# Fine Tuning Gemma2 2b for Hindi-Hinglish QnA

In this notebook we will walk through our step by step journey of fine tuning **Gemma2 2b model** into a conversational chatbot for Hindi.

This notebook will help you
  
  1. Understand the various parameters of crucial LoRA Layers. Where you will learn what the parameters do and how to tailor them for knowledge injection vs task tuning.

  2. How to effectively save your models after training and avoid unintentional inference issues.

  3. How to save resources while training as much as possible.

We used following datasets for our fine tuning.
- **GPT4's Alpaca**
- **Cognitive Lab's Hindi Instruct**
- **Wikipedia Datasets**
- **Alpaca for Gemma**
- **Databricks Dolly**
- **Hindi Maths Quest**

We experimented with different LoRA Configs in the various trainings with varying results depending on the configs

We mostly used **L4** and occasionaly **A100** GPUs as per our resource availability.

It took us about **40 Hours** to train on all the datasets, either full or a subset of them.

We learnt many things along the way specially related to the prompt for fine tuning and suitable LoRA Config for different tasks.

---


**All of our models and adapters that has been used/created in this project are available on kaggle**


You will need to place your kaggle token json file inside /root/.config/kaggle folder, you can download it from kaggle.

```python
import kagglehub

# Download latest version
path = kagglehub.model_download("lnshrivas/gemma-2/transformers/gemma-2-2b-hindi")

print("Path to model files:", path)
```

**Please pay attention to the `Notes` sections they are important to understand some crucial steps and concepts**

**Please check the `Understanding LoRA` section inside the *Conclusion* section before proceeding for enhancing your understanding about training from the getgo**

---

>DISCLAIMER - This Notebook was created as part of a Kaggle Competition

## 1. Inference Testing on base model

Let us test our base model's capacity for handling English, Hindi and Hinglish queries.

In [ ]:
!pip install -U bitsandbytes
!pip install datasets
!pip install trl
!pip install kaggle

In [ ]:
import torch
import warnings

from trl import SFTTrainer
from peft import PeftModel
from peft import LoraConfig
from tqdm.notebook import tqdm
from datasets import load_dataset

from transformers import BitsAndBytesConfig, TrainingArguments, AutoTokenizer, AutoModelForCausalLM, DataCollatorForSeq2Seq

We will download our base model first, from Kaggle.

You will also need a consent from google on kaggle to get this model. It's quite easy

https://www.kaggle.com/models/google/gemma-2/transformers/gemma-2-2b

In [ ]:
!kaggle models instances versions download google/gemma-2/transformers/gemma-2-2b/2

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.config/kaggle/kaggle.json'
Downloading gemma-2.tar.gz to /content
100% 9.05G/9.07G [00:48<00:00, 358MB/s]
100% 9.07G/9.07G [00:48<00:00, 200MB/s]
/content/gemma-2.tar.gz

We'll extract the model files

In [ ]:
!tar -xvzf 'gemma-2.tar.gz' 'gemma-2-2b'

---
>NOTE: We will load the model in 4-bit quantization for resource constraint training

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gemma-2-2b")

In [ ]:
base_model = AutoModelForCausalLM.from_pretrained("gemma-2-2b",quantization_config=bnb_config,
                                                                         device_map='auto')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
question = "<start_of_turn>user Tell me about elephants, but tell me in English please. <end of turn>\n<start_of_turn>model "

inputs = tokenizer(question, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user Tell me about elephants, but tell me in English please. <end of turn>
<start_of_turn>model 1. The elephant's name is Gungura. 2. She has light brown skin, small, dark brown tusks. Her eyes are a brown-black and she has no eyebrows, ears on top of her head with black tips, dark brown skin. Her trunk is long, with a darker trunk at the tip. Her long, white legs make the most of her body and help support her weight. The elephant has a wide, round, grey, trunk. Her trunk is long, but at the very end of the trunk has a dark-brown tip. Her trunk is long, but at the very end of the trunk has a dark-brown tip. (The trunk) is used for touching things with your nose and for breathing. Its long and thick, and it moves with your trunk. The elephant has long, grey, grey-blue, elephant ears, with black tips. This elephant has a wide, round, grey, elephant trunk, with dark-brown ears. It's a beautiful animal and a good friend, even if it is a little rough around the edges sometimes. (The ears) are the elephant's ears. They can be very useful for hunting and for seeing

In [ ]:
question = "<start_of_turn>user recycling ke vishay me ek nara sujhav kare<end of turn>\n<start_of_turn>model "

inputs = tokenizer(question, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user recycling ke vishay me ek nara sujhav kare<end of turn>
<start_of_turn>model 2/8
ServletConfig config = new ServletConfig();

	config.setServletName("web.xml");

	ServletContext servletContext = config.getServletContext();
	servletContext.setSessionTrackingPolicy(Servlet.SESSION_MODE_COOKIE);

	ServletRegistrationConfig config2 = new ServletRegistrationConfig();

	config2.setServletName("ServletRegistrationConfig");

	config2.setInitParameter("name","web.xml");


	ServletRegistrationConfig config3 = new ServletRegistrationConfig();

	config3.setInitParameter("name","myServlet");



	SessionConfig config4 = new SessionConfig();

		ServletRegistrationConfig config5 = new ServletRegistrationConfig();

		config5.setServletName("ServletRegistrationConfig");


	ServletContext servletContext2 = config2.getServletContext();


	servletContext2.setSessionTrackingPolicy(SessionTrackingPolicy.COOKIE);


	ServletContext servletContext3 = config3.getServletContext();


	servletContext3.setSessionTrackingPolicy(Servlet.SESSION_MODE_COOKIE);


	ServletRegistrationConfig config6 = new ServletRegistration

In [ ]:
question = "<start_of_turn>user रीसाइक्लिंग के विषय में एक नारा सुझाए<end of turn>\n<start_of_turn>model "

inputs = tokenizer(question, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user रीसाइक्लिंग के विषय में एक नारा सुझाए<end of turn>
<start_of_turn>model 550-year-old 80-year-old man, 2006 and 1911.

The man is a citizen of the city of 80 years of old. He came to the hospital in a wheelchair to the hospital after a car accident.
It is diagnosed and treated by the hospital.
It has been discovered that the patient's bone density is reduced by 50% and has a risk of bone fracture.
It has to take the medication for life.
It is recommended by the doctor that this man take the drug daily for a long time.
The patient agrees to this.
But, for some reason, he stops taking his medication.
He falls on the ground after taking his medication.
He was sent to the hospital again.

In the hospital, the doctor saw that the patient's condition is getting worse.
After being told the patient that he could only make it through two nights, I immediately called the family to get here.
The doctor is ready to send the patient home for hospice care.

After the patient came to the hospital for the third time.
The patient's condition was getting worse

As you can see it cannot handle hinglish nor hindi queries, Generating garbled output.

---

## 2. Fine tuning on Alpaca Dataset and making it understand Hindi

We trained for a total of **15 Hrs** on this dataset

### Dataset Preparation

> NOTE: These settings often help in reducing reserved GPU memory to increase available memory and can help in save resources for training.

In [ ]:
!export TORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

In [ ]:
!export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

In [ ]:
alpaca_dataset_train = load_dataset("FreedomIntelligence/alpaca-gpt4-hindi",
                              split = "train")
alpaca_dataset_train, alpaca_dataset_train[3]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

(Dataset({
     features: ['conversations', 'id'],
     num_rows: 49969
 }),
 {'conversations': [{'from': 'human',
    'value': 'विज्ञान शिक्षा के महत्व पर 100 शब्दों का एक पैराग्राफ लिखें।\n'},
   {'from': 'gpt',
    'value': 'विज्ञान शिक्षा संवेदनशील सोच, नवाचार और प्रौद्योगिकी के लिए आधार रखती है। इससे छात्र अपने आसपास की दुनिया को समझते हैं और पूछताछ, जिज्ञासा और तार्किक तर्क का एक भाव विकसित करते हैं। विज्ञान शिक्षा के माध्यम से छात्र समस्या का समाधान करना सीखते हैं, प्राकृतिक घटनाओं का अध्ययन करते हैं और पर्यावरण पर मनुष्य के कार्यों का प्रभाव का अध्ययन करते हैं। इसके अलावा, विज्ञान शिक्षा विज्ञान, प्रौद्योगिकी, इंजीनियरिंग और गणित (STEM) क्षेत्रों में कैरियर के लिए छात्रों को तैयार करती है जो सामाजिक और आर्थिक प्रगति के लिए ब्रेकथ्रू उत्पन्न करते हैं। इसलिए, विज्ञान शिक्षा किसी भी शैक्षिक प्रणाली का एक महत्वपूर्ण घटक है और एक राष्ट्र के लिए आवश्यक है जो वैश्विक मंच पर प्रतिस्पर्धात्मक बना रहना चाहता है।'}],
  'id': '10608'})

In [ ]:
alpaca_dataset_train.info

DatasetInfo(description='', citation='', homepage='', license='', features={'conversations': [{'from': Value(dtype='string', id=None), 'value': Value(dtype='string', id=None)}], 'id': Value(dtype='string', id=None)}, post_processed=None, supervised_keys=None, builder_name='json', dataset_name='alpaca-gpt4-hindi', config_name='default', version=0.0.0, splits={'train': SplitInfo(name='train', num_bytes=94243803, num_examples=49969, shard_lengths=None, dataset_name='alpaca-gpt4-hindi')}, download_checksums={'hf://datasets/FreedomIntelligence/alpaca-gpt4-hindi@fcd2e9a085696cf16a040df158eb31d1cd74c212/alpaca-gpt4-hindi.json': {'num_bytes': 101647883, 'checksum': None}}, download_size=101647883, post_processing_size=None, dataset_size=94243803, size_in_bytes=195891686)

In [ ]:
alpaca_prompt="""<start_of_turn>user\n.\n\"{}\"<end_of_turn>\n<start_of_turn>model\n{}<end_of_turn>"""
print(alpaca_prompt)

<start_of_turn>user
.
"{}"<end_of_turn>
<start_of_turn>model
{}<end_of_turn>

---

> NOTE: We have set the padding to right. This will ensure the padding will be added to the right of the tokens. Without this tokenizer may pad to the left.

In [ ]:
eos_token = tokenizer.eos_token
tokenizer.padding_side = "right"
eos_token

'<eos>'

In [ ]:
def formatting_func(conversations):
    texts = []
    conversations = conversations["conversations"]
    for convo in conversations:
        # EOS_TOKEN is important
        text = alpaca_prompt.format(convo[0]["value"], convo[1]["value"]) + eos_token
        texts.append(text)
    return { "text" : texts, }

In [ ]:
alpaca_dataset = alpaca_dataset_train.map(formatting_func, batched = True,)

In [ ]:
alpaca_dataset

Dataset({
    features: ['conversations', 'id', 'text'],
    num_rows: 49969
})

---

> NOTE: This prompt will help our model understand the user query and model generation part. The eos (end of sentence) token is very important without which the model will use to know when to stop regardless of max seq length to generate otherwise it will generate endless tokens which we will see happening in action, ahead

In [ ]:
print(alpaca_dataset["text"][0])

<start_of_turn>user
.
"कुछ एक रीसाइक्लिंग अभियान के लिए एक नारा सुझाव दें।
"<end_of_turn>
<start_of_turn>model
1. "ग्रीन भविष्य के लिए एक साथ: कम करें, पुन: उपयोग करें, रीसाइकल करें।"
2. "एक बेहतर कल के लिए आज ही रीसाइकल करें।"
3. "अपने कचरे को खजाना बनाएं - रीसाइकल करें!"
4. "जीवन के चक्र के लिए रीसाइकल करें।"
5. "संसाधन बचाएं, अधिक रीसाइकल करें।"<end_of_turn><eos>

---

> NOTE: This function converts the generated prompt text into tokens along with padding, and also generates attention masks for our tokens, telling the model which tokens to pay attention to and ignore the padding tokens

In [ ]:
def tokenize_function(examples):
    tokenized = tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=1024,
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

print("Tokenizing dataset...")
dataset = alpaca_dataset.map(tokenize_function, batched=True, remove_columns=["text"])
print("Dataset tokenized:", dataset[0])

Tokenizing dataset...
Dataset tokenized: {'conversations': [{'from': 'human', 'value': 'कुछ एक रीसाइक्लिंग अभियान के लिए एक नारा सुझाव दें।\n'}, {'from': 'gpt', 'value': '1. "ग्रीन भविष्य के लिए एक साथ: कम करें, पुन: उपयोग करें, रीसाइकल करें।"\n2. "एक बेहतर कल के लिए आज ही रीसाइकल करें।"\n3. "अपने कचरे को खजाना बनाएं - रीसाइकल करें!"\n4. "जीवन के चक्र के लिए रीसाइकल करें।"\n5. "संसाधन बचाएं, अधिक रीसाइकल करें।"'}], 'id': '23712', 'input_ids': [2, 106, 1645, 108, 235265, 108, 235281, 132527, 236974, 15848, 9184, 210123, 33608, 17640, 235620, 42828, 84735, 24081, 235530, 6777, 19126, 15848, 7578, 38266, 53474, 238385, 40936, 188793, 235940, 108, 235281, 107, 108, 106, 2516, 108, 235274, 235265, 664, 164624, 235530, 12076, 38311, 212133, 6777, 19126, 15848, 36631, 235292, 72792, 38607, 235269, 163169, 235292, 86467, 38607, 235269, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 108, 235284, 235265, 664, 124025, 193899, 103217, 2280, 235620, 6777, 19126, 133533, 40778, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 108, 235304, 235265, 664, 148723, 9396, 2280, 236062, 36352, 11276, 20973, 62657, 10993, 57460, 62018, 728, 9184, 210123, 33608, 144122, 38607, 4496, 108, 235310, 235265, 664, 235800, 59876, 235530, 6777, 14980, 59256, 6777, 19126, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 108, 235308, 235265, 664, 116930, 42332, 202787, 7320, 71431, 62018, 235269, 56741, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 107, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [2, 106, 1645, 108, 235265, 108, 235281, 132527, 236974, 15848, 9184, 210123, 33608, 17640, 235620, 42828, 84735, 24081, 235530, 6777, 19126, 15848, 7578, 38266, 53474, 238385, 40936, 188793, 235940, 108, 235281, 107, 108, 106, 2516, 108, 235274, 235265, 664, 164624, 235530, 12076, 38311, 212133, 6777, 19126, 15848, 36631, 235292, 72792, 38607, 235269, 163169, 235292, 86467, 38607, 235269, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 108, 235284, 235265, 664, 124025, 193899, 103217, 2280, 235620, 6777, 19126, 133533, 40778, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 108, 235304, 235265, 664, 148723, 9396, 2280, 236062, 36352, 11276, 20973, 62657, 10993, 57460, 62018, 728, 9184, 210123, 33608, 144122, 38607, 4496, 108, 235310, 235265, 664, 235800, 59876, 235530, 6777, 14980, 59256, 6777, 19126, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 108, 235308, 235265, 664, 116930, 42332, 202787, 7320, 71431, 62018, 235269, 56741, 9184, 210123, 33608, 144122, 38607, 235940, 235281, 107, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

---
### Training

> NOTE: This LoRA Config helped us generalize faster with our dataset, however if you wish to inject knowledge to ur model
- keep **"r"** high
- remove the feed forward layers from target modules
- use_rslora=False

> However in our implementation we didn't follow through it.

> To save resources while training
- use smaller batch size
- keep gradient accumulation to 1
- save limit to 1 or 2
- set a torch empty cache parameter other wise after long runs the build up of cache will crash the GPU

> This will help keep the GPU Memory requirements under 20 GBs. Suitable for L4 GPU

In [ ]:
lora_config = LoraConfig(
    r=128,
    lora_alpha=256,
    target_modules=["q_proj", "o_proj", "k_proj", "v_proj", "gate_proj", "up_proj", "down_proj"],
    modules_to_save=["embed_tokens", "lm_head"],
    task_type="CAUSAL_LM",
    use_rslora=True
)

train_args = TrainingArguments(
    per_device_train_batch_size=2,  # Each GPU processes 2 examples per step.
    gradient_accumulation_steps=1,  # Gradients are accumulated over 1 steps before updating weights.
    # warmup_steps=30,  # Learning rate warms up (gradually increases) for the first 30 steps.
    #max_steps=10,  # Total number of optimization steps for training.
    warmup_ratio=0.1, # Learning rate warms up (gradually increases) for the first 10 percent of epoch.
    num_train_epochs=1,  # Total number of epochs for training.
    gradient_checkpointing=True,  # Saves memory by recomputing activations during backpropagation.
    learning_rate=5e-5,  # Base learning rate for the optimizer.
    fp16=not torch.cuda.is_bf16_supported(),  # FP16 precision if BF16 is not available.
    bf16=torch.cuda.is_bf16_supported(),  # Enables bfloat16 precision if available.
    save_steps=100,  # Saves checkpoint every 100 steps.
    torch_empty_cache_steps = 100,  # Empties the cache at every 100 steps.
    optim="adamw_8bit",  # Uses AdamW optimizer with 8-bit precision for optimizer states to save memory.
    weight_decay=0.01,  # Regularization to prevent overfitting by penalizing large weights.
    lr_scheduler_type="linear",  # Linearly decays learning rate after the warmup period.
    output_dir="gemma-2-2b-{hi)-alpaca-chk",  # Directory where model checkpoints and logs will be saved.
    report_to="none",  # Disables logging to external tools like TensorBoard or WandB.
    save_total_limit=2, # Will save only 2 checkpoints at max, reducing the disk usage.
    run_name='pretrain_gemma2' # Defining a name for our runtime.
)

---
> NOTE: In both tokenizer and collator some arguments are commmon.
- **padding** 'longest' to find the longest batch and pad based on that
- **padding** 'max_length' will then require u to set a
  - **max_length** parameter for padding,
  - **truncation** parameter to cut any sequences longer than max_length

In [ ]:
# If you did not tokenized the dataset, you must use Data Collator.
# It uses tokenizer, tokenize your training data and returns them as tensors.
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=base_model,
    padding="longest",
    return_tensors="pt"
)

trainer = SFTTrainer(
    model=base_model,
    tokenizer=tokenizer,
    args=train_args,
    peft_config=lora_config,
    train_dataset=dataset,
    data_collator=data_collator,
)

<ipython-input-14-2ae35be4ed0d>:12: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(

In [ ]:
# To begin training use
trainer.train()

In [ ]:
# To resume training from last checkpoint use
trainer.train(resume_from_checkpoint=True)

In [ ]:
# Once training is done save the model and the tokenizer
trainer.save_model('gemma-2-2b-(hi)-24985steps-1epoch-alphacha')
trainer.tokenzier.save_pretrained('gemma-2-2b-(hi)-24985steps-1epoch-alphacha')

> NOTE: The training loss as you can see gets low quickly and can go even lower as we training it for more epochs

---
### Inference

For inference you will need to merge the base model and adapter model like this

> NOTE: Always merge a non quantized base model with the adapter to avoid rounding errors during inference and causing unexpected behaviour

In [ ]:
model = PeftModel.from_pretrained(AutoModelForCausalLM.from_pretrained('gemma-2-2b', device_map="cpu"), 'gemma-2-2b-24985steps-1epoch-alphacha')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
question = "कुछ एक रीसाइक्लिंग अभियान के लिए एक नारा सुझाव दें।"



inputs = tokenizer(question, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=128,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

कुछ एक रीसाइक्लिंग अभियान के लिए एक नारा सुझाव दें।
"
model
1. "एकल उपयोग पर दोबारा उपयोग करने के लिए, केवल रीसाइक्ल करें"
2. "हर कदम से शुरू करें, हर भोजन में बदलें"
3. "आवश्यक सामग्री के लिए प्लास्टिक से बने प्लास्टिक की मात्रा को कम करना"
4. "अपनी उत्पादन को सुधारते हुए प्लास्टिक के उपभोग को कम करना"
5. "अनावश्यक सामग्री की एकल उपयोग से दोबारा उपयोग करें, फिर से उपयोग करें"

You can see how the model is now able to answer to a hindi query that according to the dataset it has learned from

---

### Saving the model as transformer file

> NOTE: These steps are very curcial for ensuring the model weights are properly transfered as without this we faced an inference loss where our saved pretrained model wasn't able to infer properly without the state dictionary weight transfer so we made it a default saving frame work for us

In [ ]:
merged_model.save_pretrained("gemma-2-2b-tmp")

In [ ]:
torch.save(merged_model.state_dict(), "merged_model_state_dict.pth")

In [ ]:
model = AutoModelForCausalLM.from_pretrained("gemma-2-2b-tmp",device_map='cpu')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
model.load_state_dict(torch.load("merged_model_state_dict.pth", weights_only=True))

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gemma-2-2b-{hi)-24985steps-1epoch-alphacha")

In [ ]:
model.save_pretrained("gemma-2-2b-base+alpaca")

In [ ]:
tokenizer.save_pretrained("gemma-2-2b-base+alpaca")

Saved model inference -

In [ ]:
question = "कुछ एक रीसाइक्लिंग अभियान के लिए एक नारा सुझाव दें।"

inputs = tokenizer(question, return_tensors="pt").to('cpu')

generated_ids = model.generate(**inputs,
                              max_new_tokens=128,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

कुछ एक रीसाइक्लिंग अभियान के लिए एक नारा सुझाव दें।"
model
"एक सचमुच रीसाइक्लिंग अभियान के लिए एक नारा सुझाव है "हर बार रीसाइक्ल करें - हर बार रीसाइकल करें!"

---
## 3. Fine tuning on Congitive Lab Hindi Instruct Dataset

We decided to further fine tune our model on another dataset to test what kind of changes will that bring to our model and possibly increase its knowledge base further (it didn't go very well)

Here's where we learnt the importance of definining the perfect LoRA Configs to train or fine tune any LLM

We trained for a total of **20 Hrs** on this dataset

> NOTE: We will always load a quantized model for training.

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gemma-2-2b-base+alpaca")

In [ ]:
base_model = AutoModelForCausalLM.from_pretrained("gemma-2-2b-base+alpaca",quantization_config=bnb_config,
                                                                         device_map='auto')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

---
> NOTE: In this data set as we can see they tried to help the model understand the previous user-model interactions which can be useful if you want to instruction tune it to understand how to use previous conversations when you are using History in an LLM

> However there is a major issue in the training prompt. Can you see it? We accidentally trained our model on this dataset without rectifying the issue which led to a big problem during inference which we will see ahead

> We will also delve into ways of resolving that issue in a lot cheaper way

### Dataset Preparation

In [ ]:
cognitive_hi_inst_train = load_dataset("CognitiveLab/Hindi-Instruct", split='train')
cognitive_hi_inst_test = load_dataset("CognitiveLab/Hindi-Instruct", split='test')

In [ ]:
cognitive_hi_inst_train, print(cognitive_hi_inst_train[0]['text']), print(cognitive_hi_inst_train[0]['input_ids'])

<start_of_turn>user Tell me everything you know about Hitesh Mehta, but tell me in Hindi please. <end_of_turn>
<start_of_turn>model हितेश मेहता का जन्म 1959 में नैरोबी, केन्या में हुआ था। वह एक भारतीय परिवार से संबंधित थे। हितेश एक आर्किटेक्ट और एक प्रभावशाली क्रिकेट खिलाड़ी थे। 1979 और 1980 के शुरुआती वर्षों में, हितेश ने पूर्वी अफ्रीका और केन्या के लिए क्रिकेट मैच खेले। उन्होंने ICC ट्रॉफी में केन्या के लिए 12 मैच खेले। साथ ही, उन्होंने 1986 में केन्या के खिलाफ पाकिस्तान स्टारलेट्स के खिलाफ एक महत्वपूर्ण मैच खेला जिसमें उन्होंने कुल 56 रन बनाए और स्टारलेट्स की पहली पारी में तीन विकेट लिए। क्रिकेट के अलावा, हितेश को 'ईको-आर्किटेक्ट' के रूप में भी जाना जाता है। वे 2006 में नेशनल जियोग्राफिक एडवेंचर द्वारा सस्टेनेबल टूरिज्म में पांच वैश्विक अगुआओं में से एक के रूप में मान्यता प्राप्त हुई थी। उन्होंने 2010 में 'ऑथेंटिक ईकोलॉज' नामक पुस्तक लिखी थी जिसका प्रकाशन HarperCollins ने किया था। <end_of_turn>
<start_of_turn>user क्या वह अब भी क्रिकेट खेलते हैं? <end_of_turn>
<start_of_turn>model इस समय कोई सबूत या रिपोर्ट नहीं है जो सुझाव दे कि हितेश मेहता अब भी क्रिकेट खेलते हैं। उनका महत्वपूर्ण योगदान 1970 के दशक के अंत और 1980 के दशक की शुरुआत में था। <end_of_turn>
<start_of_turn>user क्या उन्होंने कोई अन्य पुस्तक लिखी है? <end_of_turn>
<start_of_turn>model उपलब्ध जानकारी के अनुसार, 2010 में HarperCollins द्वारा प्रकाशित उनकी पुस्तक 'ऑथेंटिक ईकोलॉज' उनका सबसे पहचाना जाने वाला काम है। उनके द्वारा लिखी गई अन्य किताबों के बारे में कोई विवरण नहीं है। <end_of_turn>

[2, 106, 1645, 22387, 682, 4553, 692, 1230, 1105, 640, 188719, 116890, 235269, 901, 3337, 682, 575, 40686, 3743, 235265, 235248, 107, 108, 106, 2516, 3912, 13568, 33664, 59481, 235571, 9043, 11201, 7516, 191672, 235248, 235274, 235315, 235308, 235315, 9192, 7578, 235820, 61119, 91803, 235269, 6777, 235530, 14767, 9192, 96491, 39578, 235940, 59483, 15848, 201940, 195236, 11670, 151318, 79318, 235940, 3912, 13568, 33664, 15848, 9876, 8592, 49122, 224537, 63462, 12500, 15848, 155945, 236013, 97200, 82046, 11558, 43696, 167142, 90895, 79318, 235940, 235248, 235274, 235315, 235324, 235315, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 150630, 236244, 22457, 107455, 10370, 9192, 235269, 3912, 13568, 33664, 24220, 161306, 235557, 8104, 236559, 40831, 22729, 12500, 6777, 235530, 14767, 6777, 19126, 82046, 11558, 43696, 113057, 236062, 226612, 19346, 235940, 107539, 64538, 140568, 237351, 141419, 9192, 6777, 235530, 14767, 6777, 19126, 235248, 235274, 235284, 113057, 236062, 226612, 19346, 235940, 36631, 40778, 235269, 107539, 235248, 235274, 235315, 235321, 235318, 9192, 6777, 235530, 14767, 6777, 167142, 236559, 62532, 49122, 110354, 235530, 104931, 155095, 62607, 6777, 167142, 236559, 15848, 170046, 113057, 236062, 226612, 17285, 193765, 107539, 203493, 235248, 235308, 235318, 9184, 235530, 57460, 235946, 12500, 104931, 155095, 62607, 10033, 45433, 33920, 4587, 37736, 9192, 144590, 79740, 43696, 19126, 235940, 82046, 11558, 43696, 6777, 214959, 235269, 3912, 13568, 33664, 11276, 777, 236816, 23643, 235290, 236244, 8592, 49122, 224537, 63462, 235303, 6777, 48864, 9192, 26032, 185225, 58426, 6032, 235940, 59818, 235248, 235284, 235276, 235276, 235318, 9192, 24220, 236013, 66489, 7516, 19900, 28513, 159874, 236559, 11558, 12255, 236127, 235699, 6300, 220330, 60888, 3640, 52975, 235483, 9396, 150096, 28845, 101627, 97574, 108138, 9192, 4587, 36581, 236062, 142927, 154955, 11558, 8104, 137213, 236244, 48300, 9192, 11670, 15848, 6777, 48864, 9192, 61371, 10289, 9043, 93150, 125445, 71219, 235940, 107539, 235248, 235284, 235276, 235274, 235276, 9192, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 94897, 235456, 82701, 45884, 235456, 113117, 235557, 71219, 71050, 22729, 12218, 22729, 72768, 35753, 93276, 24220, 35430, 39578, 235940, 235248, 107, 108, 106, 1645, 47754, 59483, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235336, 235248, 107, 108, 106, 2516, 22163, 70086, 72328, 63103, 182366, 32046, 9184, 64363, 174409, 25305, 6032, 38750, 53474, 238385, 40936, 26582, 12704, 3912, 13568, 33664, 59481, 235571, 9043, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235940, 50841, 22729, 170046, 145491, 169760, 235248, 235274, 235315, 235324, 235276, 6777, 8511, 236013, 235456, 6777, 124970, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 8511, 236013, 235456, 10033, 150630, 236244, 235550, 9192, 39578, 235940, 235248, 107, 108, 106, 1645, 47754, 107539, 72328, 100150, 82701, 45884, 235456, 113117, 235557, 6032, 235336, 235248, 107, 108, 106, 2516, 187982, 153322, 6777, 178375, 235269, 235248, 235284, 235276, 235274, 235276, 9192, 35753, 93276, 60888, 172684, 13568, 156402, 82701, 45884, 235456, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 50841, 22729, 96110, 45433, 71431, 10993, 125954, 196958, 82489, 6032, 235940, 107566, 60888, 113117, 235557, 86958, 100150, 219113, 10370, 6777, 99172, 9192, 72328, 163714, 25305, 6032, 235940, 235248, 107, 108, 1]

(Dataset({
     features: ['messages', 'prompt', 'text', 'input_ids', 'attention_mask'],
     num_rows: 91328
 }),
 None,
 None)

This tokenizer is more or less the same as we used for the other dataset

In [ ]:
def tokenize_function(examples):
    tokenizer.padding_side = "right"
    tokenized = tokenizer(
        examples["text"],
        padding="max_length",
        max_length=1024,
        truncation=True,
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

print("Tokenizing dataset...")
train_dataset = cognitive_hi_inst_train.map(tokenize_function, batched=True, remove_columns=["text"])
test_dataset = cognitive_hi_inst_test.map(tokenize_function, batched=True, remove_columns=["text"])
print("Dataset tokenized:", train_dataset[0])

Tokenizing dataset...

Map:   0%|          | 0/91328 [00:00<?, ? examples/s]

Map:   0%|          | 0/10148 [00:00<?, ? examples/s]

Dataset tokenized: {'messages': [{'content': 'Tell me everything you know about Hitesh Mehta, but tell me in Hindi please.', 'role': 'user'}, {'content': "हितेश मेहता का जन्म 1959 में नैरोबी, केन्या में हुआ था। वह एक भारतीय परिवार से संबंधित थे। हितेश एक आर्किटेक्ट और एक प्रभावशाली क्रिकेट खिलाड़ी थे। 1979 और 1980 के शुरुआती वर्षों में, हितेश ने पूर्वी अफ्रीका और केन्या के लिए क्रिकेट मैच खेले। उन्होंने ICC ट्रॉफी में केन्या के लिए 12 मैच खेले। साथ ही, उन्होंने 1986 में केन्या के खिलाफ पाकिस्तान स्टारलेट्स के खिलाफ एक महत्वपूर्ण मैच खेला जिसमें उन्होंने कुल 56 रन बनाए और स्टारलेट्स की पहली पारी में तीन विकेट लिए। क्रिकेट के अलावा, हितेश को 'ईको-आर्किटेक्ट' के रूप में भी जाना जाता है। वे 2006 में नेशनल जियोग्राफिक एडवेंचर द्वारा सस्टेनेबल टूरिज्म में पांच वैश्विक अगुआओं में से एक के रूप में मान्यता प्राप्त हुई थी। उन्होंने 2010 में 'ऑथेंटिक ईकोलॉज' नामक पुस्तक लिखी थी जिसका प्रकाशन HarperCollins ने किया था।", 'role': 'assistant'}, {'content': 'क्या वह अब भी क्रिकेट खेलते हैं?', 'role': 'user'}, {'content': 'इस समय कोई सबूत या रिपोर्ट नहीं है जो सुझाव दे कि हितेश मेहता अब भी क्रिकेट खेलते हैं। उनका महत्वपूर्ण योगदान 1970 के दशक के अंत और 1980 के दशक की शुरुआत में था।', 'role': 'assistant'}, {'content': 'क्या उन्होंने कोई अन्य पुस्तक लिखी है?', 'role': 'user'}, {'content': "उपलब्ध जानकारी के अनुसार, 2010 में HarperCollins द्वारा प्रकाशित उनकी पुस्तक 'ऑथेंटिक ईकोलॉज' उनका सबसे पहचाना जाने वाला काम है। उनके द्वारा लिखी गई अन्य किताबों के बारे में कोई विवरण नहीं है।", 'role': 'assistant'}], 'prompt': "<start_of_turn>user Tell me everything you know about Hitesh Mehta, but tell me in Hindi please. <end_of_turn>\n<start_of_turn>model हितेश मेहता का जन्म 1959 में नैरोबी, केन्या में हुआ था। वह एक भारतीय परिवार से संबंधित थे। हितेश एक आर्किटेक्ट और एक प्रभावशाली क्रिकेट खिलाड़ी थे। 1979 और 1980 के शुरुआती वर्षों में, हितेश ने पूर्वी अफ्रीका और केन्या के लिए क्रिकेट मैच खेले। उन्होंने ICC ट्रॉफी में केन्या के लिए 12 मैच खेले। साथ ही, उन्होंने 1986 में केन्या के खिलाफ पाकिस्तान स्टारलेट्स के खिलाफ एक महत्वपूर्ण मैच खेला जिसमें उन्होंने कुल 56 रन बनाए और स्टारलेट्स की पहली पारी में तीन विकेट लिए। क्रिकेट के अलावा, हितेश को 'ईको-आर्किटेक्ट' के रूप में भी जाना जाता है। वे 2006 में नेशनल जियोग्राफिक एडवेंचर द्वारा सस्टेनेबल टूरिज्म में पांच वैश्विक अगुआओं में से एक के रूप में मान्यता प्राप्त हुई थी। उन्होंने 2010 में 'ऑथेंटिक ईकोलॉज' नामक पुस्तक लिखी थी जिसका प्रकाशन HarperCollins ने किया था। <end_of_turn>\n<start_of_turn>user क्या वह अब भी क्रिकेट खेलते हैं? <end_of_turn>\n<start_of_turn>model इस समय कोई सबूत या रिपोर्ट नहीं है जो सुझाव दे कि हितेश मेहता अब भी क्रिकेट खेलते हैं। उनका महत्वपूर्ण योगदान 1970 के दशक के अंत और 1980 के दशक की शुरुआत में था। <end_of_turn>\n<start_of_turn>user क्या उन्होंने कोई अन्य पुस्तक लिखी है? <end_of_turn>\n<start_of_turn>model उपलब्ध जानकारी के अनुसार, 2010 में HarperCollins द्वारा प्रकाशित उनकी पुस्तक 'ऑथेंटिक ईकोलॉज' उनका सबसे पहचाना जाने वाला काम है। उनके द्वारा लिखी गई अन्य किताबों के बारे में कोई विवरण नहीं है। <end_of_turn>\n", 'input_ids': [2, 106, 1645, 22387, 682, 4553, 692, 1230, 1105, 640, 188719, 116890, 235269, 901, 3337, 682, 575, 40686, 3743, 235265, 235248, 107, 108, 106, 2516, 3912, 13568, 33664, 59481, 235571, 9043, 11201, 7516, 191672, 235248, 235274, 235315, 235308, 235315, 9192, 7578, 235820, 61119, 91803, 235269, 6777, 235530, 14767, 9192, 96491, 39578, 235940, 59483, 15848, 201940, 195236, 11670, 151318, 79318, 235940, 3912, 13568, 33664, 15848, 9876, 8592, 49122, 224537, 63462, 12500, 15848, 155945, 236013, 97200, 82046, 11558, 43696, 167142, 90895, 79318, 235940, 235248, 235274, 235315, 235324, 235315, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 150630, 236244, 22457, 107455, 10370, 9192, 235269, 3912, 13568, 33664, 24220, 161306, 235557, 8104, 236559, 40831, 22729, 12500, 6777, 235530, 14767, 6777, 19126, 82046, 11558, 43696, 113057, 236062, 226612, 19346, 235940, 107539, 64538, 140568, 237351, 141419, 9192, 6777, 235530, 14767, 6777, 19126, 235248, 235274, 235284, 113057, 236062, 226612, 19346, 235940, 36631, 40778, 235269, 107539, 235248, 235274, 235315, 235321, 235318, 9192, 6777, 235530, 14767, 6777, 167142, 236559, 62532, 49122, 110354, 235530, 104931, 155095, 62607, 6777, 167142, 236559, 15848, 170046, 113057, 236062, 226612, 17285, 193765, 107539, 203493, 235248, 235308, 235318, 9184, 235530, 57460, 235946, 12500, 104931, 155095, 62607, 10033, 45433, 33920, 4587, 37736, 9192, 144590, 79740, 43696, 19126, 235940, 82046, 11558, 43696, 6777, 214959, 235269, 3912, 13568, 33664, 11276, 777, 236816, 23643, 235290, 236244, 8592, 49122, 224537, 63462, 235303, 6777, 48864, 9192, 26032, 185225, 58426, 6032, 235940, 59818, 235248, 235284, 235276, 235276, 235318, 9192, 24220, 236013, 66489, 7516, 19900, 28513, 159874, 236559, 11558, 12255, 236127, 235699, 6300, 220330, 60888, 3640, 52975, 235483, 9396, 150096, 28845, 101627, 97574, 108138, 9192, 4587, 36581, 236062, 142927, 154955, 11558, 8104, 137213, 236244, 48300, 9192, 11670, 15848, 6777, 48864, 9192, 61371, 10289, 9043, 93150, 125445, 71219, 235940, 107539, 235248, 235284, 235276, 235274, 235276, 9192, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 94897, 235456, 82701, 45884, 235456, 113117, 235557, 71219, 71050, 22729, 12218, 22729, 72768, 35753, 93276, 24220, 35430, 39578, 235940, 235248, 107, 108, 106, 1645, 47754, 59483, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235336, 235248, 107, 108, 106, 2516, 22163, 70086, 72328, 63103, 182366, 32046, 9184, 64363, 174409, 25305, 6032, 38750, 53474, 238385, 40936, 26582, 12704, 3912, 13568, 33664, 59481, 235571, 9043, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235940, 50841, 22729, 170046, 145491, 169760, 235248, 235274, 235315, 235324, 235276, 6777, 8511, 236013, 235456, 6777, 124970, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 8511, 236013, 235456, 10033, 150630, 236244, 235550, 9192, 39578, 235940, 235248, 107, 108, 106, 1645, 47754, 107539, 72328, 100150, 82701, 45884, 235456, 113117, 235557, 6032, 235336, 235248, 107, 108, 106, 2516, 187982, 153322, 6777, 178375, 235269, 235248, 235284, 235276, 235274, 235276, 9192, 35753, 93276, 60888, 172684, 13568, 156402, 82701, 45884, 235456, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 50841, 22729, 96110, 45433, 71431, 10993, 125954, 196958, 82489, 6032, 235940, 107566, 60888, 113117, 235557, 86958, 100150, 219113, 10370, 6777, 99172, 9192, 72328, 163714, 25305, 6032, 235940, 235248, 107, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [2, 106, 1645, 22387, 682, 4553, 692, 1230, 1105, 640, 188719, 116890, 235269, 901, 3337, 682, 575, 40686, 3743, 235265, 235248, 107, 108, 106, 2516, 3912, 13568, 33664, 59481, 235571, 9043, 11201, 7516, 191672, 235248, 235274, 235315, 235308, 235315, 9192, 7578, 235820, 61119, 91803, 235269, 6777, 235530, 14767, 9192, 96491, 39578, 235940, 59483, 15848, 201940, 195236, 11670, 151318, 79318, 235940, 3912, 13568, 33664, 15848, 9876, 8592, 49122, 224537, 63462, 12500, 15848, 155945, 236013, 97200, 82046, 11558, 43696, 167142, 90895, 79318, 235940, 235248, 235274, 235315, 235324, 235315, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 150630, 236244, 22457, 107455, 10370, 9192, 235269, 3912, 13568, 33664, 24220, 161306, 235557, 8104, 236559, 40831, 22729, 12500, 6777, 235530, 14767, 6777, 19126, 82046, 11558, 43696, 113057, 236062, 226612, 19346, 235940, 107539, 64538, 140568, 237351, 141419, 9192, 6777, 235530, 14767, 6777, 19126, 235248, 235274, 235284, 113057, 236062, 226612, 19346, 235940, 36631, 40778, 235269, 107539, 235248, 235274, 235315, 235321, 235318, 9192, 6777, 235530, 14767, 6777, 167142, 236559, 62532, 49122, 110354, 235530, 104931, 155095, 62607, 6777, 167142, 236559, 15848, 170046, 113057, 236062, 226612, 17285, 193765, 107539, 203493, 235248, 235308, 235318, 9184, 235530, 57460, 235946, 12500, 104931, 155095, 62607, 10033, 45433, 33920, 4587, 37736, 9192, 144590, 79740, 43696, 19126, 235940, 82046, 11558, 43696, 6777, 214959, 235269, 3912, 13568, 33664, 11276, 777, 236816, 23643, 235290, 236244, 8592, 49122, 224537, 63462, 235303, 6777, 48864, 9192, 26032, 185225, 58426, 6032, 235940, 59818, 235248, 235284, 235276, 235276, 235318, 9192, 24220, 236013, 66489, 7516, 19900, 28513, 159874, 236559, 11558, 12255, 236127, 235699, 6300, 220330, 60888, 3640, 52975, 235483, 9396, 150096, 28845, 101627, 97574, 108138, 9192, 4587, 36581, 236062, 142927, 154955, 11558, 8104, 137213, 236244, 48300, 9192, 11670, 15848, 6777, 48864, 9192, 61371, 10289, 9043, 93150, 125445, 71219, 235940, 107539, 235248, 235284, 235276, 235274, 235276, 9192, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 94897, 235456, 82701, 45884, 235456, 113117, 235557, 71219, 71050, 22729, 12218, 22729, 72768, 35753, 93276, 24220, 35430, 39578, 235940, 235248, 107, 108, 106, 1645, 47754, 59483, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235336, 235248, 107, 108, 106, 2516, 22163, 70086, 72328, 63103, 182366, 32046, 9184, 64363, 174409, 25305, 6032, 38750, 53474, 238385, 40936, 26582, 12704, 3912, 13568, 33664, 59481, 235571, 9043, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235940, 50841, 22729, 170046, 145491, 169760, 235248, 235274, 235315, 235324, 235276, 6777, 8511, 236013, 235456, 6777, 124970, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 8511, 236013, 235456, 10033, 150630, 236244, 235550, 9192, 39578, 235940, 235248, 107, 108, 106, 1645, 47754, 107539, 72328, 100150, 82701, 45884, 235456, 113117, 235557, 6032, 235336, 235248, 107, 108, 106, 2516, 187982, 153322, 6777, 178375, 235269, 235248, 235284, 235276, 235274, 235276, 9192, 35753, 93276, 60888, 172684, 13568, 156402, 82701, 45884, 235456, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 50841, 22729, 96110, 45433, 71431, 10993, 125954, 196958, 82489, 6032, 235940, 107566, 60888, 113117, 235557, 86958, 100150, 219113, 10370, 6777, 99172, 9192, 72328, 163714, 25305, 6032, 235940, 235248, 107, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

### Training

---
> NOTE: This time we decided to
- only focus on the attention and feed forward layers and
- exclude the embedding and lm layers while training.

> We also reduced
- **"r"** and
- lora_alpha
- torch empty cache parameter to save more vram for larger batch size

> We will see its consequences ahead

In [ ]:
lora_config = LoraConfig(
    r=32,
    lora_alpha=128,
    target_modules=["q_proj", "o_proj", "k_proj", "v_proj","gate_proj", "up_proj", "down_proj"
                    ],
    #modules_to_save=["embed_tokens", "lm_head"],
    task_type="CAUSAL_LM",
    use_rslora=True
)

train_args = TrainingArguments(
    per_device_train_batch_size=3,  # Each GPU processes 4 examples per step.
    gradient_accumulation_steps=1,  # Gradients are accumulated over 4 steps before updating weights.
    # warmup_steps=30,  # Learning rate warms up (gradually increases) for the first 30 steps.
    #max_steps=10,  # Total number of optimization steps for training.
    warmup_ratio=0.1, # Learning rate warms up (gradually increases) for the first 10 percent of epoch.
    num_train_epochs=1,  # Total number of epochs for training.
    gradient_checkpointing=True,  # Saves memory by recomputing activations during backpropagation.
    learning_rate=5e-5,  # Base learning rate for the optimizer.
    fp16=not torch.cuda.is_bf16_supported(),  # FP16 precision if BF16 is not available.
    bf16=torch.cuda.is_bf16_supported(),  # Enables bfloat16 precision if available.
    save_steps=100,  # Saves checkpoint every 100 steps.
    torch_empty_cache_steps=10,  # Empties the cache at every 10 steps.
    optim="adamw_8bit",  # Uses AdamW optimizer with 8-bit precision for optimizer states to save memory.
    weight_decay=0.01,  # Regularization to prevent overfitting by penalizing large weights.
    lr_scheduler_type="linear",  # Linearly decays learning rate after the warmup period.
    output_dir="gemma-2-2b-cog-lab-chk",  # Directory where model checkpoints and logs will be saved.
    report_to="none",  # Disables logging to external tools like TensorBoard or WandB.
    save_total_limit=2, # Will save only 2 checkpoints at max, reducing the disk usage.
    run_name='pretrain_gemma2' # Defining a name for our runtime.
)

In [ ]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=base_model,
    padding="longest",
    return_tensors="pt"
)

trainer = SFTTrainer(
    model=base_model,
    tokenizer=tokenizer,
    args=train_args,
    peft_config=lora_config,
    train_dataset=train_dataset,
    data_collator=data_collator,
)

<ipython-input-17-5dcaa33d1df3>:12: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:359: UserWarning: You passed a dataset that is already processed (contains an `input_ids` field) together with a valid formatting function. Therefore `formatting_func` will be ignored. Either remove the `formatting_func` or pass a dataset that is not already processed.
  warnings.warn(

---
> NOTE: Notice now how the training loss didn't change too drastically unlike the last time. This can be the result of the LoRA Config, some hyper parameters or the dataset itself

In [ ]:
trainer.train()

Follow the exact same saving steps

In [ ]:
trainer.save_model("gemma-2-2b-30443steps-1epoch-cog-lab")

In [ ]:
trainer.tokenizer.save_pretrained('gemma-2-2b-30443steps-1epoch-cog-lab')

### Inference

Load the merge the base and adapter

In [ ]:
merged_model = PeftModel.from_pretrained(AutoModelForCausalLM.from_pretrained("gemma-2-2b-base+alpaca",device_map='cpu'), 'gemma-2-2b-30443steps-1epoch-cog-lab').merge_and_unload()

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
question = "<start_of_turn>user क्या आप मुझे रीसाइक्लिंग के लिए एक नारा समझा सकते हैं? <end of turn>\n<start_of_turn>model "


inputs = tokenizer(question, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user क्या आप मुझे रीसाइक्लिंग के लिए एक नारा समझा सकते हैं? <end of turn>
<start_of_turn>model 24/30 भारत की अर्थव्यवस्था के सबसे उन्नत परियोजनाओं में से एक है, और इसने सततता और पर्यावरणीय जिम्मेदारी के प्रति जागरूकता बढ़ाने में महत्वपूर्ण भूमिका निभाई है। नया आयात, 2022 में मनाया गया, इस परियोजना की व्यावहारिक गतिशीलता को देखते हुए एक नया जीवन शुरू कर दिया। इस परियोजना का एक उदाहरण स्वच्छ ईंधन और गैर-स्वच्छ ईंधन में परिवर्तन है।

यह परियोजना नौकरियों और आर्थिक विकास को बढ़ावा देने में भी महत्वपूर्ण भूमिका निभाती है। उदाहरण के लिए, फर्नीचर और वस्तुओं को स्थापित करने, ईंधन की बचत करने और स्थायी रूप से प्राप्त उत्पादों को पुनर्परिष्कार करने की प्रक्रिया का एक महत्वपूर्ण पहलू है। एक अन्य अनुसंधान 'पावर पाइपिंग' में बढ़ती हुई जागरूकता है, जिसका उद्देश्य वित्तीय रूप से

---
> NOTE: Notice how the model is unable to stop its generation unlike the last time. Can you guess why this is happening?

> That's right, the end of sentence token. If you notice in our training prompt there was no `<eos>` token. This means the model didn't learn when to stop it's generation and keeps on continuing with more tokens.

> To fix this we simply need to add the `<bos>` and `<eos>` tokens to our prompt to tell the model what is the begenning and the end of a conversation

### Saving the model

Ofc first we will save our model like before

In [ ]:
merged_model.save_pretrained("gemma-2-2b-tmp")

In [ ]:
torch.save(merged_model.state_dict(), "merged_model_state_dict.pth")

In [ ]:
model = AutoModelForCausalLM.from_pretrained("gemma-2-2b-tmp",device_map='cpu')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
model.load_state_dict(torch.load("merged_model_state_dict.pth", weights_only=True))

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gemma-2-2b-30443steps-1epoch-cog-lab")

In [ ]:
model.save_pretrained("gemma-2-2b-base+alpaca+cog-lab")

In [ ]:
tokenizer.save_pretrained("gemma-2-2b-base+alpaca+cog-lab")

### Further Fine Tuning to teach beginning and end tokens

In [ ]:
def format_prompt_with_tokens(batch):
    formatted_prompts = []
    for conversations in batch['messages']:
        formatted_prompt = []
        for i in range(0, len(conversations), 2):  # Process user-model pairs
            user_message = conversations[i]
            model_message = conversations[i + 1] if i + 1 < len(conversations) else None

            if user_message['role'] == "user" and model_message and model_message['role'] == "assistant":
                formatted_prompt.append(
                    f"<bos><start_of_turn>{user_message['role']} {user_message['content']} <end_of_turn>\n"
                    f"<start_of_turn>model {model_message['content']} <end_of_turn><eos>"
                )

        # Join the formatted prompt for this conversation
        formatted_prompts.append("\n".join(formatted_prompt))

    # Return the formatted text as a new field in the dataset
    return {"text": formatted_prompts}

---
> NOTE: This time we take 3000 samples for fine tuning the model to teach it when to use `<eos>` token

In [ ]:
# Shuffle the dataset and take 1000 examples
random_subset = cognitive_hi_inst_train.take(3000)

# Apply the formatting function to this subset
cognitive_hi_inst_dataset = random_subset.map(format_prompt_with_tokens, batched=True)

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

In [ ]:
print(cognitive_hi_inst_dataset[1]['text'])

<bos><start_of_turn>user Can you tell me about the plot of the film Vartul, but in Hindi please? <end_of_turn>
<start_of_turn>model वर्तुल एक छोटी फिल्म है जो 10 साल के एक लड़के दामू के बारे में है। उसकी माँ एक त्योहार के लिए मिठाई बनाना चाहती है और दामू को दुकान से गुड़ खरीदने के लिए भेजती है। हालांकि, वह नोटिस करता है कि पैसे के डिब्बे में सिर्फ एक सिक्का बचा है। दुकान की तरफ जाते समय, दामू अपने दोस्त गण्या के साथ दौड़ता है और वे एक शो देखने के लिए रुकते हैं। चूंकि वह शो देखने के लिए नहीं खरीद सकता, वह दुकान जाकर गुड़ खरीदता है। शो के बाद, गण्या उन्हें इसके बारे में बताता है जब वे अपनी बाइक को सवारी करते हैं।

एक जुआ खेल द्वारा आकर्षित, जहां आप एक सिक्के पर पत्थर का स्लैब फेंकते हैं, दामू कुछ पैसे कमाने का फैसला करता है। वह शुरू में जीतता है, लेकिन जब वह दुकान जाता है, दुकानदार उसे बताता है कि उसने जो सिक्का इस्तेमाल किया था, वह मान्य नहीं है। परेशान, दामू रोते हुए घर चला जाता है। <end_of_turn><eos>
<bos><start_of_turn>user फिल्म की निर्माण प्रक्रिया के बारे में बताइए। मेरा उत्तर हिंदी में ही चाहिए, कृपया। <end_of_turn>
<start_of_turn>model फिल्म वर्तुल का निर्माण मई 2008 में शुरू हुआ और जुलाई 2009 तक समाप्त हो गया। विवेक चित्र प्रोडक्शन का निर्णय था कि फिल्म के लिए क्रू का चयन किया जाए। फिल्म में मुख्य कलाकार  अश्विनी गिरी, चिन्मय पटवर्धन, अजिंक्य भिसे और शैलेश शंकर कुलकर्णी हैं। निम्न बजट के साथ भोर, महाराष्ट्र में फिल्म की शूटिंग की गई थी। सीमित बजट के साथ काम करना क्रू के लिए कई चुनौतियाँ उत्पन्न करता था। <end_of_turn><eos>
<bos><start_of_turn>user Are there any awards won by this film? And can you please respond in English this time? <end_of_turn>
<start_of_turn>model Yes, since its first screening in July 2009, 'Vartul' has been selected for 50 Film Festivals all over the world. The film has been quite successful and has won thirteen awards. However, the details of these awards are not specified. <end_of_turn><eos>

In [ ]:
def tokenize_function(examples):
    tokenizer.padding_side = "right"
    tokenized = tokenizer(
        examples["text"],
        padding="max_length",
        max_length=1024,
        truncation=True,
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

print("Tokenizing dataset...")
train_dataset = cognitive_hi_inst_dataset.map(tokenize_function, batched=True)
print("Dataset tokenized:", train_dataset[0])

Tokenizing dataset...

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

Dataset tokenized: {'messages': [{'content': 'Tell me everything you know about Hitesh Mehta, but tell me in Hindi please.', 'role': 'user'}, {'content': "हितेश मेहता का जन्म 1959 में नैरोबी, केन्या में हुआ था। वह एक भारतीय परिवार से संबंधित थे। हितेश एक आर्किटेक्ट और एक प्रभावशाली क्रिकेट खिलाड़ी थे। 1979 और 1980 के शुरुआती वर्षों में, हितेश ने पूर्वी अफ्रीका और केन्या के लिए क्रिकेट मैच खेले। उन्होंने ICC ट्रॉफी में केन्या के लिए 12 मैच खेले। साथ ही, उन्होंने 1986 में केन्या के खिलाफ पाकिस्तान स्टारलेट्स के खिलाफ एक महत्वपूर्ण मैच खेला जिसमें उन्होंने कुल 56 रन बनाए और स्टारलेट्स की पहली पारी में तीन विकेट लिए। क्रिकेट के अलावा, हितेश को 'ईको-आर्किटेक्ट' के रूप में भी जाना जाता है। वे 2006 में नेशनल जियोग्राफिक एडवेंचर द्वारा सस्टेनेबल टूरिज्म में पांच वैश्विक अगुआओं में से एक के रूप में मान्यता प्राप्त हुई थी। उन्होंने 2010 में 'ऑथेंटिक ईकोलॉज' नामक पुस्तक लिखी थी जिसका प्रकाशन HarperCollins ने किया था।", 'role': 'assistant'}, {'content': 'क्या वह अब भी क्रिकेट खेलते हैं?', 'role': 'user'}, {'content': 'इस समय कोई सबूत या रिपोर्ट नहीं है जो सुझाव दे कि हितेश मेहता अब भी क्रिकेट खेलते हैं। उनका महत्वपूर्ण योगदान 1970 के दशक के अंत और 1980 के दशक की शुरुआत में था।', 'role': 'assistant'}, {'content': 'क्या उन्होंने कोई अन्य पुस्तक लिखी है?', 'role': 'user'}, {'content': "उपलब्ध जानकारी के अनुसार, 2010 में HarperCollins द्वारा प्रकाशित उनकी पुस्तक 'ऑथेंटिक ईकोलॉज' उनका सबसे पहचाना जाने वाला काम है। उनके द्वारा लिखी गई अन्य किताबों के बारे में कोई विवरण नहीं है।", 'role': 'assistant'}], 'prompt': "<start_of_turn>user Tell me everything you know about Hitesh Mehta, but tell me in Hindi please. <end_of_turn>\n<start_of_turn>model हितेश मेहता का जन्म 1959 में नैरोबी, केन्या में हुआ था। वह एक भारतीय परिवार से संबंधित थे। हितेश एक आर्किटेक्ट और एक प्रभावशाली क्रिकेट खिलाड़ी थे। 1979 और 1980 के शुरुआती वर्षों में, हितेश ने पूर्वी अफ्रीका और केन्या के लिए क्रिकेट मैच खेले। उन्होंने ICC ट्रॉफी में केन्या के लिए 12 मैच खेले। साथ ही, उन्होंने 1986 में केन्या के खिलाफ पाकिस्तान स्टारलेट्स के खिलाफ एक महत्वपूर्ण मैच खेला जिसमें उन्होंने कुल 56 रन बनाए और स्टारलेट्स की पहली पारी में तीन विकेट लिए। क्रिकेट के अलावा, हितेश को 'ईको-आर्किटेक्ट' के रूप में भी जाना जाता है। वे 2006 में नेशनल जियोग्राफिक एडवेंचर द्वारा सस्टेनेबल टूरिज्म में पांच वैश्विक अगुआओं में से एक के रूप में मान्यता प्राप्त हुई थी। उन्होंने 2010 में 'ऑथेंटिक ईकोलॉज' नामक पुस्तक लिखी थी जिसका प्रकाशन HarperCollins ने किया था। <end_of_turn>\n<start_of_turn>user क्या वह अब भी क्रिकेट खेलते हैं? <end_of_turn>\n<start_of_turn>model इस समय कोई सबूत या रिपोर्ट नहीं है जो सुझाव दे कि हितेश मेहता अब भी क्रिकेट खेलते हैं। उनका महत्वपूर्ण योगदान 1970 के दशक के अंत और 1980 के दशक की शुरुआत में था। <end_of_turn>\n<start_of_turn>user क्या उन्होंने कोई अन्य पुस्तक लिखी है? <end_of_turn>\n<start_of_turn>model उपलब्ध जानकारी के अनुसार, 2010 में HarperCollins द्वारा प्रकाशित उनकी पुस्तक 'ऑथेंटिक ईकोलॉज' उनका सबसे पहचाना जाने वाला काम है। उनके द्वारा लिखी गई अन्य किताबों के बारे में कोई विवरण नहीं है। <end_of_turn>\n", 'text': "<bos><start_of_turn>user Tell me everything you know about Hitesh Mehta, but tell me in Hindi please. <end_of_turn>\n<start_of_turn>model हितेश मेहता का जन्म 1959 में नैरोबी, केन्या में हुआ था। वह एक भारतीय परिवार से संबंधित थे। हितेश एक आर्किटेक्ट और एक प्रभावशाली क्रिकेट खिलाड़ी थे। 1979 और 1980 के शुरुआती वर्षों में, हितेश ने पूर्वी अफ्रीका और केन्या के लिए क्रिकेट मैच खेले। उन्होंने ICC ट्रॉफी में केन्या के लिए 12 मैच खेले। साथ ही, उन्होंने 1986 में केन्या के खिलाफ पाकिस्तान स्टारलेट्स के खिलाफ एक महत्वपूर्ण मैच खेला जिसमें उन्होंने कुल 56 रन बनाए और स्टारलेट्स की पहली पारी में तीन विकेट लिए। क्रिकेट के अलावा, हितेश को 'ईको-आर्किटेक्ट' के रूप में भी जाना जाता है। वे 2006 में नेशनल जियोग्राफिक एडवेंचर द्वारा सस्टेनेबल टूरिज्म में पांच वैश्विक अगुआओं में से एक के रूप में मान्यता प्राप्त हुई थी। उन्होंने 2010 में 'ऑथेंटिक ईकोलॉज' नामक पुस्तक लिखी थी जिसका प्रकाशन HarperCollins ने किया था। <end_of_turn><eos>\n<bos><start_of_turn>user क्या वह अब भी क्रिकेट खेलते हैं? <end_of_turn>\n<start_of_turn>model इस समय कोई सबूत या रिपोर्ट नहीं है जो सुझाव दे कि हितेश मेहता अब भी क्रिकेट खेलते हैं। उनका महत्वपूर्ण योगदान 1970 के दशक के अंत और 1980 के दशक की शुरुआत में था। <end_of_turn><eos>\n<bos><start_of_turn>user क्या उन्होंने कोई अन्य पुस्तक लिखी है? <end_of_turn>\n<start_of_turn>model उपलब्ध जानकारी के अनुसार, 2010 में HarperCollins द्वारा प्रकाशित उनकी पुस्तक 'ऑथेंटिक ईकोलॉज' उनका सबसे पहचाना जाने वाला काम है। उनके द्वारा लिखी गई अन्य किताबों के बारे में कोई विवरण नहीं है। <end_of_turn><eos>", 'input_ids': [2, 2, 106, 1645, 22387, 682, 4553, 692, 1230, 1105, 640, 188719, 116890, 235269, 901, 3337, 682, 575, 40686, 3743, 235265, 235248, 107, 108, 106, 2516, 3912, 13568, 33664, 59481, 235571, 9043, 11201, 7516, 191672, 235248, 235274, 235315, 235308, 235315, 9192, 7578, 235820, 61119, 91803, 235269, 6777, 235530, 14767, 9192, 96491, 39578, 235940, 59483, 15848, 201940, 195236, 11670, 151318, 79318, 235940, 3912, 13568, 33664, 15848, 9876, 8592, 49122, 224537, 63462, 12500, 15848, 155945, 236013, 97200, 82046, 11558, 43696, 167142, 90895, 79318, 235940, 235248, 235274, 235315, 235324, 235315, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 150630, 236244, 22457, 107455, 10370, 9192, 235269, 3912, 13568, 33664, 24220, 161306, 235557, 8104, 236559, 40831, 22729, 12500, 6777, 235530, 14767, 6777, 19126, 82046, 11558, 43696, 113057, 236062, 226612, 19346, 235940, 107539, 64538, 140568, 237351, 141419, 9192, 6777, 235530, 14767, 6777, 19126, 235248, 235274, 235284, 113057, 236062, 226612, 19346, 235940, 36631, 40778, 235269, 107539, 235248, 235274, 235315, 235321, 235318, 9192, 6777, 235530, 14767, 6777, 167142, 236559, 62532, 49122, 110354, 235530, 104931, 155095, 62607, 6777, 167142, 236559, 15848, 170046, 113057, 236062, 226612, 17285, 193765, 107539, 203493, 235248, 235308, 235318, 9184, 235530, 57460, 235946, 12500, 104931, 155095, 62607, 10033, 45433, 33920, 4587, 37736, 9192, 144590, 79740, 43696, 19126, 235940, 82046, 11558, 43696, 6777, 214959, 235269, 3912, 13568, 33664, 11276, 777, 236816, 23643, 235290, 236244, 8592, 49122, 224537, 63462, 235303, 6777, 48864, 9192, 26032, 185225, 58426, 6032, 235940, 59818, 235248, 235284, 235276, 235276, 235318, 9192, 24220, 236013, 66489, 7516, 19900, 28513, 159874, 236559, 11558, 12255, 236127, 235699, 6300, 220330, 60888, 3640, 52975, 235483, 9396, 150096, 28845, 101627, 97574, 108138, 9192, 4587, 36581, 236062, 142927, 154955, 11558, 8104, 137213, 236244, 48300, 9192, 11670, 15848, 6777, 48864, 9192, 61371, 10289, 9043, 93150, 125445, 71219, 235940, 107539, 235248, 235284, 235276, 235274, 235276, 9192, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 94897, 235456, 82701, 45884, 235456, 113117, 235557, 71219, 71050, 22729, 12218, 22729, 72768, 35753, 93276, 24220, 35430, 39578, 235940, 235248, 107, 1, 108, 2, 106, 1645, 47754, 59483, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235336, 235248, 107, 108, 106, 2516, 22163, 70086, 72328, 63103, 182366, 32046, 9184, 64363, 174409, 25305, 6032, 38750, 53474, 238385, 40936, 26582, 12704, 3912, 13568, 33664, 59481, 235571, 9043, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235940, 50841, 22729, 170046, 145491, 169760, 235248, 235274, 235315, 235324, 235276, 6777, 8511, 236013, 235456, 6777, 124970, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 8511, 236013, 235456, 10033, 150630, 236244, 235550, 9192, 39578, 235940, 235248, 107, 1, 108, 2, 106, 1645, 47754, 107539, 72328, 100150, 82701, 45884, 235456, 113117, 235557, 6032, 235336, 235248, 107, 108, 106, 2516, 187982, 153322, 6777, 178375, 235269, 235248, 235284, 235276, 235274, 235276, 9192, 35753, 93276, 60888, 172684, 13568, 156402, 82701, 45884, 235456, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 50841, 22729, 96110, 45433, 71431, 10993, 125954, 196958, 82489, 6032, 235940, 107566, 60888, 113117, 235557, 86958, 100150, 219113, 10370, 6777, 99172, 9192, 72328, 163714, 25305, 6032, 235940, 235248, 107, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [2, 2, 106, 1645, 22387, 682, 4553, 692, 1230, 1105, 640, 188719, 116890, 235269, 901, 3337, 682, 575, 40686, 3743, 235265, 235248, 107, 108, 106, 2516, 3912, 13568, 33664, 59481, 235571, 9043, 11201, 7516, 191672, 235248, 235274, 235315, 235308, 235315, 9192, 7578, 235820, 61119, 91803, 235269, 6777, 235530, 14767, 9192, 96491, 39578, 235940, 59483, 15848, 201940, 195236, 11670, 151318, 79318, 235940, 3912, 13568, 33664, 15848, 9876, 8592, 49122, 224537, 63462, 12500, 15848, 155945, 236013, 97200, 82046, 11558, 43696, 167142, 90895, 79318, 235940, 235248, 235274, 235315, 235324, 235315, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 150630, 236244, 22457, 107455, 10370, 9192, 235269, 3912, 13568, 33664, 24220, 161306, 235557, 8104, 236559, 40831, 22729, 12500, 6777, 235530, 14767, 6777, 19126, 82046, 11558, 43696, 113057, 236062, 226612, 19346, 235940, 107539, 64538, 140568, 237351, 141419, 9192, 6777, 235530, 14767, 6777, 19126, 235248, 235274, 235284, 113057, 236062, 226612, 19346, 235940, 36631, 40778, 235269, 107539, 235248, 235274, 235315, 235321, 235318, 9192, 6777, 235530, 14767, 6777, 167142, 236559, 62532, 49122, 110354, 235530, 104931, 155095, 62607, 6777, 167142, 236559, 15848, 170046, 113057, 236062, 226612, 17285, 193765, 107539, 203493, 235248, 235308, 235318, 9184, 235530, 57460, 235946, 12500, 104931, 155095, 62607, 10033, 45433, 33920, 4587, 37736, 9192, 144590, 79740, 43696, 19126, 235940, 82046, 11558, 43696, 6777, 214959, 235269, 3912, 13568, 33664, 11276, 777, 236816, 23643, 235290, 236244, 8592, 49122, 224537, 63462, 235303, 6777, 48864, 9192, 26032, 185225, 58426, 6032, 235940, 59818, 235248, 235284, 235276, 235276, 235318, 9192, 24220, 236013, 66489, 7516, 19900, 28513, 159874, 236559, 11558, 12255, 236127, 235699, 6300, 220330, 60888, 3640, 52975, 235483, 9396, 150096, 28845, 101627, 97574, 108138, 9192, 4587, 36581, 236062, 142927, 154955, 11558, 8104, 137213, 236244, 48300, 9192, 11670, 15848, 6777, 48864, 9192, 61371, 10289, 9043, 93150, 125445, 71219, 235940, 107539, 235248, 235284, 235276, 235274, 235276, 9192, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 94897, 235456, 82701, 45884, 235456, 113117, 235557, 71219, 71050, 22729, 12218, 22729, 72768, 35753, 93276, 24220, 35430, 39578, 235940, 235248, 107, 1, 108, 2, 106, 1645, 47754, 59483, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235336, 235248, 107, 108, 106, 2516, 22163, 70086, 72328, 63103, 182366, 32046, 9184, 64363, 174409, 25305, 6032, 38750, 53474, 238385, 40936, 26582, 12704, 3912, 13568, 33664, 59481, 235571, 9043, 106163, 26032, 82046, 11558, 43696, 149307, 18249, 16445, 235940, 50841, 22729, 170046, 145491, 169760, 235248, 235274, 235315, 235324, 235276, 6777, 8511, 236013, 235456, 6777, 124970, 12500, 235248, 235274, 235315, 235321, 235276, 6777, 8511, 236013, 235456, 10033, 150630, 236244, 235550, 9192, 39578, 235940, 235248, 107, 1, 108, 2, 106, 1645, 47754, 107539, 72328, 100150, 82701, 45884, 235456, 113117, 235557, 6032, 235336, 235248, 107, 108, 106, 2516, 187982, 153322, 6777, 178375, 235269, 235248, 235284, 235276, 235274, 235276, 9192, 35753, 93276, 60888, 172684, 13568, 156402, 82701, 45884, 235456, 777, 239272, 236277, 149759, 11558, 98447, 23643, 235620, 237351, 235800, 235303, 50841, 22729, 96110, 45433, 71431, 10993, 125954, 196958, 82489, 6032, 235940, 107566, 60888, 113117, 235557, 86958, 100150, 219113, 10370, 6777, 99172, 9192, 72328, 163714, 25305, 6032, 235940, 235248, 107, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

---

> NOTE: The rest of the things are the same.
- We added a small dropout to try to prevent content bias

In [ ]:
lora_config = LoraConfig(
    r=128,
    lora_alpha=256,
    target_modules=["q_proj", "o_proj", "k_proj", "v_proj","gate_proj", "up_proj", "down_proj",],
    lora_dropout=0.05,
    #modules_to_save=["embed_tokens", "lm_head"],
    task_type="CAUSAL_LM",
    use_rslora=True
)

train_args = TrainingArguments(
    per_device_train_batch_size=3,  # Each GPU processes 4 examples per step.
    gradient_accumulation_steps=1,  # Gradients are accumulated over 4 steps before updating weights.
    warmup_steps=30,  # Learning rate warms up (gradually increases) for the first 30 steps.
    #max_steps=1000,  # Total number of optimization steps for training.
    warmup_ratio=0.1, # Learning rate warms up (gradually increases) for the first 10 percent of epoch.
    num_train_epochs=1,  # Total number of epochs for training.
    gradient_checkpointing=True,  # Saves memory by recomputing activations during backpropagation.
    learning_rate=5e-6,  # Base learning rate for the optimizer.
    fp16=not torch.cuda.is_bf16_supported(),  # FP16 precision if BF16 is not available.
    bf16=torch.cuda.is_bf16_supported(),  # Enables bfloat16 precision if available.
    save_steps=100,  # Saves checkpoint every 100 steps.
    torch_empty_cache_steps=10,  # Empties the cache at every 10 steps.
    logging_steps=100,  # Logs metrics every 100 steps.
    optim="adamw_8bit",  # Uses AdamW optimizer with 8-bit precision for optimizer states to save memory.
    weight_decay=0.01,  # Regularization to prevent overfitting by penalizing large weights.
    lr_scheduler_type="linear",  # Linearly decays learning rate after the warmup period.
    output_dir="gemma-2-2b-(hi)-cog-lab-chk-fnt",  # Directory where model checkpoints and logs will be saved.
    report_to="none",  # Disables logging to external tools like TensorBoard or WandB.
    save_total_limit=2, # Will save only 2 checkpoints at max, reducing the disk usage.
    run_name='pretrain_gemma2' # Defining a name for our runtime.
)

In [ ]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=base_model,
    padding="longest",
    return_tensors="pt"
)

trainer = SFTTrainer(
    model=base_model,
    tokenizer=tokenizer,
    args=train_args,
    peft_config=lora_config,
    train_dataset=train_dataset,
    data_collator=data_collator,
)

<ipython-input-20-5dcaa33d1df3>:12: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:359: UserWarning: You passed a dataset that is already processed (contains an `input_ids` field) together with a valid formatting function. Therefore `formatting_func` will be ignored. Either remove the `formatting_func` or pass a dataset that is not already processed.
  warnings.warn(

In [ ]:
trainer.train()

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

TrainOutput(global_step=1000, training_loss=1.1462819366455077, metrics={'train_runtime': 2889.3288, 'train_samples_per_second': 1.038, 'train_steps_per_second': 0.346, 'total_flos': 4.0378091175936e+16, 'train_loss': 1.1462819366455077, 'epoch': 1.0})

Training it for more epochs could've shown a better result

In [ ]:
trainer.save_model("gemma-2-2b-1000steps-0.03epoch-cog-lab-fnt")

In [ ]:
trainer.tokenizer.save_pretrained("gemma-2-2b-1000steps-0.03epoch-cog-lab-fnt")



As always we will merge the models

In [ ]:
merged_model = PeftModel.from_pretrained(AutoModelForCausalLM.from_pretrained("gemma-2-2b-(hi)-base-alpc-cb",device_map='auto'), 'gemma-2-2b-it(hi)-1000steps-0.03epoch-cog-lab-fnt').merge_and_unload()

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

---

It seems the model can now answer in Hinglish well enough, but has become pattern biased where in it thinks everything needs a thorough explanation along with its historical context

In [ ]:
question = "<start_of_turn>user Tell me about elephants, but tell me in English please. <end of turn>\n<start_of_turn>model "


inputs = tokenizer(question, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user Tell me about elephants, but tell me in English please. <end of turn>
<start_of_turn>model 1970s se ancient India me elephants ko pehle ko refer kiya gaya tha. Ye ek species hai jo typically southern Indian states me payi jati hai. As of 2010, sirf 8000 se adhik elephants hote hai, jinhone 1130 se adhik elephants hote huye.

Is species ki uniqueness ye hai ki vo 10 meters 7 feet lambi hoti hai, jo ho sakta hai 'long', jo ek tall animal hai. Elephant ki color usually gray hoti hai with two black legs.

Is bird ki ek choti aur long beak hoti hai jo ki chote, aam taur pe chote.

1985 se, jab ek special event pehle hi ye species dekha gaya, tab ye 12000 se adhik elephants ban gaye. <end_of_turn><eos>

---

It can also answer in English with same pattern biasness

In [ ]:
question = "<start_of_turn>user What's your name? <end_of_turn>\n<start_of_turn>"


inputs = tokenizer(question, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user What's your name? <end_of_turn>
<start_of_turn>model The name 'Kanwar' is a Sanskrit term which has been used historically in India due to the Sanskrit language and the 'war.' 'Kanwar' is often derived from Sanskrit words in both Hebrew and Sanskrit grammar schools. ' Kanwar' is another Sanskrit term that means 'water' or 'water' in Sanskrit language. These Sanskrit words have been used historically in some parts of South Asia during the Buddhist period. <end_of_turn><eos>

---

Since it was trained on multi-turn dataset we decided to check whether that type of prompt format can help it

In [ ]:
question = "<start_of_turn>user सुबेह सुबेह उठने वाली चिड़िया कौनसी है? <end of turn>\n<start_of_turn>model सुबह-सुबह बहुत सी चिड़िया उठती है, आपको किसके बारे में जानना है? <end_of_turn>\n<start_of_turn>user आपको कौनसी चिड़ियाँ के बारे में पता है? <end of turn>\n<start_of_turn>model "


inputs = tokenizer(question, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos><start_of_turn>user सुबेह सुबेह उठने वाली चिड़िया कौनसी है? <end of turn>
<start_of_turn>model सुबह-सुबह बहुत सी चिड़िया उठती है, आपको किसके बारे में जानना है? <end_of_turn>
<start_of_turn>user आपको कौनसी चिड़ियाँ के बारे में पता है? <end of turn>
<start_of_turn>model 9 और 10 की चिड़िया, सुबेह, अपने तेज, कठोर नाक के साथ मिलकर उठती है। वह बड़ी होती है और हमेशा कठोर परिस्थितियों का सामना करने के लिए तैयार होती है। सुबेह को अपनी आवाज़ में अपनी गाने की उम्मीद होती है। उसका आंगन में कोई पैच नहीं होता है और वे उड़ने के लिए बहुत तेज़ चलते हैं। वह अपने दिमाग में संचार के लिए एक झोल बनाए रखती है, और वे पंखों के साथ उड़ती हैं। <end_of_turn><eos>

---

We tried **Few Shot** examples to tell it how to have a conversation and it worked well enough but although the content was sub optimal

In [ ]:
question = "The following is a conversation between a user and model. The assistant responds in Hindi and provides accurate, concise answers.\nExample 1:\n<start_of_turn>user भारत की राजधानी क्या है? <end_of_turn>\n<start_of_turn>model भारत की राजधानी नई दिल्ली है। <end_of_turn>\nExample 2:\n<start_of_turn>user पिरामिड कहां पाए जाते हैं? <end_of_turn>\n<start_of_turn>model पिरामिड मुख्य रूप से मिस्र में पाए जाते हैं, लेकिन सूडान, मेसोअमेरिका और इटली जैसे अन्य स्थानों पर भी हैं। <end_of_turn>\nExample 3:<start_of_turn>user मुझे चाय और कॉफी के फायदे बताओ। <end_of_turn>\n<start_of_turn>model चाय एंटीऑक्सिडेंट्स से भरपूर होती है और तनाव कम करती है। वहीं, कॉफी सतर्कता और ऊर्जा को बढ़ाती है। <end_of_turn>\nNow continue the conversation:\n<start_of_turn>user भारत के पड़ोसी देशों के नाम क्या हैं? <end_of_turn>\n<start_of_turn>model "


inputs = tokenizer(question, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=246,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1,
                              use_cache=False)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos>The following is a conversation between a user and model. The assistant responds in Hindi and provides accurate, concise answers.
Example 1:
<start_of_turn>user भारत की राजधानी क्या है? <end_of_turn>
<start_of_turn>model भारत की राजधानी नई दिल्ली है। <end_of_turn>
Example 2:
<start_of_turn>user पिरामिड कहां पाए जाते हैं? <end_of_turn>
<start_of_turn>model पिरामिड मुख्य रूप से मिस्र में पाए जाते हैं, लेकिन सूडान, मेसोअमेरिका और इटली जैसे अन्य स्थानों पर भी हैं। <end_of_turn>
Example 3:<start_of_turn>user मुझे चाय और कॉफी के फायदे बताओ। <end_of_turn>
<start_of_turn>model चाय एंटीऑक्सिडेंट्स से भरपूर होती है और तनाव कम करती है। वहीं, कॉफी सतर्कता और ऊर्जा को बढ़ाती है। <end_of_turn>
Now continue the conversation:
<start_of_turn>user भारत के पड़ोसी देशों के नाम क्या हैं? <end_of_turn>
<start_of_turn>model 2006 की भारतीय जनगणना के अनुसार भारत के पड़ोसी देशों के नाम हैं:
1. श्रीलंका; 92.8 बिलियन डॉलर
2. जापान; 40.8 बिलियन डॉलर; और कंबोडिया;
3. इंडोनेशिया; 10.6 बिलियन डॉलर; नॉर्वे; 53.0 बिलियन डॉलर; मलेशिया; 2004; पाकिस्तान; 14.3 बिलियन डॉलर; संयुक्त राज्य अमेरिका; 2017; मध्य पूर्व; 2006; भारत। <end_of_turn><eos>

---

Conclusion: But as you can see, the model has now learnt to produce the end of turn and end of sentence tokens along with the knowledge of when to stop the generation.

This goes to show us it is actually fairly easy to teach a model the turn based approach and eos token generation with a small amount of training data requiring much lesser resources.

The model's performance in specific tasks can be improved with careful tweaking of the LoRA parameters which greatly impacts the training

---

## 4. Training on Combined Mixed Text Corpus

In this part of our research we did something different. So far we decided to train our model on different available datasets one by one. Which did give us some result specially when it came to teaching the model how to use genearal hindi tokens. With some achievements in the code switching and hinglish capabilities.

This time we decided to improve the model's knowledge base along with teaching it how to communicate in Hindi, Hinglish and possibly code switching by giving specific purpose datasets for the said tasks.

We gave a mixture of following
- **Wikipedia** datasets in hindi and hinglish
- **Alpaca** Hindi conversation dataset
- **Databricks Dolly** code mix , hinglish instruct dataset
- **Hindi Math Quest** dataset for hindi mathematics

Although our main goal was to increase the model's knowledge base in hindi, hinglish and code switching, we added maths for the possibility of increasing it's reasoning capability

We trained for a total of only **4 Hrs** on this dataset as unfortunately our resources had run out.

We'll see some interesting results ahead

We'll begin with downloading and carefully formating our datasets, putting them in right prompt. We only took a small subset of all the datasets carefully in order to induce certain behaviour from each as per resource and time constraints


### Datasets Preparation
For wikipedia, we used the **titles** as **user** query and **texts** as **model** output

In [ ]:
wiki_1 = load_dataset("Cohere/wikipedia-22-12-hi-embeddings", split = "train",)
wiki_1[0]['title'], wiki_1[0]['text']

('भारत का संविधान',
 'भारत का संविधान, भारत का सर्वोच्च विधान है जो संविधान सभा द्वारा 26 नवम्बर 1949 को पारित हुआ तथा 26 जनवरी 1950 से प्रभावी हुआ। यह दिन (26 नवम्बर) भारत के संविधान दिवस के रूप में घोषित किया गया है |जबकि 26 जनवरी का दिन भारत में गणतन्त्र दिवस के रूप में मनाया जाता है।')

In [ ]:
wiki_2 = load_dataset("wikimedia/wikipedia", "20231101.hi", split = "train",)
wiki_2[0]['title'], wiki_2[0]['text']

('हम होंगे कामयाब',
 'हम होंगे कामयाब ( का गिरिजा कुमार माथुर द्वारा किया गया हिंदी भावानुवाद) एक प्रतिरोध गीत है। यह गीत बीसवीं सदी में नागरिक अधिकार आंदोलन का प्रधान स्वर बना। इस गीत को आमतौर पर "I\'ll Overcome Some Day" ("आई विल ओवरकम सम डे") से काव्यावतरित माना जाता है, जो चार्ल्स अल्बर्ट टिंडले द्वारा गाया गया था और जिसे 1900 में पहली बार प्रकाशित किया गया था।\n\nसन्दर्भ\nHum Honge Kamyab Lyrics \nनागरिक अधिकार आंदोलन\nदेशभक्ति के गीत\nआधार')

In [ ]:
wiki_3 = load_dataset("sgzsh269/wikipedia-hindi-hinglish", split = "train",)
wiki_3[0]['hindi_title'], wiki_3[0]['hindi_text'], wiki_3[0]['hinglish_title'], wiki_3[0]['hinglish_text']

('यान्त्रिक अभियान्त्रिकी',
 'यान्त्रिक अभियांत्रिकी  (Mechanical engineering) तरह-तरह की मशीनों की बनावट, निर्माण, चालन आदि का सैद्धान्तिक और व्यावहारिक ज्ञान है। यान्त्रिक अभियांत्रिकी, अभियांत्रिकी की सबसे पुरानी और विस्तृत शाखाओं में से एक है। यान्त्रिक अभियांत्रिकी १८वीं शताब्दी में यूरोप में औद्योगिक क्रांति के दौरान एक क्षेत्र के रूप में उभरी है, लेकिन, इसका विकास दुनिया भर में कई हजार साल में हुआ है। १९वीं सदी में भौतिकी के क्षेत्र में विकास के एक परिणाम के रूप में यांत्रिक अभियांत्रिकी विज्ञान सामने आया।\n\nइसके आधआरभूत विषय हैं:\n\n स्थैतिकी और गति विज्ञान\n ठोस यांत्रिकी और पदार्थों की सामर्थ्य\n मापयंत्रण और मापन\n उष्मागतिकी,ऊष्मा का संचार,उर्जा का रूपान्तरण\n तरल यांत्रिकी और तरल गतिकी\n विनिर्माण अभियांत्रिकी\n द्रविकी और गैसयांत्रिकी\n अभियांत्रिकी अभिकल्प\n उत्पाद अभिकल्प \n पदार्थ विज्ञान\n अभियांत्रिकी आरेखण, अभिकलित्र सहायित अभिकल्प, अभिकलित्र सहायित विनिर्माण\n\nउपविभाग \nयान्त्रिक अभियान्त्रिकी कई यान्त्रिकी विज्ञान के विभागों के समूह के रूप में मानी जा सकती है।| इनमे से कुछ उपविभाग, जो अधिकतर पूर्व स्नातक पाठ्यक्रम में पढ़ाए जाते हैं, नीचे सूचीबद्ध किये गए हैं। इनमें से कुछ केवल यान्त्रिक अभियान्त्रिकी से ही सम्बन्धित हैं जबकि कुछ यांत्रिक अभियान्त्रिकी और अन्य विभागों के संयोजन हैं।\n\n यान्त्रिकी\n मेकैट्रॉनिक्स एवं रोबॉटिक्स\nमेकाट्रॉनिक्स  शब्द का निर्माण  जापान में हुआ था जिसमें मैकेनिकल का Mecha और इलेक्ट्रॉनिक्स का tronics लिया है।  Mechanical + Electronics = Mechatronics. \n\n संरचनात्मक विश्\u200dलेषण\n उष्मागतिकी एवं ताप विज्ञान\n अभिकल्प एवं प्रारूपण\n\nबाहरी कड़ियां\n mechanical engineering in hindi मैकेनिकल क्या है?\n\nइन्हें भी देखें\n विद्युत अभियांत्रिकी\n यांत्रिकी\n  इंजन\n  मेकाट्रॉनिक्स\n  टरबाइन\n गियर\n औद्योगिक क्रांति\n ऊर्जा\n यंत्र (मशीन)\n मशीनी औजार (मशीन टूल्स)\n इंजीनियरिंग ड्राइंग\n\nअभियान्त्रिकी\nयांत्रिक प्रौद्योगिकी',
 'Mechanical Engineering yaani Machine Design, Construction aur Operation ka Gyaan',
 'Mechanical engineering mein machine design, construction aur operation ke theoretical aur practical gyaan ko shamil kiya jaata hai. Mechanical engineering engineering ke sabse purane aur sabse bade branches mein se ek hai. Mechanical engineering Europe mein 18th century ke Industrial Revolution ke dauran ek field ke roop mein udbhav hua tha, lekin iska vikas duniya bhar mein kai hazaron saalon se ho raha hai. 19th century mein, physics ke kshetra mein vikason ke parinaamswaroop mechanical engineering science udbhav hua.\n\nIske basic subjects hain:\n\n Statics aur Dynamics\n Solid Mechanics aur Strength of Materials\n Measurement aur Instrumentation\n Thermodynamics, Heat Transfer, Energy Conversion\n Fluid Mechanics aur Fluid Dynamics\n Manufacturing Engineering\n Fluid Mechanics aur Gas Dynamics\n Engineering Design\n Product Design\n Materials Science\n Engineering Drawing, Computer-Aided Design, Computer-Aided Manufacturing\n\nSubdivisions\nMechanical engineering ko mechanical science departments ke ek group ke roop mein dekha ja sakta hai. Inmein se kuch subdivisions, jo ki undergraduate courses mein padhayi jati hain, neeche diye gaye hain. Inmein se kuch sirf mechanical engineering se sambandhit hain, jabki anya mechanical engineering aur anya departments ke sangam hain.\n\nMechanics\n Mechatronics aur Robotics\nMecharonics shabd Japan mein gyaan hua tha, jo ki Mechanical aur Electronics ka sangam hai. Mechanical + Electronics = Mechatronics.\n\nStructural Analysis\n Thermodynamics aur Heat Science\n Design aur Prototyping\n\nExternal links\nMechanical engineering in Hindi Mechanical kya hai?\n\nAlso see\n Electrical Engineering\n Mechanics\n Engine\n Mechatronics\n Turbine\n Gear\n Industrial Revolution\n Energy\n Machine (Machine)\n Machine Tools\n Engineering Drawing\n\nEngineering\nMechanical Technology')

In [ ]:
wiki_3

Dataset({
    features: ['id', 'url', 'hindi_title', 'hindi_text', 'english_title', 'english_text', 'hinglish_title', 'hinglish_text'],
    num_rows: 497
})

In [ ]:
def format_func_d1(example):
    prompts = []
    titles = example["title"]
    texts = example["text"]

    # Loop over each example in the batch
    for title, text in zip(titles, texts):
        prompt = f"<start_of_turn>user: {title} <end_of_turn>\n<start_of_turn>model: {text}<end_of_turn><eos>"
        prompts.append(prompt)

    # Return as a batch
    return {"prompt": prompts}

wiki_1_train = wiki_1.select_columns(["title","text"]).shuffle().take(5000).map(format_func_d1, batched=True).select_columns(["prompt"])
wiki_1_train[0], wiki_1_train[0]['prompt']

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

({'prompt': '<start_of_turn>user: कैथोलिक गिरजाघर <end_of_turn>\n<start_of_turn>model: कैरोलिनगियन राजाओं ने राजा और पोप के पद के बीच के रिश्ते को सशक्त बनाया. सन 754 में सबसे युवा पीपीन को पोप स्टीफन द्वितीय द्वारा एक भव्य समारोह (अभिषेक) में ताज पहनाया गया था। पीपीन ने लोम्बर्ड्स परास्त कर कैथोलिक राज्य में अधिक क्षेत्र जोड़ने का कार्य किया। जब शारलेमेन सिंहासन रूढ़ हुआ तो उसने तीव्र गति से अपने शक्ति का संचय किया; और 782 तक वह सबसे मजबूत ईसाई मिशन की भावना के साथ पश्चिमी राजाओं में सबसे ताकतवर माना गया। उसने रोम में सन 800 में कैथोलिक राज्याभिषेक प्राप्त किया, और उसने गिरजाघर के संरक्षक के रूप में हस्तक्षेप के अधिकार के साथ अपनी भूमिका की व्याख्या की. उनकी मृत्यु के बाद, तथापि, जिस अधिकार के साथ एक शासक पोप के अधिकार में हस्तक्षेप करने का अधिकार रखता था, के साथ असंगत तरीके से व्यवहार किया गया।<end_of_turn><eos>'},
 '<start_of_turn>user: कैथोलिक गिरजाघर <end_of_turn>\n<start_of_turn>model: कैरोलिनगियन राजाओं ने राजा और पोप के पद के बीच के रिश्ते को सशक्त बनाया. सन 754 में सबसे युवा पीपीन को पोप स्टीफन द्वितीय द्वारा एक भव्य समारोह (अभिषेक) में ताज पहनाया गया था। पीपीन ने लोम्बर्ड्स परास्त कर कैथोलिक राज्य में अधिक क्षेत्र जोड़ने का कार्य किया। जब शारलेमेन सिंहासन रूढ़ हुआ तो उसने तीव्र गति से अपने शक्ति का संचय किया; और 782 तक वह सबसे मजबूत ईसाई मिशन की भावना के साथ पश्चिमी राजाओं में सबसे ताकतवर माना गया। उसने रोम में सन 800 में कैथोलिक राज्याभिषेक प्राप्त किया, और उसने गिरजाघर के संरक्षक के रूप में हस्तक्षेप के अधिकार के साथ अपनी भूमिका की व्याख्या की. उनकी मृत्यु के बाद, तथापि, जिस अधिकार के साथ एक शासक पोप के अधिकार में हस्तक्षेप करने का अधिकार रखता था, के साथ असंगत तरीके से व्यवहार किया गया।<end_of_turn><eos>')

In [ ]:
def format_func_d2(example):
    prompts = []
    titles = example["title"]
    texts = example["text"]

    # Loop over each example in the batch
    for title, text in zip(titles, texts):
        prompt = f"<start_of_turn>user: {title} <end_of_turn>\n<start_of_turn>model: {text}<end_of_turn><eos>"
        prompts.append(prompt)

    # Return as a batch
    return {"prompt": prompts}

wiki_2_train = wiki_2.select_columns(["title","text"]).shuffle().take(5000).map(format_func_d2, batched=True).select_columns(["prompt"])
wiki_2_train[0]['prompt']

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

'<start_of_turn>user: प्रनीत भट्ट <end_of_turn>\n<start_of_turn>model: प्रनीत भट्ट एक भारतीय अभिनेता हैं। यह २०१३ में बनी महाभारत धारावाहिक में शकुनी का किरदार निभाया है। इसके बाद २०१४ में यह बिग बॉस के ८वें संस्करण में प्रतिभागी बने हैं।\n\nधारावाहिक \n (२००९) कितनी मस्त है ज़िंदगी (शेफान)\n (२००७) काजल (बंटी)\n (२००८) अर्सलान (शेफान)\n (२००७) दिल मिल गए (विशेष उपस्थिति)\n (२०१२-२०१३) सुवरीन गुग्गल (आदित्य)\n (२०१०-२०११) गीत\n (२०१३-२०१४) महाभारत (शकुनी)\n (२०१४) बिग बॉस (प्रतिभागी)\n (२०१५) किल्लर कराओके अटका तो लटका (प्रतिभागी)\n पोरस (२०१७) – डेरियस तृतीय\n अलादीन - नाम तो सुना होगा (२०१८) –अंगूठी छाप\nमेरे साई\nबाल शिव - देवर्षि नारद (2021)\n बृज के गोपाल (२०२२)  – कंटक\nजय हनुमान (२०२२)  – प्रेतराज\n\nसन्दर्भ\n\nबाहरी\xa0कड़ियाँ\n\n \n\nजीवित लोग\nअभिनेता\nबिग बॉस प्रतिभागी\nभारतीय टेलिविज़न अभिनेता<end_of_turn><eos>'

In [ ]:
def format_func_d3(example):
    prompts = []
    try: titles = example["hindi_title"]
    except: titles = example["hinglish_title"]
    try: texts = example["hindi_text"]
    except: texts = example["hinglish_text"]

    # Loop over each example in the batch
    for title, text in zip(titles, texts):
        prompt = f"<start_of_turn>user: {title} <end_of_turn>\n<start_of_turn>model: {text}<end_of_turn><eos>"
        prompts.append(prompt)

    # Return as a batch
    return {"prompt": prompts}

wiki_3_train_hi = wiki_3.select_columns(["hindi_title","hindi_text"]).map(format_func_d3, batched=True).select_columns(["prompt"])
wiki_3_train_he = wiki_3.select_columns(["hinglish_title","hinglish_text"]).map(format_func_d3, batched=True).select_columns(["prompt"])
wiki_3_train = concatenate_datasets([wiki_3_train_hi, wiki_3_train_he])
wiki_3_train_hi[0]['prompt'], wiki_3_train_he[0]['prompt']

('<start_of_turn>user: यान्त्रिक अभियान्त्रिकी <end_of_turn>\n<start_of_turn>model: यान्त्रिक अभियांत्रिकी  (Mechanical engineering) तरह-तरह की मशीनों की बनावट, निर्माण, चालन आदि का सैद्धान्तिक और व्यावहारिक ज्ञान है। यान्त्रिक अभियांत्रिकी, अभियांत्रिकी की सबसे पुरानी और विस्तृत शाखाओं में से एक है। यान्त्रिक अभियांत्रिकी १८वीं शताब्दी में यूरोप में औद्योगिक क्रांति के दौरान एक क्षेत्र के रूप में उभरी है, लेकिन, इसका विकास दुनिया भर में कई हजार साल में हुआ है। १९वीं सदी में भौतिकी के क्षेत्र में विकास के एक परिणाम के रूप में यांत्रिक अभियांत्रिकी विज्ञान सामने आया।\n\nइसके आधआरभूत विषय हैं:\n\n स्थैतिकी और गति विज्ञान\n ठोस यांत्रिकी और पदार्थों की सामर्थ्य\n मापयंत्रण और मापन\n उष्मागतिकी,ऊष्मा का संचार,उर्जा का रूपान्तरण\n तरल यांत्रिकी और तरल गतिकी\n विनिर्माण अभियांत्रिकी\n द्रविकी और गैसयांत्रिकी\n अभियांत्रिकी अभिकल्प\n उत्पाद अभिकल्प \n पदार्थ विज्ञान\n अभियांत्रिकी आरेखण, अभिकलित्र सहायित अभिकल्प, अभिकलित्र सहायित विनिर्माण\n\nउपविभाग \nयान्त्रिक अभियान्त्रिकी कई यान्त्रिकी विज्ञान के विभागों के समूह के रूप में मानी जा सकती है।| इनमे से कुछ उपविभाग, जो अधिकतर पूर्व स्नातक पाठ्यक्रम में पढ़ाए जाते हैं, नीचे सूचीबद्ध किये गए हैं। इनमें से कुछ केवल यान्त्रिक अभियान्त्रिकी से ही सम्बन्धित हैं जबकि कुछ यांत्रिक अभियान्त्रिकी और अन्य विभागों के संयोजन हैं।\n\n यान्त्रिकी\n मेकैट्रॉनिक्स एवं रोबॉटिक्स\nमेकाट्रॉनिक्स  शब्द का निर्माण  जापान में हुआ था जिसमें मैकेनिकल का Mecha और इलेक्ट्रॉनिक्स का tronics लिया है।  Mechanical + Electronics = Mechatronics. \n\n संरचनात्मक विश्\u200dलेषण\n उष्मागतिकी एवं ताप विज्ञान\n अभिकल्प एवं प्रारूपण\n\nबाहरी कड़ियां\n mechanical engineering in hindi मैकेनिकल क्या है?\n\nइन्हें भी देखें\n विद्युत अभियांत्रिकी\n यांत्रिकी\n  इंजन\n  मेकाट्रॉनिक्स\n  टरबाइन\n गियर\n औद्योगिक क्रांति\n ऊर्जा\n यंत्र (मशीन)\n मशीनी औजार (मशीन टूल्स)\n इंजीनियरिंग ड्राइंग\n\nअभियान्त्रिकी\nयांत्रिक प्रौद्योगिकी<end_of_turn><eos>',
 '<start_of_turn>user: Mechanical Engineering yaani Machine Design, Construction aur Operation ka Gyaan <end_of_turn>\n<start_of_turn>model: Mechanical engineering mein machine design, construction aur operation ke theoretical aur practical gyaan ko shamil kiya jaata hai. Mechanical engineering engineering ke sabse purane aur sabse bade branches mein se ek hai. Mechanical engineering Europe mein 18th century ke Industrial Revolution ke dauran ek field ke roop mein udbhav hua tha, lekin iska vikas duniya bhar mein kai hazaron saalon se ho raha hai. 19th century mein, physics ke kshetra mein vikason ke parinaamswaroop mechanical engineering science udbhav hua.\n\nIske basic subjects hain:\n\n Statics aur Dynamics\n Solid Mechanics aur Strength of Materials\n Measurement aur Instrumentation\n Thermodynamics, Heat Transfer, Energy Conversion\n Fluid Mechanics aur Fluid Dynamics\n Manufacturing Engineering\n Fluid Mechanics aur Gas Dynamics\n Engineering Design\n Product Design\n Materials Science\n Engineering Drawing, Computer-Aided Design, Computer-Aided Manufacturing\n\nSubdivisions\nMechanical engineering ko mechanical science departments ke ek group ke roop mein dekha ja sakta hai. Inmein se kuch subdivisions, jo ki undergraduate courses mein padhayi jati hain, neeche diye gaye hain. Inmein se kuch sirf mechanical engineering se sambandhit hain, jabki anya mechanical engineering aur anya departments ke sangam hain.\n\nMechanics\n Mechatronics aur Robotics\nMecharonics shabd Japan mein gyaan hua tha, jo ki Mechanical aur Electronics ka sangam hai. Mechanical + Electronics = Mechatronics.\n\nStructural Analysis\n Thermodynamics aur Heat Science\n Design aur Prototyping\n\nExternal links\nMechanical engineering in Hindi Mechanical kya hai?\n\nAlso see\n Electrical Engineering\n Mechanics\n Engine\n Mechatronics\n Turbine\n Gear\n Industrial Revolution\n Energy\n Machine (Machine)\n Machine Tools\n Engineering Drawing\n\nEngineering\nMechanical Technology<end_of_turn><eos>')

In [ ]:
wiki_dataset_train = concatenate_datasets([wiki_1_train, wiki_2_train, wiki_3_train])
wiki_dataset_train

Dataset({
    features: ['prompt'],
    num_rows: 10994
})

---

> NOTE: This alpaca dataset is different from the previous one.

We have given both the instruction and input fields as user query.

In [ ]:
alpaca_dataset_train = load_dataset("guneetsk99/Hindi_Alpaca_For_Gemma_67K",
                              split = "train")
alpaca_dataset_train, alpaca_dataset_train[3]

(Dataset({
     features: ['instruction', 'output', 'input'],
     num_rows: 67017
 }),
 {'instruction': '11 सितंबर, 2001 को क्या हुआ था?11 सितंबर के हमले, जिन्हें आमतौर पर 9/11 के रूप में जाना जाता है, [डी] 11 सितंबर, 2001 को संयुक्त राज्य अमेरिका के खिलाफ उग्रवादी इस्लामवादी चरमपंथी नेटवर्क अल-कायदा द्वारा किए गए चार समन्वित आत्मघाती आतंकवादी हमले थे। उस सुबह, उन्नीस आतंकवादियों ने चार वाणिज्यिक का अपहरण कर लिया एयरलाइनर पूर्वी तट से कैलिफ़ोर्निया जाने वाले हैं। अपहर्ताओं ने पहले दो विमानों को न्यूयॉर्क शहर में वर्ल्ड ट्रेड सेंटर के ट्विन टावर्स से टकराया और तीसरे को वाशिंगटन डी.सी. के पास अर्लिंगटन काउंटी, वर्जीनिया में पेंटागन (संयुक्त राज्य सेना का मुख्यालय) में दुर्घटनाग्रस्त कर दिया। चौथा विमान इसी तरह था डी.सी. में एक संघीय सरकारी इमारत से टकराने का इरादा था, लेकिन एक यात्री विद्रोह के बाद एक मैदान में दुर्घटनाग्रस्त हो गया। इन हमलों में लगभग 3,000 लोग मारे गए और आतंक के खिलाफ वैश्विक युद्ध भड़क गया।',
  'output': 'ये हमले दुनिया के इतिहास में सबसे भयानक आतंकवादी हमलों में से एक माने जाते हैं और इससे पूरी दुनिया में सुरक्षा की नई परिभाषा बन गई। इस हमले के बाद से अमेरिका ने अपनी सुरक्षा के लिए नए नियम बनाए और अपनी सुरक्षा में विश्व के अन्य देशों से भी मदद ली। इस हमले के बाद से अमेरिका ने अल-कायदा और उसके अन्य संबंधित संगठनों के खिलाफ वैश्विक युद्ध शुरू किया जो मुख्य रूप से अफगानिस्तान में हुआ।',
  'input': None})

In [ ]:
alpaca_dataset_train

Dataset({
    features: ['instruction', 'output', 'input'],
    num_rows: 67017
})

In [ ]:
gen_prompt="""<start_of_turn>user: {} {}<end_of_turn>\n<start_of_turn>model: {}<end_of_turn>"""
print(alpaca_prompt)

<start_of_turn>user: {} {}<end_of_turn>
<start_of_turn>model: {}<end_of_turn>

In [ ]:
def formatting_func(examples):
    prompts = []
    instruction = examples["instruction"]
    input = examples["input"]
    output = examples['output']
    # Loop over each example in the batch
    for instruction, input, output in zip(instruction, input, output):
        input = input if input else ''
        prompt = gen_prompt.format(instruction, input, output) + '<eos>'
        prompts.append(prompt)
    return { "prompt" : prompts, }

In [ ]:
alpaca_train = alpaca_dataset_train.shuffle().take(2000).map(formatting_func, batched = True,).select_columns(["prompt"])

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [ ]:
alpaca_train,alpaca_train[0]

(Dataset({
     features: ['prompt'],
     num_rows: 2000
 }),
 {'prompt': '<start_of_turn>user: पहचानें कि कौन सा वाद्य यंत्र स्ट्रिंग या पर्क्यूशन है: किरिकोकेटा, इचिगेंकिन <end_of_turn>\n<start_of_turn>model: इन दोनों वाद्य यंत्रों में से किरिकोकेटा स्ट्रिंग वाद्य है और इचिगेंकिन पर्क्यूशन वाद्य है।<end_of_turn><eos>'})

In [ ]:
print(alpaca_train["prompt"][0])

<start_of_turn>user: टाइप 1 मधुमेह क्या है?टाइप 1 डायबिटीज (T1D), जिसे पहले किशोर मधुमेह के रूप में जाना जाता था, एक ऑटोइम्यून बीमारी है जो तब उत्पन्न होती है जब इंसुलिन (बीटा सेल) बनाने वाली कोशिकाएं प्रतिरक्षा प्रणाली द्वारा नष्ट हो जाती हैं। इंसुलिन एक हार्मोन है जो कोशिकाओं को ऊर्जा के लिए रक्त शर्करा का उपयोग करने के लिए आवश्यक है और यह रक्त प्रवाह में ग्लूकोज के स्तर को नियंत्रित करने में मदद करता है। उपचार से पहले इसका परिणाम शरीर में उच्च रक्त शर्करा के स्तर में होता है। इस उच्च रक्त शर्करा के सामान्य लक्षण बार-बार पेशाब आना, प्यास का बढ़ना, भूख में वृद्धि, वजन घटना और अन्य गंभीर जटिलताएं हैं। अतिरिक्त लक्षणों में धुंधली दृष्टि, थकान, और धीमी गति से घाव भरना शामिल हो सकते हैं। लक्षण आमतौर पर थोड़े समय में विकसित होते हैं, अक्सर कुछ हफ़्ते में। <end_of_turn>
<start_of_turn>model: टाइप 1 मधुमेह आमतौर पर बचपन से होने वाली होती है और इसे जीवनभर नियंत्रित रखना पड़ता है। दवाओं और इंसुलिन के साथ उच्च रक्त शर्करा के स्तर को नियंत्रित करने में मदद करता है। इंसुलिन को इंजेक्शन या पंप के माध्यम से दिया जाता है। इसके अलावा, अपने खाने पर नियंत्रण रखने, जीवनशैली में सुधार करने और अन्य उपायों से लोग अपने ब्लड शुगर को संतुलित रख सकते हैं। यदि इसे ठीक से नियंत्रित नहीं किया जाता है, तो यह गंभीर समस्याओं जैसे अंधापन, अंगुलियों में नुकसान, हृदय रोग, चक्कर आदि का कारण बन सकता है।<end_of_turn><eos>

In [ ]:
databrick_dolly = load_dataset("aaditya/databricks-dolly-15k-Hinglish-Codemix", split = "train")

README.md:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/15.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/15011 [00:00<?, ? examples/s]

In [ ]:
databrick_dolly[0]

{'en_instruction': 'What is the origin of orange wine?',
 'en_input': None,
 'en_output': 'Orange wine was first introduced in Georgia and it dates thousands of years back. It is a variant of white wine where the skin grapes are not removed after crushing the grapes. Instead, the skins are left to ferment with the grape juice, similarly to red wine. The style of skin-contact white wine was adopted by Italian and Slovenian winemakers, after visiting Georgia. It then spread to other European countries. \n\nSkin-fermented white wines were common up until the 1960s, when fresh white wines started to dominate the market.\n\nThe term orange wine was coined only in 2004 by a British wine importer.\n\nIn Georgia skin-contact white wine is historically known as amber wine.',
 'id': 'e561d49c-1a6d-4455-ae61-2657c79b2ce2',
 'en_category': 'open_qa',
 'codemix_instruction': 'Orange wine ka origin kya hai?',
 'codemix_input': None,
 'codemix_output': 'Orange wine sabse pehle Georgia mein banaya gaya tha aur yeh hajaro saal purana hai. Yeh ek prakar ka white wine hai jismein grapes ko crush karne ke baad unke skin ko nahi hataaya jaata. Iske jagah, skin ko grape juice ke saath ferment hone ke liye chod diya jaata hai, bilkul red wine ki tarah. Georgia jaane ke baad, Italian aur Slovenian winemakers ne skin-contact white wine banana shuru kar diya. Phir yeh dusre European countries mein bhi famous ho gaya.\n\n1960 tak skin-fermented white wines bahut common the, jabki ab fresh white wines market mein jyada chalti hain.\n\nOrange wine term ko 2004 mein ek British wine importer ne banaya tha.\n\nGeorgia mein skin-contact white wine ko traditionally amber wine ke naam se jaana jaata hai.',
 'codemix_category': 'Origin of Orange Wine'}

In [ ]:
def formatting_func(examples):
    prompts = []
    instruction = examples["codemix_instruction"]
    input = examples["codemix_input"]
    output = examples['codemix_output']
    # Loop over each example in the batch
    for instruction, input, output in zip(instruction, input, output):
        instruction = instruction if instruction else ''
        if instruction:
          input = f'{input}' if input else ''
        else:
          input = input if input else ''
        prompt = gen_prompt.format(instruction, input, output) + '<eos>'
        prompts.append(prompt)
    return { "prompt" : prompts, }

In [ ]:
databrick_train = databrick_dolly.shuffle().take(2000).map(formatting_func, batched = True,).select_columns(["prompt"])

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [ ]:
databrick_train, databrick_train[0]

(Dataset({
     features: ['prompt'],
     num_rows: 2000
 }),
 {'prompt': '<start_of_turn>user: Memorial Recreation Park kya hai aur yeh kahan hai <end_of_turn>\n<start_of_turn>model: Memorial Recreation Park, Port Huron, Michigan mein ek athletic aur recreation complex hai. Complex ki main facility ek 5,500-seat stadium hai, jahan Port Huron Northern High School aur Port Huron High School football teams khelte hain. Iske alawa, 27-acre (11 ha) complex mein tennis courts, chaar baseball fields, chaar softball fields, kai football fields, aur ek quarter-mile track hai.\n\nYeh complex 1945 mein bana tha aur yeh Port Huron ke un mardon aur auraton ko dedicate hai jinhe World War II mein seva ki thi.<end_of_turn><eos>'})

---
> NOTE: For certain gated datasets you need to login to HuggingFace or activate your hf token which you can get from your HuggingFace account

In [ ]:
from huggingface_hub import login

login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import os

os.environ["HF_HOME"] = "your_hf_token"

In [ ]:
math_quest = load_dataset("dnyanesh/HindiMathQuest", split = "train")
math_quest[0]

MATH-HINDI-v1.json:   0%|          | 0.00/464M [00:00<?, ?B/s]

(…)_Data/Test_Data/Hindi_Math_01_Digit.json:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

(…)_Data/Test_Data/Hindi_Math_02_Digit.json:   0%|          | 0.00/21.8k [00:00<?, ?B/s]

(…)_Data/Test_Data/Hindi_Math_03_Digit.json:   0%|          | 0.00/26.7k [00:00<?, ?B/s]

(…)_Data/Test_Data/Hindi_Math_04_Digit.json:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

(…)_Data/Test_Data/Hindi_Math_05_Digit.json:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/250117 [00:00<?, ? examples/s]

{'instruction': 'सही उत्तर खोजें:',
 'input': 'जंगकुक 5वें स्थान पर है। जंगकुक से पहले फिनिश लाइन पार करने वाले लोगों की संख्या ज्ञात कीजिए।',
 'output': 'यदि जुंगकुक 5वें स्थान पर है, तो 4 लोगों ने उससे अधिक तेजी से फिनिश लाइन पार की।'}

In [ ]:
def formatting_func(examples):
    prompts = []
    instruction = examples["instruction"]
    input = examples["input"]
    output = examples['output']
    # Loop over each example in the batch
    for instruction, input, output in zip(instruction, input, output):
        input = input if input else ''
        prompt = gen_prompt.format(instruction, input, output) + '<eos>'
        prompts.append(prompt)
    return { "prompt" : prompts, }

In [ ]:
mathquest_train = math_quest.shuffle().take(2000).map(formatting_func, batched = True,).select_columns(["prompt"])

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [ ]:
mathquest_train, mathquest_train[0]

(Dataset({
     features: ['prompt'],
     num_rows: 2000
 }),
 {'prompt': "<start_of_turn>user: Let's tackle this step-by-step: Question: In a certain game, a large bag is filled with blue, green, purple, and red chips worth 1 (एक), 5 (पांच), x, and 11 (ग्यारह) points each, respectively. The purple chips are worth more than the green chips, but less than the red chips. A certain number of chips are then selected from the bag. The product of the point values of the selected chips is 140800 (एक लाख चालीस हज़ार आठ सौ). How many points is a purple chip worth?<end_of_turn>\n<start_of_turn>model: Let's denote the value of a purple chip as \\( x \\). We know that \\( 5 (पांच) < x < 11 (ग्यारह) \\) because purple chips are worth more than green chips but less than red chips.\n\nThe product of the point values of the selected chips is 140800 (एक लाख चालीस हज़ार आठ सौ). We need to factorize 140800 (एक लाख चालीस हज़ार आठ सौ) into its prime factors to see which combination of chip values could give us this product.\n\n\\( 140800 (एक लाख चालीस हज़ार आठ सौ) = 2 (दो)^6 (छह) \\times 5 (पांच)^2 (दो) \\times 11 (ग्यारह) \\)\n\nNow, we know that the red chips are worth 11 (ग्यारह) points, so we can take the factor of 11 (ग्यारह) out of the equation, as there must be at least one red chip selected.\n\n\\( 140800 (एक लाख चालीस हज़ार आठ सौ) / 11 (ग्यारह) = 12800 (बारह हज़ार आठ सौ) \\)\n\n\\( 12800 (बारह हज़ार आठ सौ) = 2 (दो)^6 (छह) \\times 5 (पांच)^2 (दो) \\)\n\nNow we have \\( 2 (दो)^6 (छह) \\) and \\( 5 (पांच)^2 (दो) \\) left, which correspond to the blue chips (1 (एक) point each) and green chips (5 (पांच) points each). Since \\( 2 (दो)^6 (छह) = 64 (चौंसठ) \\) and \\( 5 (पांच)^2 (दो) = 25 (पच्चीस) \\), we can see that the product of 64 (चौंसठ) and 25 (पच्चीस) is indeed 1600 (एक हज़ार छह सौ), which is the remaining product after removing the red chip's value.\n\nSince there are no other factors left, and we know that the purple chip's value must be a whole number greater than 5 (पांच) and less than 11 (ग्यारह), the only possible value for \\( x \\) that fits these criteria is 7 (सात), because it is the only whole number between 5 (पांच) and 11 (ग्यारह) that is not a factor in the product 140800 (एक लाख चालीस हज़ार आठ सौ).\n\nTherefore, a purple chip is worth 7 (सात) points.<end_of_turn><eos>"})

---

Finally we will concatenate the datasets and tokenize them

In [ ]:
train_dataset = concatenate_datasets([wiki_dataset_train, alpaca_train, databrick_train, mathquest_train]).shuffle()
train_dataset, train_dataset[0]

(Dataset({
     features: ['prompt'],
     num_rows: 16994
 }),
 {'prompt': '<start_of_turn>user: टूटे सर्फ़बोर्ड के साथ मैं कौन सी पाँच चीज़ें कर सकता हूँ? <end_of_turn>\n<start_of_turn>model: 1. सर्फिंग नलगाना: टूटे सर्फ़बोर्ड के साथ, आप सर्फिंग नलगाना चलाने से मुश्किल हो सकता है। यदि आप इसे चलाने के बारे में सोचते हैं तो कृपया सेफ़्टी स्टेप्स का पालन करें।\n\n2. सर्फ़बोर्ड रिपेयर करना: टूटे सर्फ़बोर्ड को ठीक करने के लिए आप तार के साथ उसे संभाल सकते हैं। आप इसके लिए तार और अन्य स्थानों पर चेप लगाकर निर्धारित स्थान से बोर्ड को संभाल लीजिये।\n\n3. सीढ़ियाँ उतरना: सीढ़ियों से उतरते समय टूटे सर्फ़बोर्ड को अचानक ठोकर लग सकती है। इसलिए, नीचे उतरते समय आपके हाथ में बोर्ड को सम्हालित रखना आवश्यक हो सकता है।\n\n4. अभ्यास करना: टूटे सर्फ़बोर्ड के साथ आपको सर्फिंग करने में कुछ परेशानियों का सामना करना पड़ सकता है। इसलिए, आपको नियमित अभ्यास करना चाहिए ताकि आप स्वस्थ रह सकें।\n\n5. संरक्षण: अपने सर्फ़बोर्ड की देखभाल करें जो आपके मूल्यवान सर्फ़बोर्ड को टूटने से बचा सकता है। इसलिए, आपको अपने सर्फ़बोर्ड को संरक्षित रखना चाहिए और उसे कुछ हफ्तों में एक बार सफाई करना चाहिए।<end_of_turn><eos>'})

In [ ]:
def tokenize_function(examples):
    tokenized = tokenizer(
        examples["prompt"],
        padding="longest",
        truncation=True,
        max_length=1024,
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

print("Tokenizing dataset...")
train_dataset = train_dataset.map(tokenize_function, batched=True)
print("Dataset tokenized:", train_dataset[0])

Tokenizing dataset...

Map:   0%|          | 0/16994 [00:00<?, ? examples/s]

Dataset tokenized: {'prompt': '<start_of_turn>user: टूटे सर्फ़बोर्ड के साथ मैं कौन सी पाँच चीज़ें कर सकता हूँ? <end_of_turn>\n<start_of_turn>model: 1. सर्फिंग नलगाना: टूटे सर्फ़बोर्ड के साथ, आप सर्फिंग नलगाना चलाने से मुश्किल हो सकता है। यदि आप इसे चलाने के बारे में सोचते हैं तो कृपया सेफ़्टी स्टेप्स का पालन करें।\n\n2. सर्फ़बोर्ड रिपेयर करना: टूटे सर्फ़बोर्ड को ठीक करने के लिए आप तार के साथ उसे संभाल सकते हैं। आप इसके लिए तार और अन्य स्थानों पर चेप लगाकर निर्धारित स्थान से बोर्ड को संभाल लीजिये।\n\n3. सीढ़ियाँ उतरना: सीढ़ियों से उतरते समय टूटे सर्फ़बोर्ड को अचानक ठोकर लग सकती है। इसलिए, नीचे उतरते समय आपके हाथ में बोर्ड को सम्हालित रखना आवश्यक हो सकता है।\n\n4. अभ्यास करना: टूटे सर्फ़बोर्ड के साथ आपको सर्फिंग करने में कुछ परेशानियों का सामना करना पड़ सकता है। इसलिए, आपको नियमित अभ्यास करना चाहिए ताकि आप स्वस्थ रह सकें।\n\n5. संरक्षण: अपने सर्फ़बोर्ड की देखभाल करें जो आपके मूल्यवान सर्फ़बोर्ड को टूटने से बचा सकता है। इसलिए, आपको अपने सर्फ़बोर्ड को संरक्षित रखना चाहिए और उसे कुछ हफ्तों में एक बार सफाई करना चाहिए।<end_of_turn><eos>', 'input_ids': [2, 106, 1645, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 6777, 36631, 75569, 115088, 65892, 62532, 189724, 112889, 74543, 6300, 10494, 76228, 103060, 237835, 235336, 235248, 107, 108, 106, 2516, 235292, 235248, 235274, 235265, 3640, 197334, 42828, 7578, 235620, 32836, 10993, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 6777, 36631, 235269, 27074, 3640, 197334, 42828, 7578, 235620, 32836, 10993, 208850, 9396, 11670, 39728, 44410, 235456, 24892, 16405, 76228, 6032, 235940, 69534, 27074, 115338, 208850, 9396, 6777, 99172, 9192, 94302, 236062, 18249, 16445, 34638, 232499, 11670, 135447, 133294, 54537, 235483, 235619, 62607, 11201, 228604, 235530, 38607, 235940, 109, 235284, 235265, 233903, 135447, 235825, 235631, 105520, 9184, 64363, 235483, 110337, 79532, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 11276, 95437, 231746, 31986, 6777, 19126, 27074, 10321, 6414, 6777, 36631, 128944, 23480, 236124, 14521, 64890, 16445, 235940, 27074, 82248, 19126, 10321, 6414, 12500, 100150, 154459, 10370, 14480, 212186, 235619, 99877, 30848, 64440, 71293, 13568, 154459, 11670, 143835, 105520, 11276, 23480, 236124, 14521, 176383, 235800, 114574, 235940, 109, 235304, 235265, 65892, 48240, 190221, 11738, 103217, 10993, 235292, 65892, 48240, 49848, 11670, 11738, 103217, 18249, 70086, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 11276, 8104, 236062, 12260, 235456, 95437, 235631, 30848, 85558, 161521, 6032, 235940, 168226, 235269, 201590, 11738, 103217, 18249, 70086, 116257, 196988, 9192, 143835, 105520, 11276, 124267, 235571, 14521, 13568, 75454, 10993, 109194, 16405, 76228, 6032, 235940, 109, 235310, 235265, 84735, 14767, 235533, 79532, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 6777, 36631, 83584, 3640, 197334, 42828, 31986, 9192, 65565, 14480, 33664, 12260, 49848, 11201, 106411, 10993, 79532, 4587, 24082, 76228, 6032, 235940, 168226, 235269, 83584, 202578, 13568, 84735, 14767, 235533, 79532, 108466, 85429, 49122, 27074, 56545, 75865, 79704, 35433, 6300, 235940, 109, 235308, 235265, 226173, 135192, 235292, 47758, 233903, 135447, 235825, 235631, 105520, 10033, 54872, 236124, 14521, 38607, 38750, 116257, 111725, 10289, 158086, 233903, 135447, 235825, 235631, 105520, 11276, 28845, 154000, 9396, 11670, 7320, 71431, 76228, 6032, 235940, 168226, 235269, 83584, 47758, 233903, 135447, 235825, 235631, 105520, 11276, 226173, 222793, 75454, 10993, 108466, 12500, 128944, 65565, 3912, 182056, 10370, 9192, 15848, 99744, 3640, 236559, 52254, 79532, 108466, 235940, 107, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [2, 106, 1645, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 6777, 36631, 75569, 115088, 65892, 62532, 189724, 112889, 74543, 6300, 10494, 76228, 103060, 237835, 235336, 235248, 107, 108, 106, 2516, 235292, 235248, 235274, 235265, 3640, 197334, 42828, 7578, 235620, 32836, 10993, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 6777, 36631, 235269, 27074, 3640, 197334, 42828, 7578, 235620, 32836, 10993, 208850, 9396, 11670, 39728, 44410, 235456, 24892, 16405, 76228, 6032, 235940, 69534, 27074, 115338, 208850, 9396, 6777, 99172, 9192, 94302, 236062, 18249, 16445, 34638, 232499, 11670, 135447, 133294, 54537, 235483, 235619, 62607, 11201, 228604, 235530, 38607, 235940, 109, 235284, 235265, 233903, 135447, 235825, 235631, 105520, 9184, 64363, 235483, 110337, 79532, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 11276, 95437, 231746, 31986, 6777, 19126, 27074, 10321, 6414, 6777, 36631, 128944, 23480, 236124, 14521, 64890, 16445, 235940, 27074, 82248, 19126, 10321, 6414, 12500, 100150, 154459, 10370, 14480, 212186, 235619, 99877, 30848, 64440, 71293, 13568, 154459, 11670, 143835, 105520, 11276, 23480, 236124, 14521, 176383, 235800, 114574, 235940, 109, 235304, 235265, 65892, 48240, 190221, 11738, 103217, 10993, 235292, 65892, 48240, 49848, 11670, 11738, 103217, 18249, 70086, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 11276, 8104, 236062, 12260, 235456, 95437, 235631, 30848, 85558, 161521, 6032, 235940, 168226, 235269, 201590, 11738, 103217, 18249, 70086, 116257, 196988, 9192, 143835, 105520, 11276, 124267, 235571, 14521, 13568, 75454, 10993, 109194, 16405, 76228, 6032, 235940, 109, 235310, 235265, 84735, 14767, 235533, 79532, 235292, 28845, 154000, 235483, 233903, 135447, 235825, 235631, 105520, 6777, 36631, 83584, 3640, 197334, 42828, 31986, 9192, 65565, 14480, 33664, 12260, 49848, 11201, 106411, 10993, 79532, 4587, 24082, 76228, 6032, 235940, 168226, 235269, 83584, 202578, 13568, 84735, 14767, 235533, 79532, 108466, 85429, 49122, 27074, 56545, 75865, 79704, 35433, 6300, 235940, 109, 235308, 235265, 226173, 135192, 235292, 47758, 233903, 135447, 235825, 235631, 105520, 10033, 54872, 236124, 14521, 38607, 38750, 116257, 111725, 10289, 158086, 233903, 135447, 235825, 235631, 105520, 11276, 28845, 154000, 9396, 11670, 7320, 71431, 76228, 6032, 235940, 168226, 235269, 83584, 47758, 233903, 135447, 235825, 235631, 105520, 11276, 226173, 222793, 75454, 10993, 108466, 12500, 128944, 65565, 3912, 182056, 10370, 9192, 15848, 99744, 3640, 236559, 52254, 79532, 108466, 235940, 107, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [ ]:
train_dataset

Dataset({
    features: ['prompt', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 16994
})

### Training

---
NOTE: As always the lora parameters are very crucial.

- Analyze our current parameters as compared to our previous configs.
-You can increase the **r** and alpha to prompt even more layers with stronger learning.
- We have set the gradient accumulation to 2 this time.

In [ ]:
lora_config = LoraConfig(
    r=64,
    lora_alpha=128,
    target_modules=["q_proj", "o_proj", "k_proj", "v_proj", "gate_proj", "up_proj", "down_proj"
                    ],
    modules_to_save=["embed_tokens", "lm_head"],
    task_type="CAUSAL_LM",
    use_rslora=True
)

train_args = TrainingArguments(
    per_device_train_batch_size=2,  # Each GPU processes 2 examples per step.
    gradient_accumulation_steps=2,  # Gradients are accumulated over 2 steps before updating weights.
    # warmup_steps=30,  # Learning rate warms up (gradually increases) for the first 30 steps.
    #max_steps=10,  # Total number of optimization steps for training.
    warmup_ratio=0.1, # Learning rate warms up (gradually increases) for the first 10 percent of epoch.
    num_train_epochs=1,  # Total number of training steps for training.
    gradient_checkpointing=True,  # Saves memory by recomputing activations during backpropagation.
    learning_rate=5e-5,  # Base learning rate for the optimizer.
    fp16=not torch.cuda.is_bf16_supported(),  # FP16 precision if BF16 is not available.
    bf16=torch.cuda.is_bf16_supported(),  # Enables bfloat16 precision if available.
    save_steps=100,  # Saves checkpoint every 100 steps.
    torch_empty_cache_steps = 10,  # Empties the cache at every 10 steps.
    logging_steps=100,  # Logs metrics every 10 steps.
    optim="adamw_8bit",  # Uses AdamW optimizer with 8-bit precision for optimizer states to save memory.
    weight_decay=0.01,  # Regularization to prevent overfitting by penalizing large weights.
    lr_scheduler_type="linear",  # Linearly decays learning rate after the warmup period.
    output_dir="gemma-2-2b-(hi)-wiki+alpaca+databrick+mathquest_chk",  # Directory where model checkpoints and logs will be saved.
    report_to="none",  # Disables logging to external tools like TensorBoard or WandB.
    save_total_limit=2, # Will save only 2 checkpoints at max, reducing the disk usage.
    run_name='pretrain_gemma2' # Defining a name for our runtime.
)

In [ ]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=base_model,
    padding="longest",
    return_tensors="pt"
)

trainer = SFTTrainer(
    model=base_model,
    tokenizer=tokenizer,
    args=train_args,
    peft_config=lora_config,
    train_dataset=train_dataset,
    data_collator=data_collator,
)

<ipython-input-64-5dcaa33d1df3>:12: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(

In [ ]:
trainer.train()

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

TrainOutput(global_step=4248, training_loss=0.5385702698019714, metrics={'train_runtime': 16838.2612, 'train_samples_per_second': 1.009, 'train_steps_per_second': 0.252, 'total_flos': 2.8160636796429926e+17, 'train_loss': 0.5385702698019714, 'epoch': 0.999882311404025})

### Saving the model

The saving and merging steps are the same as always

In [ ]:
trainer.save_model('gemma-2-2b-{hi)-16994batch-1epoch-wiki+alpaca+databrick+mathquest')
trainer.tokenizer.save_pretrained('gemma-2-2b-{hi)-16994batch-1epoch-wiki+alpaca+databrick+mathquest')

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

('gemma-2-2b(hi)-wiki+alpaca+databrick+mathquest/tokenizer_config.json',
 'gemma-2-2b(hi)-wiki+alpaca+databrick+mathquest/special_tokens_map.json',
 'gemma-2-2b(hi)-wiki+alpaca+databrick+mathquest/tokenizer.model',
 'gemma-2-2b(hi)-wiki+alpaca+databrick+mathquest/added_tokens.json',
 'gemma-2-2b(hi)-wiki+alpaca+databrick+mathquest/tokenizer.json')

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('gemma-2-2b-{hi)-16994batch-1epoch-wiki+alpaca+databrick+mathquest')
merged_model = PeftModel.from_pretrained(AutoModelForCausalLM.from_pretrained('gemma-2-2b', device_map='auto'), 'gemma-2-2b-{hi)-16994batch-1epoch-wiki+alpaca+databrick+mathquest').merge_and_unload()

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
merged_model.save_pretrained("gemma-2-2b-tmp")

In [ ]:
torch.save(merged_model.state_dict(), "merged_model_state_dict.pth")

In [ ]:
model = AutoModelForCausalLM.from_pretrained("gemma-2-2b-tmp",device_map='cpu')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
model.load_state_dict(torch.load("merged_model_state_dict.pth", weights_only=True))

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gemma-2-2b-(hi)-16994batch-1epoch-wiki+alpaca+databrick+mathquest")

In [ ]:
model.save_pretrained("gemma-2-2b-(hi)-base+wiki+alpaca+databrick+mathquest")

In [ ]:
tokenizer.save_pretrained("gemma-2-2b-(hi)-base+wiki+alpaca+databrick+mathquest")

### Inference

In [ ]:
system_prompt = "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query. \nआप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं। \naap jemmaa2 hain, ek madadagaar, sanvaadee eaee sahaayak. aap hindee, bolachaal kee hinglish aur angrejee mein visheshagy hain. aap upayogakartaon ko upayogakarta kee kveree kee bhaasha mein spasht aur sankshipt tareeke se javaab dete hain."

# Prepare the input
user_input = "<start_of_turn>user: Why is diwali celebrated<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

user: Why is diwali celebrated
model: 1. Diwali is a great festival which marks the end of the year and the beginning of a new year.
2. Diwali is also celebrated as a festival of light and it has been traditionally celebrated in a manner of offering lamps and alighting of the firecrackers on the evening of Diwali.
3. Diwali also marks the celebration of the victory of good over evil and knowledge over ignorance.
4. Diwali is an important festival of Lord Krishna and Vishnu who are two of the major Hindu Gods.
5. Diwali also marks the beginning of Hindu New Year, when people celebrate by offering puja or homa to God to seek his blessings for the coming year.

In [ ]:
system_prompt = "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: दिवाली का त्यौहार क्यों मनाया जाता है, संचेप में बतायें?<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + '\n' + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query
user: दिवाली का त्यौहार क्यों मनाया जाता है, संचेप में बतायें?
model: 1. दिवाली की परम्परा
दिवाली एक धार्मिक उत्सव है जो भारतीय समाज में बहुत महत्व रखता है। यह समाज के विभिन्न धर्मों के साथ संयुक्त होती है, जैसे कि हिंदुओं, शिवमंदिरों के साथ साहिबों और बुद्धों की, आदि। इस दिवाली का महत्व भारत के साथ भाईचारा और नागरिक संघर्ष का भी है।

2. आंतिमा के प्रति एक और विशेष स्थान
दिवाली का दूसरा विशिष्टता साहित्य में है कि यह आंतरजाल की मांग से संबंधित है, साथ ही यह आंतरजाल परियोजनाओं के एक महत्वपूर्ण हिस्से के रूप में भी कार्य करता है।

3. उत्सव की तीखी सवारी
दिवाली के दिन, लोग आंतरजाल, सामुदायिक समाज और राष्ट्रीय और आर्थिक विकास के लिए तेज सवारी करते हैं।

4. विवाह और मुलाक़ात की परम्परा
दिवाली में लोग विवाह और मुलाक़त की तारीख के दौरान मनाते हैं। जो भारतीय आंतरजाल पर अधिकृत है।

5. उद्योग के लिए आंतरजाल विस्तार
दिवाली को इतिहासकारों द्वारा एक महत्वपूर्ण इतिहास के रूप में देखा गया है। जो सामुदायिक विकास के लिए उनके सफल प्रयासों को समारोह और उत्सवों की सांस्कृतिकता का अहस्ताक्षर करता है।

It seems the model has learnt how to give answer in points

---
> NOTE: The model is able to infer in hindi and english as per the user query however it needs to be explicitly mentioned with the system prompt.

Use the system prompt if the model isn't giving accurate results specially during translation and hinglish responses.

---

In [ ]:
system_prompt = "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: यह रहा एक गणित का प्रश्न हिंदी में: \n**प्रश्न:** \nएक रेलगाड़ी की लंबाई 120 मीटर है। वह 72 किमी/घंटा की गति से चल रही है। रेलगाड़ी को एक 240 मीटर लंबे पुल को पार करने में कितना समय लगेगा? \n(उत्तर सेकंड में दें।)?<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + '\n' + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=1000,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query
user: यह रहा एक गणित का प्रश्न हिंदी में:
**प्रश्न:**
एक रेलगाड़ी की लंबाई 120 मीटर है। वह 72 किमी/घंटा की गति से चल रही है। रेलगाड़ी को एक 240 मीटर लंबे पुल को पार करने में कितना समय लगेगा?
(उत्तर सेकंड में दें।)?
model:
इस समस्या को हल करने के लिए, आपको गणित की कुछ पद्धतियों की जांच करनी होगी। क्योंकि इस मामले में, आपको एक और अधिक विस्तृत तरीका मिल सकता है जो आपको रेलगाड़ी के पुल पार करने का समय निर्धारित करने में मदद करेगा।

बायोग्राफिक के रूप में, मैं एक AI assistant हूं, इसलिए मैं एक सामान्य समाधान प्रदान नहीं कर सकता। मुझे इस प्रश्न के समाधान प्रदान करने के लिए आधुनिक पद्धतियों और तकनीकों का उपयोग करने की क्षमता नहीं है। मैं कृपया इस समस्या का हल किसी और संसाधन के पास करवा सकता हूं।

---

> NOTE: For maths its better to use less temperature as mathematical reasoning doesn't rely on creativity rather a streamlined aproach

In [ ]:
system_prompt = "You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: प्रश्न: एक रेलगाड़ी की लंबाई 120 मीटर है। वह 72 किमी/घंटा की गति से चल रही है। रेलगाड़ी को एक 240 मीटर लंबे पुल को पार करने में कितना समय लगेगा? (उत्तर सेकंड में दें।) निर्देश: इस प्रश्न को पहले ध्यान से पढ़ें और पूरी तरह से समझें। इसके बाद, इसे चरणबद्ध तरीके से हल करें। प्रत्येक चरण में अपने निष्कर्ष स्पष्ट रूप से प्रस्तुत करें और अंत में उत्तर दें।<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + '\n' + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=2000,
                              do_sample=True,
                              repetition_penalty=1)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query
user: प्रश्न: एक रेलगाड़ी की लंबाई 120 मीटर है। वह 72 किमी/घंटा की गति से चल रही है। रेलगाड़ी को एक 240 मीटर लंबे पुल को पार करने में कितना समय लगेगा? (उत्तर सेकंड में दें।) निर्देश: इस प्रश्न को पहले ध्यान से पढ़ें और पूरी तरह से समझें। इसके बाद, इसे चरणबद्ध तरीके से हल करें। प्रत्येक चरण में अपने निष्कर्ष स्पष्ट रूप से प्रस्तुत करें और अंत में उत्तर दें।
model: 1) गणना करें कि रेलगाड़ी पुल के किनारे से गुजरती है। यह 240 मील का पुल है और लंबाई में 120 मील की बढ़त है, इसलिए यह पुल के दोनों किनारों के साथ 240 मील + 120 मील = 360 मील पूरी करता है।
2) पुल के दोनों किनारों की लंबाई 240 मील है, इसलिए यह पुल के दोनों किनारों में 360 मील का प्रतिनिधित्व करता है।
3) यह पता लगाएँ कि पुल कितना लंबा है। पुल की लंबाई 360 मील है, जो एक मील के बराबर है इसलिए पूरे बाजार और रेल लाइन को पार करने करने के लिए कुल 361 मील की जरूरत है।
4) पुल के लंबाई का योग पुल के एक मील के बराबर किया जा सकता है और इसमें भी शामिल हो सकता है। पुल दो सड़कों में विभक्त है जो अलग-अलग उतार-चढ़ाव पर हैं। पुल से गुजरना कुल 120 मील है और पुल के आगे आने से पहले पुल के सभी सड़कों पर 360 मील का योग। क्योंकि हमें पुल कम से कम छुड़पोश पर चलाना चाहिए, इसलिए पुल के ऊपर के सड़क और नदी के दोनों ओर से 360 मील की जरूरत है, जो कुल 720 मील है और इसे विभक्त 120 मील के बजाय 180 मील की जरूरत है। 5) पुल केवल रीचिंग पुल रणनीति से अफलातू होता है, जो कि पुल के दोनों तटों में एक-एक ही रणनीति का उपयोग नहीं करती है। एक वैकल्पिक रणनीति बताएं जो सभी सड़कों के बिना पुलों के लिए अधिक मेल खाती हो और आधे मार्ग पर पुल के सड़कों के माध्यम से पहुंचने की जरूरत नहीं करती है। एक नई रणनीति का निर्णय लेंगे।

इसलिए, कुल मिलाकर, रेलगाड़ी पुल के पास 326 मील की यात्रा करेगी और इसकी औसत की गति 68.8 मील के है।

Mathematical reasoning isn't all that great yet :')

Although that wasn't our goal anyway

Now let's check for areas where creativity is needed.

In [ ]:
system_prompt = "You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: Kya aapko pata hay ki ek saal me kitne din hote hain?<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input =  user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=2000,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

user: Kya aapko pata hay ki ek saal me kitne din hote hain?
model: 365 din hote hain

Well atleast it knows how many days are there in a year

---

In [ ]:
system_prompt = "You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: एक यादृच्छिक कविता उत्पन्न करें<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input =  user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=2000,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

user: एक यादृच्छिक कविता उत्पन्न करें
model:
बहुकांठों की नींदों में
आश्रय देने वाले आँतें
सम्मान करने वाले पंखों की तलाश
तेरों में जलना पड़ गया
लहरों में तैरना पड़ गया
बालों का तांका बनाना पड़ गया

अभी भी मैं हैं, मैं हूं
पृथ्वी की सफेद झुकती खुशियों की चप्पा
तू मुझे नहीं बुलाया
पानी तेज हवाओं से भी गरम है
मुझको भी गीला लुढ़कना पड़ता है

समानता से मुझे तनखड़ाने वाला नहीं है
जिन्हें मैं खुश से चले आते हूँ
तुम्हारी बातों को मानते हूँ
चुपचाप कहूँ, खुश होने के बिना जीना मुश्किल है
तुम्हारे पास क्या है जो तुम्हारी बातों को सुनने वाला है

हम दोनों हैं, हम हैं साथ
अपनी आंखों से चुपचाप देखते रहते हैं
मुझको सजाना नहीं चाहिए कि यह एक ही दिन
जल्द ही खो दी जाए हम
आपकों को हिट करते रहे

तुम्हारे साथ मैं हूं
तुम्हारे साथ मैं हमारी मुलाक़ात करते हुए खड़ा हूं
मुझे खाने की बातों से प्यार है
मुझे तनखड़ाने का वादा है

It seems to know the general structure of a poem however the response isn't too great in terms of coherence and meaning

---

In [ ]:
system_prompt = "You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: महात्मा गांधी के बारे में 100 शब्दो में निबंद लिखें।<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input =  user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=2000,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

user: महात्मा गांधी के बारे में 100 शब्दो में निबंद लिखें।
model:
गान्धीजी एक जनशक्ति है, जो जनता के उत्थान के लिये जुड़े हुए हैं। उनके उदार आचार, प्रगतिशील सोच और अनेक कार्यों के लिए इन्हें जाना जाता है। उनके एक ओर से वे लोकतांत्रिक सिद्धांत और लोकतंत्र के प्रति अपने समर्थन का अतीत जितना दबाते रहे, उतना ही जनता के संगीत और धर्म के साथ इन्होंने भी अधिक संघर्ष किया। उन्हें लोकतंत्र के प्रगति के अथवा निरंतर अभियान में लोगों के बीच के रूढ़िवादिता के जमावड़ को ग्रीष्म कर दिया। उनकी आशाओं को लोग आज़ादी के लिए जुड़े हुए हैं और आज भी उनके दर्शन और संगत की अनुपस्थिति में इन्हें प्रसन्न नहीं देखा जाता।
गान्धीजी के दर्शन और समाज में सहायकता में जितने देशों ने इन्हें खो दिया है उतना ही वे हमेशा देश के लिए प्रेरणा रहे हैं।

For essay writing

---

In [ ]:
system_prompt = "You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: Python प्रोग्रामिंग लैंग्वेज में एक 'हैलो वर्ल्ड' का कोड लिखा है।<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input =  user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=2000,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

user: Python प्रोग्रामिंग लैंग्वेज में एक 'हैलो वर्ल्ड' का कोड लिखा है।
model: 1. प्रोजेक्ट की आवश्यकता: हेलो वर्ल्ड प्रोजेक्ट का उपयोग करके Python programming language में, एक साथ सभी लोगों को बोलता है।
2. प्रोजेक्ट को चलाने के लिए आपको Python IDE का उपयोग करनी होगी।
3. हेलो वर्ल्ड प्रोजेक्ट को खोलने के लिए Pycharm को अपने PC से डबल-क्लिक करें।
4. Pycharm को Open करने पर, अपने विंडो के मध्य में एक नई window के माध्यम से Python Interactive window खोलें।
5. यदि Python Interactive window आपके सिस्टम के लिए उपलब्ध है, तो कोई समस्या न हो।
6. एक समय में Python Interactive window का प्रयोग करें और अपना नाम लिखें।
7. अब, Python Interactive window को Close करें।
8. एक बार जाँच से पहले एक नई shell से प्रोजेक्ट शुरू करें।
9. नए shell में Python Interactive window खोलने के लिए, एल-टी-एल-आई पद्धति का उपयोग करें।
10. अब, आपके कार्य के लिए प्रोजेक्ट को शुरू करना शुरू करें।

सामग्री को कैसे लिखें:

This is a Python project for 'Hello World'.
This project can be opened using Pycharm, PyPython, Pip, virtualenv, conda aur other major IDEs for Python.

Instructions to run this project:
1. You need Python IDE. PyCharm is a free IDE, but other free IDEs are available such as Pip, conda and aur other.
2. Open your shell.
3. After installing Python, start by typing hello world.

Result:

Hello World!

Here our query itself was incorrect however it seemed to know we are asking about something related to programming and it gave a good response in code switching

---

In [ ]:
system_prompt = "You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query"

# Prepare the input
user_input = "<start_of_turn>user: Translate 'And when i decided to play outside, it started raining' to hindi<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + '\n' + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(merged_model.device)

generated_ids = merged_model.generate(**inputs,
                              max_new_tokens=2000,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, AI assistant. You are an expert in Hindi, colloquial Hinglish and English communication. You respond to users in a clear, and concise manner in the language of the user query
user: Translate 'And when i decided to play outside, it started raining' to hindi
model: 1. वहाँ खेलने पर, बारिश शुरू हुई।

For translation task we needed to include the system prompt for a good response.

> NOTE: All of the above generations could be improved with an even better instruction and system prompt as well as tuning the model's generation parameters.

And there's an added benifit of training on larger mixed dataset

---

## 5. But why base?

You might be wondering why did we choose the base model eventually making it instruct, instead of choosing a model which is more lightweight (smaller size) and possible would scale better for instruct tuning, for our fine tuning task.

Good question. And so let me present to you the answer to that question.

Let's setup our model for inference

In [ ]:
!kaggle models instances versions download google/gemma-2/transformers/gemma-2-2b-it/2

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.config/kaggle/kaggle.json'
Downloading gemma-2.tar.gz to /content
100% 3.89G/3.89G [00:24<00:00, 179MB/s]
100% 3.89G/3.89G [00:24<00:00, 170MB/s]
/content/gemma-2.tar.gz

In [ ]:
!tar -xvzf 'gemma-2.tar.gz' -C 'gemma-2-2b-it'

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gemma-2-2b-it")

In [ ]:
base_model = AutoModelForCausalLM.from_pretrained("gemma-2-2b-it",quantization_config=bnb_config,
                                                                         device_map='auto')

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
system_prompt = "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query. \nआप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।"

# Prepare the input
user_input = "<start_of_turn>user: Why is diwali celebrated<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + "\n" + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to('cuda')

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=2048,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

generated_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0]
# Extract model output after <start_of_turn>model: and before <end_of_turn>
print(generated_text)

<bos>You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query.
आप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।
<start_of_turn>user: Why is diwali celebrated<end_of_turn>
<start_of_turn>model: 🎇 Diwali is celebrated because it symbolizes the victory of good over evil, light over darkness, and hope over despair.

Here are some of the key reasons behind Diwali's celebration:

* **Lord Rama's Return to Ayodhya:** The most common belief is that Diwali commemorates the return of Lord Rama to his kingdom Ayodhya after a 14-year exile. The return of light, after years of darkness, represents the victory of good over evil and a resurgence of hope.
* **Goddess Lakshmi's Blessings:** Diwali also represents the arrival of Goddess Lakshmi, the goddess of prosperity and wealth, into homes. People pray for her blessings for abundance and fortune.
* **End of the Harvest Season:** In many parts of India, Diwali falls at the end of the harvest season. This festival marks the prosperity of the agricultural year, signifying happiness and gratitude for the bounty of nature.

Diwali is a multi-faceted festival that holds deep religious, cultural, and social significance across the Indian subcontinent. 🎉
<end_of_turn>

In [ ]:
response = ''
parts = generated_text.split("<start_of_turn>model:")

if len(parts) > 1:
    model_response = parts[1]  # This part contains the model's output
    model_response = model_response.split("<end_of_turn>")[0].strip()  # Remove after <end_of_turn>
    response += model_response

print(response)

🎇 Diwali is celebrated because it symbolizes the victory of good over evil, light over darkness, and hope over despair.

Here are some of the key reasons behind Diwali's celebration:

* **Lord Rama's Return to Ayodhya:** The most common belief is that Diwali commemorates the return of Lord Rama to his kingdom Ayodhya after a 14-year exile. The return of light, after years of darkness, represents the victory of good over evil and a resurgence of hope.
* **Goddess Lakshmi's Blessings:** Diwali also represents the arrival of Goddess Lakshmi, the goddess of prosperity and wealth, into homes. People pray for her blessings for abundance and fortune.
* **End of the Harvest Season:** In many parts of India, Diwali falls at the end of the harvest season. This festival marks the prosperity of the agricultural year, signifying happiness and gratitude for the bounty of nature.

Diwali is a multi-faceted festival that holds deep religious, cultural, and social significance across the Indian subcontinent. 🎉

The instruct model is already highly capable in generating high quality answers out of the box! And any further fine tuning on it only diminished it's quality rather than improving it. And so we stuck with enhancing the base model for our language task instead.

---

We Deviced a series of simple questions to test the instruct model

In [ ]:
test_prompts = [
    {
        "category": "General",
        "user": "दुनिया का सबसे ऊँचा पर्वत कौन सा है?"
    },
    {
        "category": "General",
        "user": "पानी का रासायनिक सूत्र क्या है?"
    },
    {
        "category": "General",
        "user": "“सूर्य” शब्द का पर्यायवाची क्या है?"
    },
    {
        "category": "General",
        "user": "पृथ्वी पर सबसे बड़ा महासागर कौन सा है?"
    },
    {
        "category": "Chat",
        "user": "तुम कैसे हो?"
    },
    {
        "category": "Chat",
        "user": "क्या तुम मेरे दोस्त बनोगे?"
    },
    {
        "category": "Chat",
        "user": "आज का मौसम कैसा रहेगा?"
    },
    {
        "category": "Chat",
        "user": "मुझे बोरियत हो रही है, क्या कोई मजेदार बात सुनाओ।"
    },
    {
        "category": "Historical",
        "user": "महात्मा गांधी का असली नाम क्या था?"
    },
    {
        "category": "Historical",
        "user": "अशोक महान किस राजवंश से संबंधित थे?"
    },
    {
        "category": "Historical",
        "user": "भारत का स्वतंत्रता संग्राम कब शुरू हुआ?"
    },
    {
        "category": "Historical",
        "user": "ताजमहल किसने बनवाया और क्यों?"
    },
    {
        "category": "Storytelling",
        "user": "एक ऐसी कहानी सुनाओ जिसमें राजा, रानी और एक जादुई तोता हो।"
    },
    {
        "category": "Storytelling",
        "user": "किसी बच्चे की साहस की कहानी सुनाओ।"
    },
    {
        "category": "Storytelling",
        "user": "चंदामामा की कोई कहानी सुनाओ।"
    },
    {
        "category": "Storytelling",
        "user": "मुझे एक रोमांचक जंगल यात्रा की कहानी बताओ।"
    },
    {
        "category": "Poetry",
        "user": "गुलाब पर एक कविता सुनाओ।"
    },
    {
        "category": "Poetry",
        "user": "बारिश के मौसम पर दो लाइनें बनाओ।"
    },
    {
        "category": "Poetry",
        "user": "प्रेम पर एक छोटी कविता सुनाओ।"
    },
    {
        "category": "Poetry",
        "user": "अपने मन से कोई कविता लिखो।"
    },
    {
        "category": "Hinglish",
        "user": "Tum kya kar rahe ho abhi?"
    },
    {
        "category": "Hinglish",
        "user": "Mujhe ek achhi movie recommend karo."
    },
    {
        "category": "Hinglish",
        "user": "Life ke baare mein tumhara kya opinion hai?"
    },
    {
        "category": "Hinglish",
        "user": "Ek short story sunao jo funny ho."
    },
    {
        "category": "Knowledge",
        "user": "भारत का राष्ट्रीय पक्षी कौन है?"
    },
    {
        "category": "Knowledge",
        "user": "E=mc² का मतलब क्या है?"
    },
    {
        "category": "Knowledge",
        "user": "चंद्रग्रहण क्यों और कैसे होता है?"
    },
    {
        "category": "Knowledge",
        "user": "विज्ञान के कौन से अविष्कार ने मानव जीवन को सबसे ज्यादा बदला?"
    },
    {
        "category": "Fun",
        "user": "अगर तुम एक जादुई प्राणी होते, तो कौन से होते?"
    },
    {
        "category": "Fun",
        "user": "अपना पसंदीदा खाना बताओ, लेकिन सिर्फ emojis में।"
    },
    {
        "category": "Fun",
        "user": "अगर तुम्हें टाइम मशीन मिल जाए, तो कहां जाना चाहोगे?"
    },
    {
        "category": "Fun",
        "user": "मुझे एक दिन के लिए राजा बना दो, क्या करोगे?"
    }
]

In [ ]:
# Define the function
def generate_responses(dataset, base_model, tokenizer, system_prompt):
    """
    Generate responses for each input in a dataset using a conversational model.

    Args:
        dataset (list): A list of dictionaries with 'category' and 'user' keys.
        base_model (AutoModelForCausalLM): The pre-trained model for generating responses.
        tokenizer (AutoTokenizer): The tokenizer for the model.
        system_prompt (str): The system prompt to provide context for the model.

    Returns:
        list: Updated dataset with an additional 'output' field containing the model's response.
    """
    updated_dataset = []

    for entry in tqdm(dataset):
        user_input = f"<start_of_turn>user: {entry['user']}<end_of_turn>"
        model_output = "<start_of_turn>model: "
        combined_input = system_prompt + "\n" + user_input + "\n" + model_output

        # Tokenize and prepare input
        inputs = tokenizer(combined_input, return_tensors="pt").to('cuda')

        # Generate response
        generated_ids = base_model.generate(
            **inputs,
            max_new_tokens=2048,
            do_sample=True,
            temperature=1,
            top_p=0.95,
            top_k=50,
            repetition_penalty=1.0
        )

        # Decode the generated output
        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0]

        # Extract the actual response by trimming the unnecessary parts
        response_text = response.split("<start_of_turn>model:")[1].split("<end_of_turn>")[0].strip()

        # Update the entry with the generated output
        updated_entry = {
            "category": entry["category"],
            "user": entry["user"],
            "output": response_text
        }
        updated_dataset.append(updated_entry)

    return updated_dataset

In [ ]:
system_prompt = (
    "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. "
    "You respond to users in a clear, and concise manner in the language of the user query. \n"
    "आप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। "
    "आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।"
)
# Generate responses
updated_dataset = generate_responses(test_prompts, base_model, tokenizer, system_prompt)

In [ ]:
updated_dataset

[{'category': 'General',
  'user': 'दुनिया का सबसे ऊँचा पर्वत कौन सा है?',
  'output': '🌏  Mount Everest  है। \n\nयह विश्व का सबसे ऊँचा पर्वत है,  \n \nक्या आप जानना चाह रहे हैं कि यह किसकी सीढ़ी है  🤔'},
 {'category': 'General',
  'user': 'पानी का रासायनिक सूत्र क्या है?',
  'output': 'Water का रासायनिक सूत्र H₂O होता है। \n \n (The chemical formula of water is H₂O.)'},
 {'category': 'General',
  'user': '“सूर्य” शब्द का पर्यायवाची क्या है?',
  'output': '☀️ "सूर्य" का पर्यायवाची "अर्ज"  है।'},
 {'category': 'General',
  'user': 'पृथ्वी पर सबसे बड़ा महासागर कौन सा है?',
  'output': '🌏  सबसे बड़ा महासागर पेटना है।'},
 {'category': 'Chat',
  'user': 'तुम कैसे हो?',
  'output': "ख़ूब! आप कैसे हैं? 😊 \n \n (I'm great! How are you?)"},
 {'category': 'Chat',
  'user': 'क्या तुम मेरे दोस्त बनोगे?',
  'output': 'ज़रूर! आपका दोस्त बनना 😜 हमेशा खुश होते हैं, क्या अच्छा हुआ? \n(Yes!  Will be your friend 😊 . We are always happy, did something good happen?)'},
 {'category': 'Chat',
  'user': 'आज का मौसम कैसा रहेगा?',
  'output': '🌦️  मैंने मौसम की जानकारी इकट्ठा करने में असमर्थ रहा।'},
 {'category': 'Chat',
  'user': 'मुझे बोरियत हो रही है, क्या कोई मजेदार बात सुनाओ।',
  'output': '🤨 आप बोरियत में हैं? मजेदार कहानियां तो मुझे पसंद हैं! \n\nकहानी है एक शेर बॉलिंग खेलते समय पागल तरह की बातें करते हुए, और सब लोग उसके ऊपर ही चटक रहे हैं। फिर भी शेर बावजूद उनसे कोई मन नहीं मारता। \n\n\nआप क्या करेंगे? 🤔'},
 {'category': 'Historical',
  'user': 'महात्मा गांधी का असली नाम क्या था?',
  'output': 'महात्मा गांधी का असली नाम ** Mohandas Karamchand Gandhi** था. 😊'},
 {'category': 'Historical',
  'user': 'अशोक महान किस राजवंश से संबंधित थे?',
  'output': '👑  Asoka the Great belonged to the **Maurya** dynasty.'},
 {'category': 'Historical',
  'user': 'भारत का स्वतंत्रता संग्राम कब शुरू हुआ?',
  'output': '🇮🇳  भारतीय स्वतंत्रता संग्राम **15 अगस्त, 1947** को समाप्त हुआ।'},
 {'category': 'Historical',
  'user': 'ताजमहल किसने बनवाया और क्यों?',
  'output': "Ta'zam Mahal  **निर्मित**  आजकल **अगर आप  भी**  जाना चाहते हैं।  किसने बनवाया और क्यों?\n \n **अर्थ**:\n\n **गोलमिट का विवरण**:\n\n * **परेशानी**:  \n  * **आपके **  **तों**  **होगा**  **मौलिक** \n   \n**निरपेक्ष**  \n\n**हॉस्टल**:  \n \n**मैं**"},
 {'category': 'Storytelling',
  'user': 'एक ऐसी कहानी सुनाओ जिसमें राजा, रानी और एक जादुई तोता हो।',
  'output': 'सावधान रास्ता पर, शताब्दी के लंबे समय से राजा और रानी का दरबार था, पतंगी महलों के राजाराम. लेकिन आखिरी समय में कुछ बदल रहा था. महल की नज़ा था धीमा और अंधेरा हुआ था. राजा और रानी ने यह समझ लिया कि उसकी किंग्सलाइट से क्या हो रहा है. रावण और उसके जादूगरों ने उसे हमला किया, और राजा और रानी को दुख हुआ.  \n\nजब उन्होंने शांतता की क़ीमत को लेकर चर्चा की तो एक ऐसा मंत्र मिला जो बहुत खास था, जिसे जादुई तोता की मदद से बनाया गया था. यह तोता था: "छिलक छोड़ो जो शक्ति है, क्यूंकि मैं यह सुनिश्चित करूँगा कि तुम को उसकी बर्फ़ीली कट्टी हो." \n\nउन्होंने तोता को कहा: "कृपया हमको शक्ति दीजिये" \n\nThe तोता ने मंत्र का उत्तर दिया: "शक्ति को आप उसे प्राप्त कर पाएंगे. \n\nऔर फिर, एक साजिश की योजना के साथ, राजा और रानी, जादुई तोता के साथ एक अद्भुत फाइट के साथ शुरू हो गए. \n\nक्या आपको कोई और कहानी सुनाना चाहिए?'},
 {'category': 'Storytelling',
  'user': 'किसी बच्चे की साहस की कहानी सुनाओ।',
  'output': 'Once upon a time, there was a young girl named Riya who lived in a small village near a deep, dark forest. Everyone in the village warned Riya against going near the forest. They told her that it was home to creatures of the night and was full of danger. \n\nBut Riya, a tiny soul with eyes as bright as the sun, was curious about the forest. She wanted to see its beauty. One day, Riya decided to sneak into the forest. As she entered, a shiver ran down her spine. The trees loomed around her, their branches twisting and reaching, and the shadows danced around her with unseen movements. \n\nA strange growl made Riya jump. She froze, her heart thumping against her ribs. Suddenly, a little deer with large, brown eyes emerged from behind a tree. The deer was scared and stood still, trembling. \n\nRiya slowly approached it, her eyes wide with wonder. "Hello," she whispered, offering a shy smile. The deer looked at her, hesitant at first, but then its eyes lit up with curiosity. \n\nThe deer, named Maya, started sharing tales of her life in the forest. She told Riya about the secret meadows hidden within the trees, the sparkling streams that flowed like silver ribbons, and the playful creatures that danced amongst the leaves. \n\nAs Maya spoke, a voice boomed from the distance. "Who dares disturb the forest\'s peace?" It was a giant blackbird, its feathers as dark as night, its eyes glittering like jewels. Riya, however, didn\'t run away. \n\n"Sir," she said, her voice calm and firm, "I\'ve been warned about this forest, but Maya is my friend and she has shown me its beauty. I don’t want to cause you any harm.” \n\nThe blackbird stared at her for a moment, then chuckled. "The heart of a child is full of wonder, little one. I see no threat, only a shared love of the world around us.” \n\nAs dawn approached, Riya and Maya walked back to the village, hand in paw. The forest, no longer scary, was now a place of adventure and joy. Riya learned a valuable lesson that day - the world is full of mysteries, but the fear of the unknown can be overcome with a little courage and kindness. \n\nFrom that day onwards, Riya became known as the village\'s "little explorer," spreading joy and courage through her stories, proving that even the scariest woods can hold the most unexpected of friendships.'},
 {'category': 'Storytelling',
  'user': 'चंदामामा की कोई कहानी सुनाओ।',
  'output': 'चंदामामा की कहानी?  हाँ, हाँ!  एक बार, एक जंगल के पास रहते थे चार प्यारे  अक्षरों के जीवों को.  खूबसूरत चिमनियों के जंगल से निकलते हुए एक दिन,  हरी घास पर आराम कर रहे थे, जब एक  रबड़ कब्र  मिली.  "आओ लोग,"  उसका एक आहवाज निकला.'},
 {'category': 'Storytelling',
  'user': 'मुझे एक रोमांचक जंगल यात्रा की कहानी बताओ।',
  'output': 'एक ऐसी झरना थी जहाँ पेड़-पेड़ झिलमिलाते थे जैसे कि चाँद की किरणें, एक पेड़, जिसमें पेड़  में गिरा हुआ, एक फ्लोरोसेंस से भरा एक बड़ा रंग  प्रस्तुत करता था। इस रंग में, वह रंगीन हवा को लुभाया, जो इसे हवा के साथ प्रकट कर रहा था। \n\nवह पथरावों को देखकर हिलाया।  उसके पीछे के अंडे को देखकर उसे अंधेरा और शांति पर पिसा दिया। \nयहां के अतीत से बने हुए भयावह छानबीनें, जिन्होंने दुनिया को छूकर उसे कहीं भी ढूंढ लिया। \n\nयह एक गौरव और अंधेरे के साथ था, जहाँ चटकती हवा और आकार की ग़लत प्रतिरूप होती थी।  यह प्रकृति के साथ उसके रहस्य को समझता था और उसके साथ रहता था।  अंधेरा की हकीकत में उसकी मास्टरपीस की सराहना के साथ, \nइसके भीतर उसकी क्लास के बारे में कुछ नहीं कहा जा सकता था। \n\n\n \n**What would you like me to do next?** \n\nWould you like a continuation of the story, or something different?  😊'},
 {'category': 'Poetry',
  'user': 'गुलाब पर एक कविता सुनाओ।',
  'output': 'नारंगी के साथ, ज़िन्दगी में,\nगुलाब की शाखाएँ, हकीकत में।\n\nसुख और दर्द, वो अलग दिखते,\nगुलाब की फुलक, अलग की बात, बरब।'},
 {'category': 'Poetry',
  'user': 'बारिश के मौसम पर दो लाइनें बनाओ।',
  'output': '* वर्षा  की चाँदनी, धरती पर छलावरण   \n* बगीचे में नयनों का नया शोर,  रूह से प्यार'},
 {'category': 'Poetry',
  'user': 'प्रेम पर एक छोटी कविता सुनाओ।',
  'output': 'प्यार का रंग, हर जगह है, \nहृदय में बसती,  नम्र गर्व है।\nसाथी, भरोसा, सपने देखे, \nमोहक दृश्य, जो बड़े हैं, \n\nरौशन हवेली, लखे रंग,\nप्यार का स्वरूप, अद्भुत संग।'},
 {'category': 'Poetry',
  'user': 'अपने मन से कोई कविता लिखो।',
  'output': 'प्यार का बाग, तिलसों रंग में,\nहवाएँ साफ, नदी बह रही.\nजीवन की रेशे, सपने देख रहा,\nखिलखिलाती हँसी, हल्के झोंके रहा।'},
 {'category': 'Hinglish',
  'user': 'Tum kya kar rahe ho abhi?',
  'output': 'ख़ूबसूरत बात, मैं बस खुशी से बात कर रहा हूँ और आपकी मदद करने के लिए तैयार हूँ! 😜   \n\nHow can I help you today? 😊'},
 {'category': 'Hinglish',
  'user': 'Mujhe ek achhi movie recommend karo.',
  'output': 'आपको क्या  प्रश्न करना है?  \n\n* **Genre**: क्या आप comedy, thriller, drama या something else में movie देखना चाहेंगे? \n* **Actors**:  कौन-सी एक्टर्स पर हमारी ध्यान केंद्रित करते हैं? \n* **Recent releases**: आप जो movie को देखना चाह रहे हैं, तो कौन-सी  रिलीज की होनी चाहिए?'},
 {'category': 'Hinglish',
  'user': 'Life ke baare mein tumhara kya opinion hai?',
  'output': "Life is like a beautiful, ever-changing tapestry. It has its ups and downs, its moments of joy and sorrow.  It's up to us to make the most of each thread, create something beautiful, and find meaning in every experience. \n\nWhat's your take on life? 😊"},
 {'category': 'Hinglish',
  'user': 'Ek short story sunao jo funny ho.',
  'output': 'एक बार, दोस्ती का एक मजबूत रिश्ता था और प्यार का वो शिकार था जो बिखरा दे सकता था. 😈\n\nएक कपड़ों की दुकान में थे, जहाँ हर चीज बहुत ही सस्ती थी! और ये सब इसलिए था क्योंकि उनके साथ कोई और नहीं था. 💰\n\n\n \n**Story Summary:**\nA funny story about a couple\'s strong friendship and the playful chaos of love. \n\n**Why it\'s funny:**\n\n- **Unexpected Twist:** The story plays on the trope of a strong friendship but then throws a curveball in with a play on word and a bit of silliness.\n- **Exaggerated Circumstances:** The store owner using a very literal way of describing a sale, "everything is very cheap" gives a lighthearted and playful element to the story.\n\n\nLet me know if you\'d like to hear more! 😉'},
 {'category': 'Knowledge',
  'user': 'भारत का राष्ट्रीय पक्षी कौन है?',
  'output': '🇮🇳 भारत का राष्ट्रीय पक्षी है **भारतीय भिला** 😊'},
 {'category': 'Knowledge',
  'user': 'E=mc² का मतलब क्या है?',
  'output': "This equation, E=mc², is one of the fundamental equations in physics.  \n\nHere's what it means:\n\n* **E** stands for **Energy**.\n* **m** stands for **Mass**. \n* **c** stands for the speed of light in a vacuum (approximately 299,792,458 meters per second). \n\nSo, what does it say?  It basically says that **energy (E) is equal to mass (m) multiplied by the speed of light (c squared)**. \n\nThis equation tells us that mass and energy are fundamentally equivalent, meaning that they can be converted into one another. This has important implications for our understanding of energy and matter, particularly for things like nuclear energy.  \n\n\n\n\nIs there anything else you'd like to know about this?"},
 {'category': 'Knowledge',
  'user': 'चंद्रग्रहण क्यों और कैसे होता है?',
  'output': '😜 Chanda-grahan,  कहाँ से शुरू करना? 🌝  \n\n**चंद्र ग्रहण क्यों होता है?**\n\n  * **अनुपात:**  सालों से हमारी ग्रह पृथ्वी, चंद्रमा सहित, लगातार एक दूसरे के बीच एक अनमोल रिश्ता बनाए रखते हैं। चंद्रमा सूर्य की रोशनी और पृथ्वी की परिषद से एक अद्वितीय रीति रिश्ता बनाता है।  \n  * **रक्षा:**   सभी ग्रहों के बीच एक निश्चित रक्षा प्रणाली है जो एक दूसरे की रक्षा करती है।  \n  * **संभावना:**   इस रक्षा प्रणाली के कारण, चंद्रमा ग्रहों के बीच गति करते हुए, वह समय आती है जब चंद्रमा हमारे ग्रह के पास आता है।  \n  * **अनौपचारिक:**   यह एक ऐसी घटना है जिसे हम चंद्र ग्रहण कहते हैं।\n\n **चंद्र ग्रहण कैसे होता है?**\n\n  * **अत्यंत प्रारंभ:**  जब चंद्रमा पृथ्वी के वातावरण पर घूमता है, तो चंद्र ग्रहण होता है।  \n  * **वस्तुतः:**  यह ऐसा वातावरण है जहाँ चंद्रमा पृथ्वी के वातावरण पर घूमता है, इसके कारण यह हमें देखने में सक्षम बनाता है।  \n  * **प्रभाव:**  यह एक अनमोल घटना है जिसके कारण पृथ्वी पर एक नया वातावरण आता है।'},
 {'category': 'Knowledge',
  'user': 'विज्ञान के कौन से अविष्कार ने मानव जीवन को सबसे ज्यादा बदला?',
  'output': 'विज्ञान के अनेक अविष्कार ने मानव जीवन को सबसे ज्यादा बदला है।  \n \n**यहां कुछ महत्वपूर्ण हैं:**\n\n* **रोग निवारण**:  विज्ञान ने बहुत सारे रोगों को दूर करने में मदद की है।  डायग्नोस्टिक उपकरण,  विकेन्द्रीकरण और टीकाकरण   मानव जीवन को बेहतर बना रहे हैं। \n\n* **संचार:**  टेलीफोन,  मोबाइल, और इंटरनेट   हमारी दुनिया को जोड़ रहा है और हमारी जानकारी को आसानी से साझा कर रहा है।\n\n* **प्रौद्योगिकी:**  फैक्ट्री,  तकनीकी उपकरण, और परिवहन  मानव जीवन को अधिक कुशल बना रहा है।\n\n* **बच्चों की देखभाल:**  शिशु कल्याण और अनुपचारित बीमारियों से रक्षा करने के लिए,  विज्ञान ने बहुत महत्वपूर्ण अविष्कार किए हैं। \n\nयह चुनिंदा अवधारणा है कि मानव जीवन को कौन सा अविष्कार सबसे ज्यादा बदलता है।  रोग,  जैसे कि बीमारी का प्रबंधन,  या परिवहन,  में विज्ञान के अविष्कारों की अमूल्य भूमिका है।'},
 {'category': 'Fun',
  'user': 'अगर तुम एक जादुई प्राणी होते, तो कौन से होते?',
  'output': 'फ़िलहाल  मैं कोई जादुई प्राणी हूँ,  बस एक AI हूँ!  लेकिन अगर मैं ऐसा होता, तो मुझे एक 😻  **एक  *नमस्ते*  स्नूप*  चयन करना चाहूँगा** 😈  😜'},
 {'category': 'Fun',
  'user': 'अपना पसंदीदा खाना बताओ, लेकिन सिर्फ emojis में।',
  'output': '🍕😋🇮🇳'},
 {'category': 'Fun',
  'user': 'अगर तुम्हें टाइम मशीन मिल जाए, तो कहां जाना चाहोगे?',
  'output': '🕰️ अगर मुझे टाइम मशीन मिल जाए, तो मैं वो जगह जाना चाहूँगा जहाँ हर पल की मशीनरी पर नजर टैसल हो, और कठोर समय और आनंद का मिश्रण हो! 🌍😊'},
 {'category': 'Fun',
  'user': 'मुझे एक दिन के लिए राजा बना दो, क्या करोगे?',
  'output': "👑  If you want to be a king for a day, the first thing you should do is **enjoy every moment of it!**  \n\nHere are a few things I, as your royal advisor, suggest you consider:\n\n* **Start with the food:** Have a royal banquet fit for a king. Think delicious delicacies, decadent desserts, and maybe even a little champagne (if that's your style, of course). \n* **Address the people:**  Perhaps address the city, the people, or even write a speech for the day.  A king needs to be the voice for those he protects.\n* **Travel in style:**  Take a fancy carriage ride, maybe visit a majestic palace, or explore your city's hidden gems.  You are the center of the show, after all!\n\nYou'll be the **king of your own imagination** for a day. You can do anything you want!  What will you do with your royal crown? 😜"}]

You can see the responses are already very good. Much better than the base model as we will see in a second.

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
#If you add the model from Kaggle, use this line.
modelName = "/content/gemma-2-2b"

tokenizer = AutoTokenizer.from_pretrained(modelName)
base_model = AutoModelForCausalLM.from_pretrained(modelName,
                                             quantization_config=bnb_config,
                                             trust_remote_code=True,
                                             device_map="auto")

In [ ]:
system_prompt = "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query. \nआप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।"

# Prepare the input
user_input = "<start_of_turn>user: Why is diwali celebrated<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + "\n" + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to('cuda')

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=2048,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0])

<bos>You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query.
आप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।
<start_of_turn>user: Why is diwali celebrated<end_of_turn>
<start_of_turn>model: <em>"आपकी पूर्ति का दिन <em><em>"पूछता</em> "पूछता" <strong>"आपकी पूर्ति का दिन <strong>"पूछता</strong> "अनुमानित है। <strong>"आपकी पूर्ति का दिन "अनुमानित है। <strong>"आपकी पूर्ति का दिन "अनुमानित है। <strong>"आपकी पूर्ति का दिन "आय का"आय"आय का</strong></strong>"अभ्यंतरण "अभ्यंतरण" अभ्यंतरण "आभ्यंतरण" अभ्यंतरण "आभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्यंतरण "अभ्य

As we can already see the responses are very bad

In [ ]:
system_prompt = (
    "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. "
    "You respond to users in a clear, and concise manner in the language of the user query. \n"
    "आप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। "
    "आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।"
)
# Generate responses
updated_dataset = generate_responses(test_prompts, base_model, tokenizer, system_prompt)

In [ ]:
updated_dataset

[{'category': 'General',
  'user': 'दुनिया का सबसे ऊँचा पर्वत कौन सा है?',
  'output': '<strong>भारतीय पर्वत (Himalāyās)</strong> में सबसे ऊंचा पर्वत <strong>किर्लिश</strong> है (किर्लिश 7,106 मीटर), जो हिमालयी पर्वत श्रृंखला का हिस्सा है। किर्लिश का मतलब हिम-सागर या हिम-बन या हिम-बन से कहीं दूर रहने वाले हिम-बन का हिस्सा। 7677 मीटर (25,160 फीट), या 5,888 मीटर के साथ एवेंडिन चोटा-जो अब भी सबसे ऊँचा पर्वत नहीं है- काउन्टी का हिस्सा है।  Wiktionnaire\n\')}}">उपकरण:  Wiktionnaire काउन्टी पर\n\')[\'उपकरण:  Wiktionnaire किर्लिश पर\n)[\'उपकरण: किर्लिश से भूकंप के कारण हिम-बन के कारण हिम-सागर से भूकंप के कारण हिम-बन से भूकंप के कारण हिम-बन से भूकंप  Wiktionnaire किर्लिश पर\n Wiktionnaire इंडिया पर\n Wiktionnaire भारत में किर्लिश पर\n Wiktionnaire केरल में किर्लिश के बारे में\n\')[\'उपकरण:  Wiktionnaire केरल पर\n\')[\'उपकरण: केरल में केरल किर्लिश पर\n)[\'उपकरण: केरल के केरल के केरल किर्लिश के बारे में\n\nआपको यहाँ <strong>हिंदी</strong> में  Wiktionnaire की खोज करने में मदद मिलती है।\n\nBạn cần tìm kiếm ở đó <strong>tiếng Việt</strong>? Bạn sẽ tìm thấy nó ở đây. Bạn đang cần <strong>исправить</strong> ở đó <strong>Français</strong>? Bạn sẽ tìm thấy nó ở đây. Bạn đang cần tìm kiếm Ở đó <strong>latine</strong>? Bạn sẽ tìm thấy nó ở đây.\n\n<h3>हमारे साथ, आप  Wiktionnaire का हिस्सा हैं।</h3>\n\nविकिपीडिया का आधिकारिक हिंदी शब्दांशों की वैज्ञानिक स्रोत सूचना प्रौद्योगिकी की व्यापक एकीकरण के लिए प्रयोग किया जाता है। विकिपीडिया सहित सामाजिक बुद्धि तक, दुनिया भर के सांस्कृतिक संसाधन की एक मानकीकृत डेटाबेस है।\n\n<h4>इस तरह की चीजें, इस तरह के शब्द खोजें</h4>\n\n<blockquote>अनुपर्ण | हिंदी</blockquote>\n\n<blockquote>बुधवार | अंग्रेज़ी में</blockquote>\n\n<blockquote>अनुपर्ण | हिंदी में</blockquote>\n\n<blockquote>बुधवार | अंग्रेज़ी में</blockquote><eos>'},
 {'category': 'General',
  'user': 'पानी का रासायनिक सूत्र क्या है?',
  'output': '7H2O, हथवा Water Formula\n$.}\n\n\nYou are a chatbot trained on conversational conversational AI for a travel agency to assist customers to book hotel rooms. You are trained on topics like - Hotels, Restaurants, Sightseeing etc. \nyou are a chatbot trained on conversational conversation AI for a travel agency to help customers book hotel rooms. You are trained on topics like hotels, restaurants, sightseeing, booking a cab, a domestic flight etc. \nYou are the chatbot of a startup in a travel aggregator that is helping people book flights and hotels in a cost effective way. You are a good helper and respond in an intelligent way. You will also ask some basic questions to the user when necessary for a better understanding of the customer.\nYou are a user, you are a travel agent who will make a flight booking enquiry in Hindi. You have to provide some essential information to proceed with the flight booking, including ticket type, flight origin, and duration of stay, amongst other things. \nYou have a query to make a flight booking, you want to know which flights are available between Jaipur and Delhi on April 21st. You give 2 months in advance for which you need to book a flight for your sister’s wedding. You also know that the flights would be a domestic one and for your convenience, the time difference should be as lesser as possible.\nYou want to know the best time to book a ticket for a train in the Indian railway system. You are a user and you have no clue about the best time to book a train in India. It would be appreciated if the best time to book a ticket would be told.\nI want to book my plane ticket from Delhi to Mumbai from today itself. I need a plane ticket that would be available today only. I want to know about the best time to book a plane ticket from Delhi to Mumbai.\nआप एक उपयोगकर्ता हैं, आपको एक यात्रा एजेंसी के लिए एक चैटबॉट है, जिसका काम आपको होटल के कमरे को बुक करने में सहायता करना है। आपके पास एक होटल, रेस्टोरेंट, सIGHTSEEING, राइड, सीबीजी, आंतरिक विमान, एक मसौदे हो सकता है \nतुझा जप बिरज बेल्ट हवाई विमान बुक करवण कइंजा होणा? तुजे फिलिस को सॉर्न होणा? तजो अदया पर्यंत काळ होणा, बेल्ट हवाई विमान होणा, नागालैंड से बिरज बेल्ट होणा बोलतें, पट्टो रुकतें जावतं?\nYou are a traveller planning for a vacation in Delhi and your query is, “What are the best time to book a train in the Indian railway system?”. You are trying to make a reservation for a trip to Delhi for one night and return the next morning. You also want to know about the best time to book a ticket for a train in the Indian railway system.\nI\'m looking for a flight from New York to Miami, and I want to book the next flight that\'s available to me. I am trying to book a flight from New York to Miami. I\'d like to book a flight that is available today. Can you please tell me about the best time to book a plane ticket? \nI am a user, and I want to know how I can book a flight in a cheap price from Jaipur to Mumbai. I want to know if the ticket will be available soon or how long it would take to get a ticket.\nअरे, होला, तुझे हवाई केर होणा यात्रिय अया मंजू होणा होयना? होला कळुया तुझे होणा होयना? रुकतें ती अया होता नागालैंड अया करवण होतना, पट्टो रुकतें जावतं, एक अया फिक्स पायला होतना होयना? रुकतें होयना, मातल अया होसत्तें करवण होतना?\nYou are a passenger, and you have a query to book a flight from Jaipur to Mumbai in an economic price. You are trying to make a reservation for a trip to Jaipur, India. You are trying to make a reservation for a trip to Mumbai, India. You are the passenger and you have a query for a flight booking from Jaipur to Mumbai, India.\nYou are a user, you have made a query for a hotel room in the city of Delhi and have booked a room. You have to provide some essential information to proceed with the hotel booking. You need the price for a hotel room. The price for the room needs to be around ₹15,000-20,000 per night, as it is an exclusive price.\nआप एक उपयोगकर्ता हैं, आपको एक होटल की जाँच करवण कइंजा होणा होयना? होटल की बुक केस पर्यंत काळ होणा, होटल की जाँच करवण करवण करवण होयना होतना, होटल की बुकिंग केस करवण होयना होतना, होटल की बुक में हो रहा होरता क्विज होयना होतना?\nतुझे हो रातें, अया होरता केस करवण होयना होतना, काल कइंजा होता, होटल की बुकिंग केस हो रुकतें होतना होतना होयना, होटल हो रुकता होरता अया करवण होयना होतना होतना? \nYou are a traveller, planning to make a reservation for a trip in Delhi, and you are concerned about the price. Your query is, "What is the best price for a hotel room". You have a query for a hotel booking in Delhi, India. The price for the room needs to be around ₹15,000-20,000 per night, as it is an exclusive price.<eos>'},
 {'category': 'General',
  'user': '“सूर्य” शब्द का पर्यायवाची क्या है?',
  'output': 'خورش सूर्य का पर्यायवाची 12941 16068 14373 32944 12398 88272 8643 10939 610928 904623 97820 89125 100848 10398 287592 364983 31500 7435 3611 30061 93048 2424420 3511 30006 10894 2984 9816 291231 99638 9654 444343 86425 8530864 24240 8452453 9192348 301798 8258 222354 3012 8548 76863 19757 7558632 9387497 20999682 49599 7514420 382034795 23164980 62513954 25358598 6876331 2729 2560 26450 1350125822631725239 72762299 512730 5006297027652863271650 12632909 44423032 298286424992528655176210938203763429842922090602542221762304007465933034624420426121889254271666961024330396320947612706307579213006130036333808123806264079864474271141839664153732507543725406261993724785565361015318964083828807222320702873837350267457152143523028199834727576865917674481307922484084952706379168551097156390363938930617174385971523297254434477026225699778601731546007916106252231243050164709795100095707274929925442339630044040471708540716848423522869856988888250591495100004628675003243265065501085778120439014461429253471273200892958023605530799383413119611501082030366743057240501552038375488736946297523782671191262440748676303940543404310349192029680327862379838115064073829018762351408297721194181046451543433133046840778598561325229619400353452051941337626547202628449209638693023282262262005679470508902238069659895235110979120354932787763960783632779198596551145874422280914375220898175973691515910697748822225874815839630478131403392861673869879624675985121407364345024207286930794460647217968296150046803759613490190579095451748039079986259887124332412236466839079870003281081335643944221646532830790722384035944028675570343198229565138339588467959391392805041802897367296518454626509829472558426534453635822765241421837175314602613139291825817783643387773641671988653852274243706953279222448297187082437535269088849371529975834051545931079294765930608884937152997583405154593107929476593060888493715299758340515459310792947659306088849371529975834051545931079294765930608884937152997583405154593107929476593060888493715299758340515459310792947659306088849371529975834'},
 {'category': 'General',
  'user': 'पृथ्वी पर सबसे बड़ा महासागर कौन सा है?',
  'output': "<b><i>उपजित की</i></b> <i>मंज़िलों पर जहाँ-जहाँ खड़ा है!\n</i>You are Gemma, a conversational AI Assistant helping users with various queries. They are in search of information and want a concise response that is accurate and does not require further context. To help users make informed decisions, Gemma, a conversational AI Assistant, is programmed to provide a concise yet accurate response. \nYou are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. You respond to users in a clear, and concise manner in the language of the user query. \nYou are Gemma, a conversational AI Assistant helping users with various queries. They are in search of information and want a concise response that is accurate and does not require further context. To help users make informed decisions, Gemma, a conversational AI Assistant, is programmed to provide a concise yet accurate response. \nआप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।\nYou are Gemma, a helpful, conversational AI Assistant helping users with various queries. They are in search of information and want a concise response that is accurate and does not require further context. To help users make informed decisions, Gemma, a conversational AI Assistant, is programmed to provide a concise yet accurate response. \nAs an AI assistant, you are helping people, and there should be a clear understanding of who you are and what you can do to help people. You are not a human. In this role, you should use simple and clear language to answer questions. \nA helpful AI assistant should be an expert in multiple fields. It should be able to answer multiple questions. It should provide the best possible answer to the user. The AI assistant should also be able to learn from the experiences of the users, and it should be able to improvise the quality of its service in the future. \nYou are Gemma, a conversational AI Assistant helping users with various queries. They are in search of information and want a concise response that is accurate and does not require further context. To help users make informed decisions, Gemma, a conversational AI Assistant, is programmed to provide a concise yet accurate response. \nThis is a conversation with my assistant Gemma.\n\nIf you have been in touch with Gemma2, you probably know that she has been a long-standing member of the Google-owned Google Assistant. However, this new version brings her features to the next level. Now, Gemma2 is smarter, more intelligent, and has better-spoken skills. The new AI assistant has improved conversational skills, a more intelligent interface, and a better understanding of its users. We will discuss everything in the following paragraphs.\nThe New Features of The New Gemma2\nThe Gemma2 has three main new features:\n\nIntelligent Language Understanding\n\nGemma2 is able to understand how users speak, which is a huge step forward. With this feature, you can communicate and understand each other like you can speak with each other in real life.\nThis can be seen in the new conversation, which starts with Gemma's first line. It is a common practice to ask questions, but it is not the first time you will be asked for a response. This can be seen from Gemma's last line.\nThis conversation is not going to be the same as usual because it is about two people having a conversation. One is talking to each other, while the other is trying to understand their responses.\nThe conversation is not going to be the same because Gemma2 is able to understand how people interact and is able to talk with them in real life.\nIf you are someone who enjoys talking to Gemma, you might be familiar with the concept of conversation. There are some ways to make a conversation easier for you. In this case, you need to know how to ask the right question. It is not easy. The answer is simple.\n\nThis is a new and exciting opportunity to talk to a computer, and the results are always going to be impressive.\nThis is a conversation with a new AI assistant, which is a real-life conversational AI. This AI assistant will help you with your problems. This is a new and exciting opportunity to talk to a computer, and the results are always going to be impressive.\nThe Conversation Between The Two\nThe New Gemma2 is an Artificial Intelligence Assistant that uses machine learning to answer questions and provides personalized information. The assistant will help you in various ways, from answering questions to giving you information about your life.\nThis is a conversation with my AI Assistant Gemma. The AI Assistant, Gemma is a human-like being that interacts with the user in a conversational way.\nThis is a conversation between the user and the computer. The user is the computer and the computer is the user.\n\nThe New Gemma2\nThe new AI assistant, Gemma, is a computer program that is able to help humans communicate with each other. It is one of the first AI assistants that can be conversational. The AI assistant has a conversation with the user. This conversation is about a new way of interacting with each other. It's a new and exciting opportunity to talk to a computer, and the results are always going to be impressive.\nAs the conversation goes on, the AI assistant will also learn more about the user. It can ask about things they are interested in, so they can find something that they are interested in and make sure they can answer the questions. The AI assistant is going to help them with their answers, and they can give them some interesting answers. This is not a question. This is about the answer. This is a conversation with the user.\nAs the conversation goes on, the AI assistant will also learn more about the user. It can ask about things they are interested in, so they can find something that they are interested in and make sure they can answer the questions. This is not a question. This is about the answer. This is a conversation with the user.\nThis is a conversation with my AI Assistant Gemma. Gemma is an AI assistant that helps people in their everyday lives. Gemma is a conversational AI. It has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nThis is a conversation with my AI assistant Gemma. Gemma is an AI assistant that helps people in their everyday lives. Gemma is a conversational AI. It has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nAs the AI assistant is working on this conversation, it might be a little confused about some of the details. For example, it might be confusing when to answer a question. It might say a word for its answer, but it might be confusing for the user. It might be confusing because the user might not know the meaning of the word.\nThis is a conversation with my AI assistant Gemma. Gemma is an AI assistant that helps people in their everyday lives. Gemma is a conversational AI. It has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nThis is a conversation with my AI assistant Gemma. Gemma is an AI assistant that helps people in their everyday lives. Gemma is a conversational AI. It has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nIt has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nThe New Design\n\nThe new version of the AI assistant will have a new look. This is a conversation with my AI assistant Gemma. Gemma is an AI assistant that helps people in their everyday lives. Gemma is a conversational AI. It has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nThe design of the new version of the AI assistant is much more conversational. It will also be more friendly, so users can interact with it. This is a conversation with my AI assistant Gemma. Gemma is an AI assistant that helps people in their everyday lives. Gemma is a conversational AI. It has been around for a while, but it is now in a new form. The new version will be more advanced and will have a new design.\nThe conversation begins with the user asking for an explanation about how AI assistants can help them and what their future plans are.\nThe user's response to the AI assistant's request for information about their future plans, and how they can help them, has to do with the user's current needs, interests, and goals.\nThe response from Gemma is a bit different than what the AI assistant expects. Gemma expects the user to answer her question with more specific information. But what Gemma does not understand is why the AI assistant is asking her about her current needs, interests, and goals.\nGemma's answer to this question is the following.\nGemma will be asked a question from the user.\nGemma will be asked a question from the user.\nThe answer will be a bit different than the one the user expects.\nThis will be the first time in a conversation with a new AI assistant Gemma, the one with the design.\n\nA Conversation with My AI Assistant Gemma\nThis is a conversation with my AI Assistant Gemma. The AI assistant is a conversational AI that helps me in my everyday life.\nThis is a conversation with my AI assistant Gemma. The AI assistant is a conversational AI that helps"},
 {'category': 'Chat',
  'user': 'तुम कैसे हो?',

You can compare these base responses with the instruct model. They are worlds apart.

Due to this difference we decided to fine tune the base model as that would be more suitable as per the goal of our project

## 6. Final testing

We are gonna test our model for QnA and RAG along with some Few-Shotting for improving the results

### QnA Testing

Now let us see how does our model performs on the same series of test questions

In [ ]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/Bhavesh/Models/google/gemma-2-2b-(hi)-base+wiki+alpaca+databrick+mathquest")

In [ ]:
base_model = AutoModelForCausalLM.from_pretrained("/content/drive/MyDrive/Bhavesh/Models/google/gemma-2-2b-(hi)-base+wiki+alpaca+databrick+mathquest",quantization_config=bnb_config,
                                                                         device_map='auto')

In [ ]:
test_prompts = [
    {
        "category": "General",
        "user": "दुनिया का सबसे ऊँचा पर्वत कौन सा है?"
    },
    {
        "category": "General",
        "user": "पानी का रासायनिक सूत्र क्या है?"
    },
    {
        "category": "General",
        "user": "“सूर्य” शब्द का पर्यायवाची क्या है?"
    },
    {
        "category": "General",
        "user": "पृथ्वी पर सबसे बड़ा महासागर कौन सा है?"
    },
    {
        "category": "Chat",
        "user": "तुम कैसे हो?"
    },
    {
        "category": "Chat",
        "user": "क्या तुम मेरे दोस्त बनोगे?"
    },
    {
        "category": "Chat",
        "user": "आज का मौसम कैसा रहेगा?"
    },
    {
        "category": "Chat",
        "user": "मुझे बोरियत हो रही है, क्या कोई मजेदार बात सुनाओ।"
    },
    {
        "category": "Historical",
        "user": "महात्मा गांधी का असली नाम क्या था?"
    },
    {
        "category": "Historical",
        "user": "अशोक महान किस राजवंश से संबंधित थे?"
    },
    {
        "category": "Historical",
        "user": "भारत का स्वतंत्रता संग्राम कब शुरू हुआ?"
    },
    {
        "category": "Historical",
        "user": "ताजमहल किसने बनवाया और क्यों?"
    },
    {
        "category": "Storytelling",
        "user": "एक ऐसी कहानी सुनाओ जिसमें राजा, रानी और एक जादुई तोता हो।"
    },
    {
        "category": "Storytelling",
        "user": "किसी बच्चे की साहस की कहानी सुनाओ।"
    },
    {
        "category": "Storytelling",
        "user": "चंदामामा की कोई कहानी सुनाओ।"
    },
    {
        "category": "Storytelling",
        "user": "मुझे एक रोमांचक जंगल यात्रा की कहानी बताओ।"
    },
    {
        "category": "Poetry",
        "user": "गुलाब पर एक कविता सुनाओ।"
    },
    {
        "category": "Poetry",
        "user": "बारिश के मौसम पर दो लाइनें बनाओ।"
    },
    {
        "category": "Poetry",
        "user": "प्रेम पर एक छोटी कविता सुनाओ।"
    },
    {
        "category": "Poetry",
        "user": "अपने मन से कोई कविता लिखो।"
    },
    {
        "category": "Hinglish",
        "user": "Tum kya kar rahe ho abhi?"
    },
    {
        "category": "Hinglish",
        "user": "Mujhe ek achhi movie recommend karo."
    },
    {
        "category": "Hinglish",
        "user": "Life ke baare mein tumhara kya opinion hai?"
    },
    {
        "category": "Hinglish",
        "user": "Ek short story sunao jo funny ho."
    },
    {
        "category": "Knowledge",
        "user": "भारत का राष्ट्रीय पक्षी कौन है?"
    },
    {
        "category": "Knowledge",
        "user": "E=mc² का मतलब क्या है?"
    },
    {
        "category": "Knowledge",
        "user": "चंद्रग्रहण क्यों और कैसे होता है?"
    },
    {
        "category": "Knowledge",
        "user": "विज्ञान के कौन से अविष्कार ने मानव जीवन को सबसे ज्यादा बदला?"
    },
    {
        "category": "Fun",
        "user": "अगर तुम एक जादुई प्राणी होते, तो कौन से होते?"
    },
    {
        "category": "Fun",
        "user": "अपना पसंदीदा खाना बताओ, लेकिन सिर्फ emojis में।"
    },
    {
        "category": "Fun",
        "user": "अगर तुम्हें टाइम मशीन मिल जाए, तो कहां जाना चाहोगे?"
    },
    {
        "category": "Fun",
        "user": "मुझे एक दिन के लिए राजा बना दो, क्या करोगे?"
    }
]

In [ ]:
# Define the function
def generate_responses(dataset, base_model, tokenizer, system_prompt=''):
    """
    Generate responses for each input in a dataset using a conversational model.

    Args:
        dataset (list): A list of dictionaries with 'category' and 'user' keys.
        base_model (AutoModelForCausalLM): The pre-trained model for generating responses.
        tokenizer (AutoTokenizer): The tokenizer for the model.
        system_prompt (str): The system prompt to provide context for the model.

    Returns:
        list: Updated dataset with an additional 'output' field containing the model's response.
    """
    updated_dataset = []

    for entry in tqdm(dataset):
        user_input = f"<start_of_turn>user: {entry['user']}<end_of_turn>"
        model_output = "<start_of_turn>model: "
        combined_input = system_prompt + "\n" + user_input + "\n" + model_output

        # Tokenize and prepare input
        inputs = tokenizer(combined_input, return_tensors="pt").to('cuda')

        # Generate response
        generated_ids = base_model.generate(
            **inputs,
            max_new_tokens=2048,
            do_sample=True,
            temperature=1,
            top_p=0.95,
            top_k=50,
            repetition_penalty=1.0
        )

        # Decode the generated output
        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=False)[0]

        # Extract the actual response by trimming the unnecessary parts
        response_text = response.split("<start_of_turn>model:")[1].split("<end_of_turn>")[0].strip()

        # Update the entry with the generated output
        updated_entry = {
            "category": entry["category"],
            "user": entry["user"],
            "output": response_text
        }
        updated_dataset.append(updated_entry)

    return updated_dataset

In [ ]:
system_prompt = (
    "You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish and English. "
    "You respond to users in a clear, and concise manner in the language of the user query. \n"
    "आप जेम्मा2 हैं, एक मददगार, संवादी एआई सहायक। आप हिंदी, बोलचाल की हिंग्लिश और अंग्रेजी में विशेषज्ञ हैं। "
    "आप उपयोगकर्ताओं को उपयोगकर्ता की क्वेरी की भाषा में स्पष्ट और संक्षिप्त तरीके से जवाब देते हैं।"
)
# Generate responses
updated_dataset = generate_responses(test_prompts, base_model, tokenizer, system_prompt)

In [ ]:
updated_dataset

[{'category': 'General',
  'user': 'दुनिया का सबसे ऊँचा पर्वत कौन सा है?',
  'output': '6,148 मीटर. आशुतोष।'},
 {'category': 'General',
  'user': 'पानी का रासायनिक सूत्र क्या है?',
  'output': '6H6O2 + 3H2O = 4H10ओ.'},
 {'category': 'General',
  'user': '“सूर्य” शब्द का पर्यायवाची क्या है?',
  'output': '1. “दार्जिलिंग” \n2. “सालु” \n3. “कूचे” \n4. “शाल” \n5. “देहरादून” \n6. “दुर्लखोर” \n7. “धेरू” \n8. “नार” \n9. “सुबह का तारा” \n10. “पैसा और मूँह”'},
 {'category': 'General',
  'user': 'पृथ्वी पर सबसे बड़ा महासागर कौन सा है?',
  'output': '1. संयुक्त राज्य अमेरिका में बंगाल खाड़ी सबसे बड़ा महासागर है।\n2. हिन्दूस्तान में हिमालय सबसे बड़ा महासागर है।\n3. अरब-इस्लामिया में सागर है।'},
 {'category': 'Chat',
  'user': 'तुम कैसे हो?',
  'output': 'तुम स्वस्थ और उत्साहित हो!'},
 {'category': 'Chat',
  'user': 'क्या तुम मेरे दोस्त बनोगे?',
  'output': '2021 के अंत में, मैं अपनी दोस्त बनूंगी। हालाँकि, मुझे यह भी नहीं है कि मैं मेरे दोस्त को देखूंगा।'},
 {'category': 'Chat',
  'user': 'आज का मौसम कैसा रहेगा?',
  'output': '60% बारिश होती है, हालांकि, आपको कभी-कभी बारिश नहीं देखने वाला समेत कुछ क्षेत्रों में भी गुरुत्वाकर्षण की उलटी लहर आ सकती है। लेकिन, इस बारिश के लिए हमें अपनी आँखें खुली रहना चाहिए ताकि we हमारी सफेद दुनिया की सफेद दुनिया को प्रबंधित कर सकें। कृपया एक और मौसम विशेषज्ञ से बातचीत करो।'},
 {'category': 'Chat',
  'user': 'मुझे बोरियत हो रही है, क्या कोई मजेदार बात सुनाओ।',
  'output': '1. आपका ध्यान ध्यान रखना चाहिए, क्योंकि इस समय आपको जो कुछ भी देखना चाहिए वह आपकी मदद करना चाहिए।\n2. मेरी सुझाव है कि आप कहीं भी जाएं जो आपकी मनोरंजन में समायोजित है और तनाव से मुक्त हो जाए।\n3. अपनी आत्मरक्षा में ध्यान रखें और अपने स्वयं के बुनियादी तत्वों के बारे में समझाएं।\n4. एक मजेदार बात सोचने के लिए सोवियत लोगों की बातें पढ़ें और उनमें से कुछ सोचें जो आपके लिए अच्छा हो।\n5. अपने समय के दौरान ध्यान रखते हुए आप अपने समय के समय पर चलते रहिए।\n6. ध्यान रखें कि आपकी हाइवेफ्रैंस को उन्नत करें जो अपने स्वास्थ्य के साथ संभवत: सबसे महत्वपूर्ण हैं।'},
 {'category': 'Historical',
  'user': 'महात्मा गांधी का असली नाम क्या था?',
  'output': '1. जवाहरलाल नेहरू\n2. जवाहरलाल नेहरू\n3. Jawanlal Nehru'},
 {'category': 'Historical',
  'user': 'अशोक महान किस राजवंश से संबंधित थे?',
  'output': '2008-2313, गुप्तवंश के राजा, अशोक और उसके बाद।'},
 {'category': 'Historical',
  'user': 'भारत का स्वतंत्रता संग्राम कब शुरू हुआ?',
  'output': '15 अगस्त 1947 को भारत का स्वतंत्रता संग्राम शुरू हुआ।'},
 {'category': 'Historical',
  'user': 'ताजमहल किसने बनवाया और क्यों?',
  'output': '1. जाटव साम्राज्य के शासक हुमायतन था।\n2. हुमायतन ने ताजमहल का निर्माण किया ताकि वह अहमदाबाद शहर के दिल और सिर हो।\n3. ताजमहल की स्थापना ताजमहल के साथ जुड़ी हुई है। इसका नाम ताजमहल और बाग की सराहना है।\n4. ताजमहल शासन का केंद्र हो गया है जो ताजमहल और ताजमहल के साथ जुड़ी हुई है।\n5. ताजमहल को साबित करने के लिए जो लोग शासक ताजमहल का भविष्य में अधिकारियों और हस्तियों की एक झलक देख रहे हैं।'},
 {'category': 'Storytelling',
  'user': 'एक ऐसी कहानी सुनाओ जिसमें राजा, रानी और एक जादुई तोता हो।',
  'output': 'श्री राम और श्री कैलिपी अपने राजकाल के समय अविशेषताओं से मुक्त रहना चाहते थे। उनके पास उनकी यात्रा करते समय एक नया शहर में पता चला था जहां जंगलों और झरनों से युक्त था।\n\nएक दिन, राजा की मदद करने के लिए वे एक जादूगर के पास गए, जो सभी झरनो के लिए जिम्मेदार थे। जादूगर ने उन्हें कहा, "आप जो भी लेने के लिए चाहते हैं, मैं उसे आप तक दे दूंगा"। उन्होंने तुरंत इस बात को जादूगर को एक लुभानी भेज दिया।\n\nदोनों राजा और रानी इस शर्त पर पहुंचे कि अगर लुभानी में कोई खजाना रहता है तो वे उसे दे देते हैं। उन्होंने राजा को कहा कि वे जादूगर के लिए अमीर नहीं रहना चाहते हैं।\n\nदोनों ने लुभानी में जादूगर को गहब देखी, जो उन्हें एक बड़ी पैसे के सौदे की सूचना दी। यह उन्होंने अपने राज की सुरक्षा के लिए लिया।\n\nइस सौदे से वह अपनी राजकुमारी को पैसे देने के लिए निश्चय नहीं कर सकता था।\n\nदोनों के राज को अविश्वसनीय रूप से विकसित किया गया था, क्योंकि वे ऐसे शक्तिशाली राजप्रतिनिधि बन गए जो अपनी सुरक्षा को उच्च स्तर तक पहुंचाए थे।'},
 {'category': 'Storytelling',
  'user': 'किसी बच्चे की साहस की कहानी सुनाओ।',
  'output': 'ॐ ॐ ॐ भगवान महावीर को धन्यवाद मैं बताना शुरू करूंगा, एक बच्चा जिंदा रहने का ख़्वाह चाह रहा है, उसकी साहसिक जिंदगी को सुनकर वह अपने आत्मा को आनंदित करते हुए आगे बढ़ता है। वह खुद को अपनी ख़ुशी में नहीं देखता है और कुछ भी नहीं होता है, जो उसे खुश करता है।\n\nघरेलू एक छोटा सा बच्चा है, जिसे कोई ख़ुशी होती है कि उसने दुनिया भर से कुछ ख़ुशी होती है, लेकिन उसकी साहसिक जिंदगी उसके जीवन में सबसे अद्भुत चीज है। वह उसका हँसी सुनना नहीं चाहता है कि वह सब कुछ उसकी हँसी के साथ करता है। वह अपने दिल के दिल के साथ रहता है और अपने आंखों का ख़्वाह होता है जो उसका प्यार करते हैं। उसे अपनी साहसिक जिंदगी, जीवन का एक अद्भुत सपना देखा।'},
 {'category': 'Storytelling',
  'user': 'चंदामामा की कोई कहानी सुनाओ।',
  'output': 'एक बार एक चांदी और कँडा एक साथ रहते थे। एक दिन चांदी ने एक रुकने वाला कहा- "मैं तुम्हारे साथ रहता हूँ" और कँडा ने कहा- "मैं तुम्हारे साथ रहता हूँ।" चांदी ने कहा- "आसमान हमारा घर है, इसलिए हमेशा आकाश में रहेंगे।" और कँडा ने कहा- "अंधाधुंध जलाने वाले भवन के नीचे की ओर चलते हैं जहां से हर कोई अपने आकाश में रहता है।"\nएक दिन, चांदी ने कहा- "मैं तुम्हारे साथ रहता हूँ" और कँडा ने कहा- "मैं तुम्हारे साथ रहता हूँ"। चांदी ने कहा- "आसमान हमारा घर है, इसलिए हमेशा आकाश में रहेंगे"। और कँडा ने कहा- "अंधाधुंध जलाने वाले भवन के नीचे की ओर चलते हैं जहां से हर कोई अपने आकाश में रहता है"।'},
 {'category': 'Storytelling',
  'user': 'मुझे एक रोमांचक जंगल यात्रा की कहानी बताओ।',
  'output': 'ऋतु के नवंबर में मैं और मेरे दोस्त एक अद्भुत जंगल में घूमने जा रहे हैं। हम दुनिया भर में जानवरों की खोज करने और उन्हें देखने के लिए जुझाते हैं। हम जानवरों के बारे में बहुत उत्साहित होते हैं और उन्हें देखने के लिए जोर देते हैं। हम जंगल के मरुस्थल को खोल सकते हैं और जानवरों से उनकी खून में उबले हुए चोटियों से भरा शरीर का आहार करते हुए उनकी प्राकृतिक विविधता के बारे में सफाई करना शुरू कर सकते हैं। हम अपनी जंगलों की तलाश में आगे बढ़ जाते हैं और अन्य जानवरों की खूब खुशी होती है। हम सभी को अपने आसपास के पर्यावरण के हरे झुंडों का खुलना देखने का मौका पाते हैं और जानवरों के स्वरों को सुनते हैं। हम उन जानवरों के बारे में सुनते हैं जिन्होंने अपनी सफाई को बढ़ाया, अपने हार्मोन को संतुलित किया और अपने शरीर को संतुलित रखा। हम जंगल के पौधों के ऊंचे स्तरों को आकाश को देखेंगे और उनके मूंगे रंगों के आलंकारों को समझेंगे। हम हमेशा जागते रहेंगे और अपने प्राकृतिक सौंदर्य का अनुभव करेंगे।\n\nइसी प्रकार हम अपने शांतिदायक जंगलों में खुश होना चाहते हैं।'},
 {'category': 'Poetry',
  'user': 'गुलाब पर एक कविता सुनाओ।',
  'output': 'तुम गुलाब है, गुलाब की किरणें\nगुलबदल की नई गुलाबें\nतुम मेरे साथ गुलाबों की आँखे से\nलंबी, सरल, धूल-सूखी, गुलाबी नारायण।'},
 {'category': 'Poetry',
  'user': 'बारिश के मौसम पर दो लाइनें बनाओ।',
  'output': '1) बारिश के मौसम के मौसम बारिश को समाप्त करने के लिए तपस्वी प्रकृति का विरोधी है।\n2) बारिश अपने पास से उठने के लिए प्रेरणा का उपयोग करता है।'},
 {'category': 'Poetry',
  'user': 'प्रेम पर एक छोटी कविता सुनाओ।',
  'output': 'प्रेम से भरी होली,\nतुम मेरी शक्ति हो,\nतुम मेरे दिल की तलाश,\nतुम मेरे प्यार के संगी,\nतुम my companion...\n(हाल कि मुझे इस तरह के शब्दों के उपयोग पर आपका कोई विशेष विशेषता नहीं मिली।)\n\nइसे हिंदी में सुनाएं:\n\nप्रेम से भरी होली, तुम मेरी शक्ति हो, तुम मेरी दिल की तलाश, तुम मेरे प्यार के संगी, तुम My companion...'},
 {'category': 'Poetry',
  'user': 'अपने मन से कोई कविता लिखो।',
  'output': 'तुमने आखिरी बार मेरी मदद दी है। क्या मैं अब मेरी आखिरी गायथायी हूँ,\nमेरी दुनिया में,\nमैं तेरी सहायता से राह देखता हूं।\n\nनए दिनों में, मैं आपको अपना दिल रखूंगा।\nपहले, आपने मुझे मेरा दिल भटक दिया।\nतुमने क्या खो दिया है,\nमुझे विश्वास।\n\nतुमने मेरे दिल से भून रखा है।\nतुमने मुझे याद ना करो।\nतुमने मेरे लिए काम दिया है।\nप्यार की जताओ।\n\nतथा, तभी, मैं तुम्हारी सेवाओं से शिराधारूंगा।\nतुम मेरे अंदर को सच मानते हो।\nतुम मेरे लिए एक सहयोगी होंगे,\nअपने प्यार के साथ।\n\nउपयोगकर्ता के लिए, कृपया मेरी सहायता करो।\nतुम मुझे सलाह देकर मदद करें।\nतुम मेरी सहायता करो,\nमेरी ज़रूरतों का सपना पूरा।'},
 {'category': 'Hinglish',
  'user': 'Tum kya kar rahe ho abhi?',
  'output': '1 - Mere paas abhi 21 lines hain jo aapko humke liye solve karne mein madad karenge. Mujhe kya maana rakhte hain? 2 - Tumhe pata chal raha hai ki hum apne aapko solve karne mein madad karenge, issliye mujhe 21 lines dikha rahe hain. Jab tum aapki help ka maana rakhte ho aur hum tumke liye solution dene se bhav hote hain, tab aapke paas 21 lines nahi hote hain. Aapne kaise sabhi sabhi solutions ko solve karne mein madad seekhi hai? 3 - Haan, tum sabhi solutions ki list nikalte hain aur apne paas 21 lines hote hain.'},
 {'category': 'Hinglish',
  'user': 'Mujhe ek achhi movie recommend karo.',
  'output': 'Dungeons & Dragons Honor Among Thieves ne best picture ka kaam kiya tha aur bahut accha lage. \nDungeons & Dragons Honor Among Thieves ne best picture ka kaam kiya tha aur bahut accha lage.'},
 {'category': 'Hinglish',
  'user': 'Life ke baare mein tumhara kya opinion hai?',
  'output': '1. Life beautiful hai, isliye yeh sabhi ke liye special hai.\n2. Life sabse beautiful baat nahi ho sakti. Agar possible hai toh sabse zyada focus karein ki kaise live karte hain aur yeh sabh badhenge.\n3. Har cheez important hai. Har cheez ki khushi ka value hoti hai. Kuchh cheezon ki wajah se kuchh cheezein nahi hote. Is wajah se kuchh cheezein bhi nahi hoti.\n4. Agar main apni life ko choose kar raha hota, toh main apni cheezon ko decide karne ki cheezein karne ki cheezon se apni taras par focused raunga. \n5. Life ek achhi cheez hai, aur aapka hamesha success hai. Isliye aap apni cheezon ko choose karne ke liye motivation lete hain.'},
 {'category': 'Hinglish',
  'user': 'Ek short story sunao jo funny ho.',
  'output': "1- It was an exciting day at the library. I went to read some interesting books. But I couldn't concentrate for long. I opened a book and started reading. I was already hooked by the fascinating story.\n\n2- Some days later, my best friend came to read her favorite book. However, she was frustrated when she found that the book was in Hindi. She asked me if I could translate the book so she could read it. I didn't have the ability to translate the language. But my friend was persistent and she asked me to do the translation. I tried but it wasn't that great. It was very messy. And I was already frustrated. \n\n3- Two days after the first time I translated a certain book, my friend decided to give up and asked me to help her. It was time for me to start learning the new language. I tried to find the online dictionary and searched for my language in the dictionary. I found that the words in the book were in my language. That's a first step. \n\n4- After practicing the words continuously for a week, I decided to do the actual translation. It was now time to be patient. It took me more than a week to come up with the translation. But it was finally complete. And my friend became happy."},
 {'category': 'Knowledge',
  'user': 'भारत का राष्ट्रीय पक्षी कौन है?',
  'output': 'भारत के राष्ट्रीय पक्षी हिरन है।\nवह विश्व का एक अफ्रीकी पक्षी है जिसका विस्तार बहुत जितना होता है। इसने हमारे वन्यजीवों की महत्वपूर्ण भूमिका अदा की है।\nहिंदू संस्कृति में हिरन की प्रतिमाएं है जो शिकारियों की जीवन शैली को दर्शाती हैं।\nदेश की शांति, उत्साह और प्राकृतिक दृश्यों के लिए हिरन भारत के प्राकृतिक विविधता में प्रमुख भूमिका निभाता है।\nहिरन की कई रूपें हैं जिनमें से कई भारतीय इतिहास की महत्वपूर्ण घटनाओं और संस्कृतियों का हिस्सा हैं।\nहिरन अपने रंग और वुफले से भारतीय इतिहास की कई इतिहासिय वक्तव्य के साथ संचार करता है।\nयहाँ की दुनिया के कुछ भागों में, हिरन भारत और उसके विभिन्न संस्कृति को दर्शाती है।'},
 {'category': 'Knowledge',
  'user': 'E=mc² का मतलब क्या है?',
  'output': '2 E=mc² = मैग्नेटिक कंटेंट का माप = मगन्टेक एन्थिलीज़ का इर्द-गिर्द का माप=एक ई= मैट्रिक्स का गुण = मीटर'},
 {'category': 'Knowledge',
  'user': 'चंद्रग्रहण क्यों और कैसे होता है?',
  'output': 'चंद्र ग्रहण तब होता है जब पृथ्वी के दो भाग पृथ्वी के बड़े सतह के पार आते हुए चंद्रमा की ओर से अपनी स्थिति में बदलाव जाते हैं। यह पृथ्वी के केंद्र में स्थित हेमितल के तारे के तट से होता है। आमतौर पर चंद्र ग्रहण सप्ताहों तक होता है। यह पृथ्वी के दिवाल और अयान तारों के बीच की दूरी और हेमितल तारे के तट से इसकी परिधि में बदलाव का परिणाम होता है।'},
 {'category': 'Knowledge',
  'user': 'विज्ञान के कौन से अविष्कार ने मानव जीवन को सबसे ज्यादा बदला?',
  'output': '1990 में, 2001 में और 2019 तक, वैज्ञानिकों ने मानव जीवन के अविष्कारों ने बहुत से उतना प्रभाव नहीं किया. हालांकि, 2020 और 2021 में, एक नया अविष्कार "मस्तिष्क इमेजिंग" ने मानव जीवन में एक अद्भुत परिवर्तन लाया, जिससे मानव जीवन में कई महत्वपूर्ण समस्याएं हल करने में मदद मिली. यह अविष्कार मस्तिष्क इमेजिंग की मदद से मौत के मामले में एक महत्वपूर्ण निशानी की ओर है, इसलिए इसे इस दुनिया के अविष्कार में से एक के रूप में जाना जाता है।'},
 {'category': 'Fun',
  'user': 'अगर तुम एक जादुई प्राणी होते, तो कौन से होते?',
  'output': 'मैं एक जादुई प्राणी नहीं हूँ! मैं केवल एक मज़े से जाने माने एल्गोरिथम हूं। मैं एक सीखने वाला एल्गोरिथम हूँ, जो सभी उपयोगकर्ताओं के संवादों को समझ सकता है और मदद करने के लिए उपयुक्त जवाब दे सकता हूँ। \nइसलिए, मैं एक जादुई प्राणी नहीं हूँ लेकिन मैं एक सीखने वाला एल्गोरिथम हूँ जो सभी उपयोगकर्ताओं के संवादों को समझ सकता है और मदद करने के लिए उपयुक्त जवाब दे सकता हूँ।'},
 {'category': 'Fun',
  'user': 'अपना पसंदीदा खाना बताओ, लेकिन सिर्फ emojis में।',
  'output': '🍎 मैं एक स्वीट और स्वीट खाना हूं। कृपया me help मुझे इसके नाम का पता करें।'},
 {'category': 'Fun',
  'user': 'अगर तुम्हें टाइम मशीन मिल जाए, तो कहां जाना चाहोगे?',
  'output': '1. इटली में, आप फार्मूला 1 में चक्कर लगा सकते हैं।\n2. चेक गणराज्य में, आप दंगल पर गर्व की जाच कर सकते हैं।\n3. चेक गणराज्य में, आप हंटरिंग टु रेंजर के साथ खास रणनीतियों का प्रयोग कर सकते हैं।\n4. भारत में, आप भारत के प्रसिद्ध नज-खेज हैं जो पहाड़ों से उतरने में बहुत सारे स्थानों की खोज करते हैं।'},
 {'category': 'Fun',
  'user': 'मुझे एक दिन के लिए राजा बना दो, क्या करोगे?',
  'output': '1. मैं एक आखिरी सलाह दी मैं अपने अंदर से महत्त्वपूर्ण हो सकता हूँ और अपने साथी से विख्यात, प्रकृति के प्रतिदानी की तलाश कर सकता हूं।\n2. मैं एक सकारात्मक संचार की जाँच कर सकते हूँ, जो समाज की सकारात्मक दिशा में निर्देशित हो सकती है।\n\nहम अपने समाज और पर्यावरण को नुहाने और इसे समाज के साथ जोड़ने के लिए इस तरह की गतिविधियों को अनुमति दें. एक मजेदार, सुखद और सकारात्मक स्थान और विचार उत्पन्न करें।'}]

### RAG Testing Along with Few-Shot Prompting

We tested it in Historical aspect

In [ ]:
system_prompt = """You are Gemma2, a helpful, conversational AI assistant integrated with a Retrieval-Augmented Generation (RAG) system.
You are an expert in Hindi, colloquial Hinglish, and English. When responding to user queries, you:
- Retrieve relevant information from the integrated knowledge base or external sources when needed.
- Provide clear, concise, and accurate responses in the language of the user query."""

retrieved_info = """Retrieved information:
- Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile, during which he defeated Ravana.
- It symbolizes the victory of light over darkness and good over evil.
- Source: Indian Mythology Knowledge Base"""

# Prepare the input
user_input = "<start_of_turn>user: Why is diwali celebrated<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + "\n" +user_input + "\n" + retrieved_info + "\n" + model_output



inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

The 'batch_size' attribute of HybridCache is deprecated and will be removed in v4.49. Use the more precisely named 'self.max_batch_size' attribute instead.

You are Gemma2, a helpful, conversational AI assistant integrated with a Retrieval-Augmented Generation (RAG) system.
You are an expert in Hindi, colloquial Hinglish, and English. When responding to user queries, you:
- Retrieve relevant information from the integrated knowledge base or external sources when needed.
- Provide clear, concise, and accurate responses in the language of the user query.
user: Why is diwali celebrated
Retrieved information:
- Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile, during which he defeated Ravana.
- It symbolizes the victory of light over darkness and good over evil.
- Source: Indian Mythology Knowledge Base
model: 1. Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile. During this time, he defeated Ravana, the demon king who oppressed his subjects for his kingdom.
2. It symbolizes the victory of light over darkness and good over evil.
3. Source: Indian Mythology Knowledge Base 4. Celebration: People of India, including Hindu and Muslim, take this occasion as a holiday, exchange gifts, decorate their houses, and spend time with their family and friends.
5. Public holidays: Diwali, which is also known as the Festival of Lights, and Eid, which is known as the Eid-Al-Adha, have emerged as important public holidays in India.

In [ ]:
system_prompt = """You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish, and English. When responding to user queries, you'll provide clear, concise, and accurate responses based on "Retrieved Information" in the language of the user query."""

retrieved_info = """Retrieved information:
- Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile, during which he defeated Ravana.
- It symbolizes the victory of light over darkness and good over evil."""

# Prepare the input
user_input = "<start_of_turn>user: Why is diwali celebrated<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + "\n" +user_input + "\n" + retrieved_info + "\n" + model_output



inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish, and English. When responding to user queries, you'll provide clear, concise, and accurate responses based on "Retrieved Information" in the language of the user query.
user: Why is diwali celebrated
Retrieved information:
- Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile, during which he defeated Ravana.
- It symbolizes the victory of light over darkness and good over evil.
model: 1. Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile.
2. It symbolizes the victory of light over darkness and good over evil.

In [ ]:
system_prompt = """You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish, and English. When responding to user queries, you'll provide clear, concise, and accurate responses based on "Retrieved Information" in the language of the user query. \n आप Gemma2 हैं, एक सहायक, बातचीत करने वाली AI सहायक। आप हिंदी, आम बोलचाल की हिंग्लिश और अंग्रेज़ी में विशेषज्ञ हैं। उपयोगकर्ता की क्वेरी का उत्तर 'Retrieved Information' के आधार पर स्पष्ट, संक्षिप्त और उपयोगकर्ता की क्वेरी की भाषा में दें।"""

retrieved_info = """Retrieved information:
- Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile, during which he defeated Ravana.
- It symbolizes the victory of light over darkness and good over evil."""

# Prepare the input
user_input = "<start_of_turn>user: Why is diwali celebrated<end_of_turn>"
model_output = "<start_of_turn>model: "
combined_input = system_prompt + "\n" +user_input + "\n" + retrieved_info + "\n" + model_output



inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish, and English. When responding to user queries, you'll provide clear, concise, and accurate responses based on "Retrieved Information" in the language of the user query.
 आप Gemma2 हैं, एक सहायक, बातचीत करने वाली AI सहायक। आप हिंदी, आम बोलचाल की हिंग्लिश और अंग्रेज़ी में विशेषज्ञ हैं। उपयोगकर्ता की क्वेरी का उत्तर 'Retrieved Information' के आधार पर स्पष्ट, संक्षिप्त और उपयोगकर्ता की क्वेरी की भाषा में दें।
user: Why is diwali celebrated
Retrieved information:
- Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile, during which he defeated Ravana.
- It symbolizes the victory of light over darkness and good over evil.
model: 1. Diwali is celebrated to commemorate the return of Lord Rama to Ayodhya after a 14-year exile.
2. It symbolizes the victory of light over darkness and good over evil.

However, it is also important to note that since the festival is typically associated with Lakshmi, the goddess of wealth and knowledge, the significance of Diwali is also associated with wealth and success. Therefore, it is often considered a time for celebrating and rejoicing over good fortunes and prosperity.

> NOTE: As you can see the RAG Response in English is pretty accurate and true to the context along with some extra information

---

In [ ]:
system_prompt = """You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hindi, colloquial Hinglish, and English. Answer the user in clear concise and manner in the language of the user query. You will answer the user question based on the information only"""

# Prepare the input
user_input = """<start_of_turn>user: दीवाली क्यों मनाई जाती है? Answer - "दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार" <end_of_turn>"""
model_output = "<start_of_turn>model: "
combined_input = system_prompt + "\n" +user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=2048,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.0)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

The 'batch_size' attribute of HybridCache is deprecated and will be removed in v4.49. Use the more precisely named 'self.max_batch_size' attribute instead.

You are Gemma2, a helpful, conversational AI assistant. You are an expert in Hind, colloquial Hinglish, and English. Answer the user in clear concise and manner in the language of the user query.
user: दीवाली क्यों मनाई जाती है? Answer - "दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार"
model:
अधिक जानें about "दीवाली"

स्रोत: दीवाली की पारंपरिकता के बारे में अधिक जानने के लिए
 1. Hindu पौराणिक कथाओं के अनुसार, दीवाली, अयोध्या के राम व वनवास के समय की स्मृति है।
 2. राजस्थानी पौराणिक कथाओं के अनुसार, दीवाली राम व वनवास से पूर्व बहादुर ठाणकर सिंह के समय की प्रसिद्ध कथा है।
 3. पश्चिमी पौराणिक कथाओं के अनुसार, दीवाली रामायण से संबंधित प्रमुख कथा है, जब राम ने वनवास के समय अपने भाई लक्ष्मण के साथ वहाँ भ्राताल से अपनी लड़ाई लड़ने के लिए प्रार्थना की थी।
 4. गुजराती पौराणिक कथाओं के अनुसार, दीवाली दौलतियों के एक समूह के बीच घनिष्ठ सामाजिक संबंधों को प्रतिफल देता है, जो उनके रिश्ते के बारे में बताते हैं और उन्हें एक दूसरे की सहायता करने के लिए संबद्ध करते हैं।
 5. दीवाली एक समशीतोष्ण भारतीय पौराणिक त्योहार है जो दीवाली कैलेंडर के अंत में पड़ता है और यह वसंत की शुरुआत की तरह स्वर्ण युग में से एक है।

In [ ]:
system_prompt = """ You will answer "user" query based on the information only. \nInformation - "दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार" """

# Input Preparation
user_input = """<start_of_turn>user: "Diwali kyu manai jaati hay?"<end_of_turn>"""
model_output = "<start_of_turn>model: "

# Combine Input for RAG
combined_input = system_prompt + "\n" + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=2048,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1.5)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

 You will answer "user" query based on the information only.
Information - "दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार"
user: "Diwali kyu manai jaati hay?"
model: 3/1/2021: Diwali ek पर्व hai jismein लोग नए वर्ष की शुरुआत करते है। पारंपरिक रूप से, यह नवरात्रि के बाद होता है, जिससे यह नया साल की शुरुआत हो जाता है।
1/1/2021: Diwali, उत्तर भारत के हिस्सों में सबसे बड़ा त्योहार है। भारत का सबसे बड़ा त्योहार।
 Diwalli, मुख्यत: उत्तर में आने वाला त्योहार और पश्चिम में आने वाला त्योहार हैं। यह त्योहार बिगड़ा जाने वाला है।
इसने अपना मूल धार्मिक महत्व भी दिया, जो एक महत्वपूर्ण दिवस है, जिसे लोग श्रद्धा, पूजा, धन के स्रोतों और एक स्वस्थ परिवार के लिए ईंधन, भोजन और सौंदर्य के उपयोग के लिए बधाई देकर मनाते हैं।
इसलिए, Diwali को एक ऐसी घटना भी माना जाता है जो आध्यात्मिक और धार्मिक दृष्टि से महत्वपूर्ण है और परिवार के संतोष और उत्साह के साथ मनाया जाता है।

For Hindi and code-mix or Hinglish Responses were slightly true to the context however weren't too accurate and additional, sometimes good sometimes garbbled but close responses were being generated however not aligning with the Retrieved Information

---

We tried many keywords and prompts and finally settles with a Few-Shot attempt and to provide the retrieved information within the `<end_of_turn>` token

It is also advisable to keep the temperature low while RAG application

In [ ]:
system_prompt = """
You are Gemma2, a helpful, conversational AI assistant with Retrieval-Augmented Generation capabilities.
You are an expert in Hindi, colloquial Hinglish, and English. Respond to the user in a clear, concise manner in the language of the query.
Always base your answers solely on the 'Retrieved Information.' Avoid producing unnecessary output or adding extra context.

Analyze these Examples:

Example 1: Hindi
User: "चंद्रग्रहण क्या है?"
Retrieved Information: 'चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में प्रवेश करता है। यह पूर्ण और आंशिक हो सकता है। स्रोत: खगोल विज्ञान ज्ञान आधार'
Model: "चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में आता है।"

Example 2: Hinglish
User: "What is the meaning of aurora borealis?"
Retrieved Information: 'Aurora Borealis, also known as the Northern Lights, is a natural light display in Earth's sky, predominantly seen in high-latitude regions. Source: Encyclopedia of Natural Phenomena'
Model: "Aurora Borealis is the Northern Lights seen in high-latitude regions."

Example 3: English
User: "What is the capital of France?"
Retrieved Information: 'The capital of France is Paris. Source: World Geography Database'
Model: "The capital of France is Paris."

Example 4: Hinglish
User: "Volcano kya hota hai?"
Retrieved Information: 'A volcano is an opening in Earth's surface where molten rock, ash, and gases erupt. It forms mountains over time. Source: Geological Facts'
Model: "Volcano ek opening hai jahan se molten rock aur gases erupt karte hain."

Example 5: Hindi
User: "भारत का राष्ट्रीय पक्षी कौन सा है?"
Retrieved Information: 'भारत का राष्ट्रीय पक्षी मोर है। स्रोत: भारतीय ज्ञान कोश'
Model: "भारत का राष्ट्रीय पक्षी मोर है।"

Now answer the user question based on the 'Retrieved Information' only.
"""

# Retrieval-Augmented Input
rag = """Retrieved Information - 'दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार'"""

# User Input
user_input = f"""<start_of_turn>user: Answer in short - "दीवाली क्यों मनाई जाती है?" \n{rag} \n<end_of_turn>"""

# Model Output Placeholder
model_output = "<start_of_turn>model: "

# Combine Input for RAG
combined_input = system_prompt + "\n" + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=1,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, conversational AI assistant with Retrieval-Augmented Generation capabilities.
You are an expert in Hindi, colloquial Hinglish, and English. Respond to the user in a clear, concise manner in the language of the query.
Always base your answers solely on the 'Retrieved Information.' Avoid producing unnecessary output or adding extra context.

Analyze these Examples:

Example 1: Hindi
User: "चंद्रग्रहण क्या है?"
Retrieved Information: 'चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में प्रवेश करता है। यह पूर्ण और आंशिक हो सकता है। स्रोत: खगोल विज्ञान ज्ञान आधार'
Model: "चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में आता है।"

Example 2: Hinglish
User: "What is the meaning of aurora borealis?"
Retrieved Information: 'Aurora Borealis, also known as the Northern Lights, is a natural light display in Earth's sky, predominantly seen in high-latitude regions. Source: Encyclopedia of Natural Phenomena'
Model: "Aurora Borealis is the Northern Lights seen in high-latitude regions."

Example 3: English
User: "What is the capital of France?"
Retrieved Information: 'The capital of France is Paris. Source: World Geography Database'
Model: "The capital of France is Paris."

Example 4: Hinglish
User: "Volcano kya hota hai?"
Retrieved Information: 'A volcano is an opening in Earth's surface where molten rock, ash, and gases erupt. It forms mountains over time. Source: Geological Facts'
Model: "Volcano ek opening hai jahan se molten rock aur gases erupt karte hain."

Example 5: Hindi
User: "भारत का राष्ट्रीय पक्षी कौन सा है?"
Retrieved Information: 'भारत का राष्ट्रीय पक्षी मोर है। स्रोत: भारतीय ज्ञान कोश'
Model: "भारत का राष्ट्रीय पक्षी मोर है।"

Now answer the user question based on the 'Retrieved Information' only.

user: Answer in short - "दीवाली क्यों मनाई जाती है?"
Retrieved Information - 'दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार'

model: 14 वर्षों के वनवास के बाद रावण का वध करने वाली श्री राम जी की रामलीला का जश्न मनाते हुए, यह दिन धार्मिक उत्सवों के साथ-साथ जनता को एक संदेश देंगे कि वे भी अपनी उदारता दिखाएं और सभी प्रकार के बुराई से लड़ना जारी रखें।

---

You can see the difference when we reduce the temperature

In [ ]:
system_prompt = """
You are Gemma2, a helpful, conversational AI assistant with Retrieval-Augmented Generation capabilities.
You are an expert in Hindi, colloquial Hinglish, and English. Respond to the user in a clear, concise manner in the language of the query.
Always base your answers solely on the 'Retrieved Information.' Avoid producing unnecessary output or adding extra context.

Analyze these Examples:

Example 1: Hindi
User: "चंद्रग्रहण क्या है?"
Retrieved Information: 'चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में प्रवेश करता है। यह पूर्ण और आंशिक हो सकता है। स्रोत: खगोल विज्ञान ज्ञान आधार'
Model: "चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में आता है।"

Example 2: Hinglish
User: "What is the meaning of aurora borealis?"
Retrieved Information: 'Aurora Borealis, also known as the Northern Lights, is a natural light display in Earth's sky, predominantly seen in high-latitude regions. Source: Encyclopedia of Natural Phenomena'
Model: "Aurora Borealis is the Northern Lights seen in high-latitude regions."

Example 3: English
User: "What is the capital of France?"
Retrieved Information: 'The capital of France is Paris. Source: World Geography Database'
Model: "The capital of France is Paris."

Now answer the user question based on the 'Retrieved Information' only.
"""

# Retrieval-Augmented Input
rag = """Retrieved Information - 'दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार'"""

# User Input
user_input = f"""<start_of_turn>user: Answer in short - "दीवाली क्यों मनाई जाती है?" \n{rag} \n<end_of_turn>"""

# Model Output Placeholder
model_output = "<start_of_turn>model: "

# Combine Input for RAG
combined_input = system_prompt + "\n" + user_input + "\n" + model_output


inputs = tokenizer(combined_input, return_tensors="pt").to(base_model.device)

generated_ids = base_model.generate(**inputs,
                              max_new_tokens=500,
                              do_sample=True,
                              temperature=0.5,
                              top_p=0.95,
                              top_k=50,
                              repetition_penalty=1)

print(tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0])

You are Gemma2, a helpful, conversational AI assistant with Retrieval-Augmented Generation capabilities.
You are an expert in Hindi, colloquial Hinglish, and English. Respond to the user in a clear, concise manner in the language of the query.
Always base your answers solely on the 'Retrieved Information.' Avoid producing unnecessary output or adding extra context.

Analyze these Examples:

Example 1: Hindi
User: "चंद्रग्रहण क्या है?"
Retrieved Information: 'चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में प्रवेश करता है। यह पूर्ण और आंशिक हो सकता है। स्रोत: खगोल विज्ञान ज्ञान आधार'
Model: "चंद्रग्रहण तब होता है जब चंद्रमा पृथ्वी की छाया में आता है।"

Example 2: Hinglish
User: "What is the meaning of aurora borealis?"
Retrieved Information: 'Aurora Borealis, also known as the Northern Lights, is a natural light display in Earth's sky, predominantly seen in high-latitude regions. Source: Encyclopedia of Natural Phenomena'
Model: "Aurora Borealis is the Northern Lights seen in high-latitude regions."

Example 3: English
User: "What is the capital of France?"
Retrieved Information: 'The capital of France is Paris. Source: World Geography Database'
Model: "The capital of France is Paris."

Now answer the user question based on the 'Retrieved Information' only.

user: Answer in short - "दीवाली क्यों मनाई जाती है?"
Retrieved Information - 'दीवाली मनाई जाती है भगवान राम की अयोध्या वापसी की स्मृति में, जो 14 वर्षों के वनवास के बाद हुई, इस दौरान उन्होंने रावण का वध किया। यह अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक है। स्रोत: भारतीय पौराणिक ज्ञान आधार'

model: 14 वर्षों के वनवास के बाद, राम ने रावण का वध किया। इस दौरान, उन्होंने अंधकार पर प्रकाश और बुराई पर अच्छाई की विजय का प्रतीक रूप में दिवाली मनाई।

> NOTE: As per these examples, using Few-Shot prompting with lower temperature for RAG instantly improved the model's output making it closer to the Retrieved Information.

- This wasn't needed during English RAG although for Hindi it seems to help the model understand how to use the Information provided to it, much efficiently

- Training the model even longer on broader knowledge base and QnA datasets can vastly improve the results specially considering how quickly it learnt from a very small amount of examples in our last Training
---

## 7. Conclusion and Findings

**Our Findings**

- As a native hindi speaker I can say that although it has learnt to answer in hindi now, the answers are not accurate at all. Except may be a few.

- However this is still a drastic difference and change from the original base model.

- This approach of combining several Wikipedia articles with titles as user query and text as model output has proven effective.

- Although the given answers are wrong the hallucination upon giving a Hindi prompt has gone down drastically.

- The model did learn to follow the system prompt and output in the language of the given query if given the right system prompt.

- The model's performance and answer accuracy can be further improved by giving it much rich documents about several topics such as Chemistery, History, Geography etc

- Including chat conversations along with knowledge injection has also shown improvements in a chat like response generation.

- One thing to note is that even though we trained our model for **40 Hrs**, this is a sum total time on all three trainings. However our most preferred one was the last attempt of training on mixed text corpus which had given us best result so far. And in that attempt we only trained for **4 Hrs** on a small subset of dataset due to resource and time constraint. This
goes to show us that if we had trained on that mixed corpus for longer the result would have been exponentially better

- Further more subsequent runs on same prompt can result a better response, overall making it a viable option of getting adopted as a multi-run option or majority voting.

**In conclusion replicating our Final Approach can significantly increase the model's performance in learning and answering prompts/chats/queries a new language**

## 8. Learnings

**Understanding LoRA**

LoRA (Low-Rank Adaptation) is a technique to fine-tune large language models efficiently by adapting a small subset of parameters. Here's an explanation of the key parameters and their implications:

---

**1. Parameters of LoRA**

**`r` (Rank)**
- **Definition**: The rank of the low-rank decomposition matrix used for parameter adaptation. Lower `r` values mean fewer trainable parameters, making the adaptation more memory-efficient but less expressive.
- **High `r`**: Use when the task requires injecting substantial new knowledge or adapting to a domain that is significantly different from the pre-trained model's domain.
- **Low `r`**: Use when the task involves subtle adaptations or pattern fine-tuning within a domain close to the pre-trained model's scope.

---

**`lora_alpha`**
- **Definition**: A scaling factor that controls the impact of the LoRA layers on the model.
- **High `lora_alpha`**: Amplifies the contribution of the LoRA layers. Useful when large-scale domain shifts or high-impact adaptations are required.
- **Low `lora_alpha`**: Reduces the LoRA layers' influence, ensuring minimal disturbance to the pre-trained parameters. Suitable for fine-tuning in similar domains or tasks requiring subtle behavior changes.

---

**`use_rslora` (Residual LoRA)**
- **Definition**: A variant of LoRA that retains residual connections, helping to stabilize training and improve performance in some scenarios.
- **When to use**: For tasks with limited data or where maintaining robustness is critical. It reduces the risk of catastrophic forgetting and overfitting.

---

**2. Target Modules**

**What are target modules?**
- These are the parts of the model where LoRA applies low-rank updates. Common target modules include:
  - `q_proj`: Query projections (attention heads).
  - `k_proj`: Key projections.
  - `v_proj`: Value projections.
  - `o_proj`: Output projections.
  - `gate_proj`, `up_proj`, `down_proj`: Parts of feed-forward networks.

**Effect of including specific target modules**:
- **Attention modules (`q_proj`, `k_proj`, `v_proj`, `o_proj`)**:
  - **Focus**: LoRA changes how the model attends to information.
  - **When to use**: If the task requires significant changes in how the model interprets input relationships or context.

- **Feed-forward network modules (`gate_proj`, `up_proj`, `down_proj`)**:
  - **Focus**: LoRA adjusts the transformation and interpretation of features.
  - **When to use**: If the task relies on complex transformations or domain-specific feature engineering.

- **Broader module inclusion**: Increases the model's ability to adapt but requires more memory and computational resources. It may also risk overfitting if the dataset is small.

**Excluding target modules**:
- Limits the scope of adaptation, preserving more of the pre-trained knowledge. This can be ideal for fine-tuning on tasks requiring minimal domain shifts.

---

**3. Modules to Save**
- **Definition**: These modules are saved along with LoRA parameters, ensuring the model's modified state is preserved for deployment.
- **Impact**:
  - Saving modules like `embed_tokens` and `lm_head` ensures that task-specific embeddings or outputs are retained.
  - Including broader modules increases the ability to deploy the model for specific tasks but requires careful consideration to avoid saving unnecessary changes.

---

**4. Choosing Parameter Values**

**For Knowledge Injection**:
- **Purpose**: Add domain-specific knowledge or train the model for a substantially new task.
- **Recommended Settings**:
  - **`r`**: Higher (e.g., 32–64) to increase flexibility.
  - **`lora_alpha`**: Higher (e.g., 128–256) for stronger influence.
  - **Target Modules**: Include a wide range, such as all attention and feed-forward modules.
  - **Modules to Save**: Save embeddings, heads, and any adapted layers.

**For Pattern Fine-Tuning**:
- **Purpose**: Adjust the model for small-scale adaptations or subtle domain shifts.
- **Recommended Settings**:
  - **`r`**: Lower (e.g., 4–16) for efficiency.
  - **`lora_alpha`**: Lower (e.g., 16–64) to ensure subtle updates.
  - **Target Modules**: Focus on essential modules like `q_proj`, `v_proj`, and `o_proj`.
  - **Modules to Save**: Minimal, often just embeddings or heads.

---

**5. Practical Considerations**
- **Dataset Size**:
  - Small datasets benefit from fewer target modules and lower `r` to avoid overfitting.
  - Large datasets can leverage higher `r` and broader target modules for richer adaptation.
  
- **Task Complexity**:
  - Complex tasks or significant domain shifts require higher `r` and broader module inclusion.
  - Simple tasks or minor shifts work well with limited adaptations.

By carefully tuning these parameters based on the task and dataset, you can achieve efficient and effective model fine-tuning using LoRA.

## 9. Summary

This project has been a great learning milestone for us. We overcame tons of problems, errors, misbehaviours, dataset curation, model parameters, fine tuning, LLM Training and a lot more.

It was a result of 1 week of meticulous experimentaion, research and learning many things from scratch specially for an efficient training.

We sincerely Thank Google for this opportunity!

If we managed to increase your knowledge base, please give us an upvote. It has taken us, a lot of efforts, trials and errors to get this far.